Repository kubernetes-client/java, pull requests merged in 2018-07, with the labels that each got.

#301 Update Guava dependency.
  examples/pom.xml
  util/pom.xml
Labels: cncf-cla: yes, size/XS

#312 Support refresh for Azure Active Directory tokens.
  util/pom.xml
  util/src/main/java/io/kubernetes/client/util/authenticators/AzureActiveDirectoryAuthenticator.java
Labels: cncf-cla: yes, size/M

#298 Correctly load base64-encoded strings from Secret Yaml files.
  util/src/main/java/io/kubernetes/client/util/Yaml.java
  util/src/test/java/io/kubernetes/client/util/YamlTest.java
  util/src/test/resources/test.yaml
Labels: cncf-cla: yes, size/L

#313 Add config file persistence.
  util/src/main/java/io/kubernetes/client/util/ClientBuilder.java
  util/src/main/java/io/kubernetes/client/util/ConfigPersister.java
  util/src/main/java/io/kubernetes/client/util/FilePersister.java
  util/src/main/java/io/kubernetes/client/util/KubeConfig.java
  util/src/test/java/io/kubernetes/client/ExecTest.java
  util/src/test/java/io/kubernetes/client/util/FilePersisterTest.java
  util/src/test/resources/kubeconfig-http
Labels: cncf-cla: yes, size/L

#314 Avoid use SystemClassLoader on Yaml.
  util/src/main/java/io/kubernetes/client/util/Yaml.java
Labels: cncf-cla: yes, size/XS

#316 Format Compatibility Table in README
  README.md
Labels: cncf-cla: yes, size/S

#322 Close watches more cleanly.
  util/src/main/java/io/kubernetes/client/util/Watch.java
Labels: cncf-cla: yes, size/XS

#323 feat (#137): Introduce builder generation.
  kubernetes/build.gradle
  kubernetes/pom.xml
  kubernetes/src/main/java/io/kubernetes/client/fluent/Config.java
  kubernetes/src/test/java/io/kubernetes/client/models/V1PodBuilderTest.java
Labels: cncf-cla: yes, size/M

#325 Release 3.0.0-beta1
  CHANGELOG.md
  examples/pom.xml
  kubernetes/pom.xml
  pom.xml
  proto/pom.xml
  util/pom.xml
Labels: cncf-cla: yes, size/M
