Repository kubernetes-client/java, pull requests merged in 2018-09, with the labels that each got.

#355 Added more example with Java SE 8 Lambda expression
  examples/pom.xml
  examples/src/main/java/io/kubernetes/client/examples/ExpandedExample.java
Labels: approved, cncf-cla: yes, lgtm, size/L

#359 Example of fluent builders.
  .gitignore
  examples/src/main/java/io/kubernetes/client/examples/FluentExample.java
  kubernetes/pom.xml
Labels: approved, cncf-cla: yes, lgtm, size/M

#370 add constructDateTime to snakeYaml CustomConstructor
  util/src/main/java/io/kubernetes/client/util/Yaml.java
  util/src/test/java/io/kubernetes/client/util/YamlTest.java
Labels: approved, cncf-cla: yes, lgtm, size/M

#371 Improve code generation documentation.
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#362 Release 3.0.0-beta2
  CHANGELOG.md
  examples/pom.xml
  kubernetes/pom.xml
  pom.xml
  proto/pom.xml
  util/pom.xml
Labels: approved, cncf-cla: yes, lgtm, size/S

#366 Dropped reference to gson internal API
  kubernetes/src/main/java/io/kubernetes/client/JSON.java
Labels: approved, cncf-cla: yes, lgtm, size/S
