Repository kubernetes-client/java, pull requests merged in 2018-10, with the labels that each got.

#379 Update the versions used in the README to latest stable and beta
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#387 Changed to set USERPROFILE on Windows environment.
  util/src/main/java/io/kubernetes/client/util/KubeConfig.java
Labels: approved, cncf-cla: yes, lgtm, size/XS

#390 Expand HOME detection on Windows.
  util/src/main/java/io/kubernetes/client/util/ClientBuilder.java
  util/src/main/java/io/kubernetes/client/util/KubeConfig.java
Labels: approved, cncf-cla: yes, lgtm, size/M

#375 Add utilities for copying files.
  examples/src/main/java/io/kubernetes/client/examples/CopyExample.java
  util/pom.xml
  util/src/main/java/io/kubernetes/client/Copy.java
Labels: approved, cncf-cla: yes, lgtm, size/L

#395 Add coverage reporting to util pom.xml
  util/pom.xml
Labels: approved, cncf-cla: yes, lgtm, size/S

#393 Add a simple example test.
  examples/pom.xml
  examples/src/test/java/io/kubernetes/client/examples/ExampleTest.java
Labels: approved, cncf-cla: yes, lgtm, size/M

#403 Release 3.0.0
  README.md
  examples/pom.xml
  kubernetes/pom.xml
  pom.xml
  proto/pom.xml
  util/pom.xml
Labels: approved, cncf-cla: yes, lgtm, size/M
