Repository kubernetes-client/java, pull requests merged in 2018-08, with the labels that each got.

#332 Add security contacts.
  SECURITY_CONTACTS
Labels: cncf-cla: yes, size/S

#331 Clear KUBECONFIG env variable before tests.
  util/src/test/java/io/kubernetes/client/util/ClientBuilderTest.java
  util/src/test/java/io/kubernetes/client/util/ConfigTest.java
Labels: cncf-cla: yes, size/XS

#330 Use project version instead of directly reference
  examples/pom.xml
  util/pom.xml
Labels: cncf-cla: yes, size/S

#334 Exlude com.sun.tools from io.sundr.builder-annotations transitive dep…
  kubernetes/pom.xml
Labels: cncf-cla: yes, size/XS

#336 adding sample yaml to test examples.jar from with in a pod
  examples/Dockerfile
  examples/createPod.sh
  examples/test.yaml
Labels: cncf-cla: yes, size/M

#320 Add CONTRIBUTING.md
  CONTRIBUTING.md
  README.md
Labels: cncf-cla: yes, size/M

#344 Implemented equals method for Quantity
  kubernetes/src/main/java/io/kubernetes/client/custom/Quantity.java
Labels: cncf-cla: yes, size/S

#339 support client certificate chain
  util/src/main/java/io/kubernetes/client/util/SSLUtils.java
Labels: cncf-cla: yes, size/S
