Repository kubernetes-client/java, pull requests merged in 2018-11, with the labels that each got.

#414 Fix formatting in Quantity.java
  kubernetes/src/main/java/io/kubernetes/client/custom/Quantity.java
Labels: approved, cncf-cla: yes, lgtm, size/L

#416 Use two space indentation in some test classes
  kubernetes/src/test/java/io/kubernetes/client/JSONTest.java
  kubernetes/src/test/java/io/kubernetes/client/custom/SuffixFormatterTest.java
  kubernetes/src/test/java/io/kubernetes/client/models/V1PodBuilderTest.java
Labels: approved, cncf-cla: yes, lgtm, size/L

#415 Remove extra `Quantity.fromString()` call
  kubernetes/src/main/java/io/kubernetes/client/custom/Quantity.java
Labels: approved, cncf-cla: yes, lgtm, size/XS

#412 Add merge in ProtoClient
  util/src/main/java/io/kubernetes/client/ProtoClient.java
Labels: approved, cncf-cla: yes, lgtm, size/S

#402 Remove the generated README it was confusing and incorrect.
  README.md
  kubernetes/.swagger-codegen-ignore
  kubernetes/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XL

#418 Release 4.0.0-beta1
  examples/pom.xml
  kubernetes/pom.xml
  pom.xml
  proto/pom.xml
  util/pom.xml
Labels: approved, cncf-cla: yes, lgtm, size/S

#426 minor code fixes and unit tests added to KubeConfig
  util/src/main/java/io/kubernetes/client/util/KubeConfig.java
  util/src/main/java/io/kubernetes/client/util/authenticators/AzureActiveDirectoryAuthenticator.java
  util/src/main/java/io/kubernetes/client/util/authenticators/GCPAuthenticator.java
  util/src/test/java/io/kubernetes/client/util/FilePersisterTest.java
  util/src/test/java/io/kubernetes/client/util/KubeConfigTest.java
Labels: approved, cncf-cla: yes, lgtm, size/M

#419 Update change log.
  CHANGELOG.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#442 Fix serialization of null quantities
  kubernetes/src/main/java/io/kubernetes/client/custom/Quantity.java
Labels: approved, cncf-cla: yes, lgtm, size/XS

#444 add the boilerplate file
  util/src/main/java/io/kubernetes/client/PortForward.java
  util/src/main/java/io/kubernetes/client/ProtoClient.java
Labels: approved, cncf-cla: yes, lgtm, size/S

#445 Update ProtoClient.java
  util/src/main/java/io/kubernetes/client/ProtoClient.java
Labels: approved, cncf-cla: yes, lgtm, size/XS
