Repository kubernetes-client/java, pull requests merged in 2019-09, with the labels that each got.

#683 Fix: add lacked ratelimiter initialization
  extended/src/main/java/io/kubernetes/client/extended/workqueue/DefaultRateLimitingQueue.java
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#691 Fix a bug where the error stream for port forwarding was an input stream
  util/src/main/java/io/kubernetes/client/PortForward.java
Labels: approved, cncf-cla: yes, lgtm, size/XS

#692 Fix a dropped parameter.
  util/src/main/java/io/kubernetes/client/Copy.java
Labels: approved, cncf-cla: yes, lgtm, size/XS

#694 mockito 3.0.0
  extended/pom.xml
  util/pom.xml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#701 Fix exec to look up container name if absent.
  util/src/main/java/io/kubernetes/client/Exec.java
  util/src/test/java/io/kubernetes/client/CopyTest.java
  util/src/test/java/io/kubernetes/client/ExecTest.java
Labels: approved, cncf-cla: yes, lgtm, size/S

#697 Fix error handling.
  examples/src/main/java/io/kubernetes/client/examples/WebSocketsExample.java
  util/src/main/java/io/kubernetes/client/Copy.java
  util/src/main/java/io/kubernetes/client/Exec.java
  util/src/main/java/io/kubernetes/client/util/WebSocketStreamHandler.java
  util/src/main/java/io/kubernetes/client/util/WebSockets.java
  util/src/test/java/io/kubernetes/client/ExecTest.java
Labels: approved, cncf-cla: yes, lgtm, size/M

#700 Improve close behavior some.
  util/src/main/java/io/kubernetes/client/Copy.java
  util/src/main/java/io/kubernetes/client/Exec.java
  util/src/main/java/io/kubernetes/client/util/Watch.java
  util/src/main/java/io/kubernetes/client/util/WebSocketStreamHandler.java
  util/src/main/java/io/kubernetes/client/util/WebSockets.java
Labels: approved, cncf-cla: yes, lgtm, size/M

#711 Fix typo in ControllerExample
  examples/src/main/java/io/kubernetes/client/examples/ControllerExample.java
Labels: approved, cncf-cla: yes, lgtm, size/XS
