Repository kubernetes-client/java, pull requests merged in 2019-11, with the labels that each got.

#773 Doc: Emphasis setting infinite timeout in controller example
  examples/src/main/java/io/kubernetes/client/examples/ControllerExample.java
Labels: approved, cncf-cla: yes, lgtm, size/XS

#771 Chore: Document "-l" option for the crd java model gen
  docs/generate-model-from-third-party-resources.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#772 Feat: Fundamental label selector utils
  util/src/main/java/io/kubernetes/client/util/labels/EqualityMatcher.java
  util/src/main/java/io/kubernetes/client/util/labels/LabelMatcher.java
  util/src/main/java/io/kubernetes/client/util/labels/LabelSelector.java
  util/src/main/java/io/kubernetes/client/util/labels/SetMatcher.java
  util/src/test/java/io/kubernetes/client/util/labels/LabelSelectorTest.java
Labels: approved, cncf-cla: yes, lgtm, size/XL

#776 Modify Incorrect URL address
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#786 Resetting wiremock to fix flaky test
  util/src/test/java/io/kubernetes/client/CopyTest.java
Labels: approved, cncf-cla: yes, lgtm, size/XS

#790 Adding more info logs on starting/stopping controller
  extended/src/main/java/io/kubernetes/client/extended/controller/LeaderElectingController.java
Labels: approved, cncf-cla: yes, lgtm, size/S

#791 Pin commons-collections dependency
  extended/pom.xml
  pom.xml
  util/pom.xml
Labels: approved, cncf-cla: yes, lgtm, size/S

#793 Chore: Split reflect utils to [Object|List]accessor for clarification
  extended/src/main/java/io/kubernetes/client/extended/controller/Controllers.java
  extended/src/main/java/io/kubernetes/client/extended/pager/Pager.java
  util/src/main/java/io/kubernetes/client/informer/cache/Caches.java
  util/src/main/java/io/kubernetes/client/informer/cache/ReflectorRunnable.java
  util/src/main/java/io/kubernetes/client/util/ListAccessor.java
  util/src/main/java/io/kubernetes/client/util/ObjectAccessor.java
  util/src/main/java/io/kubernetes/client/util/Reflect.java
Labels: approved, cncf-cla: yes, lgtm, size/L

#797 Constructs informer by setting lister-watcher from InformerFactory
  util/src/main/java/io/kubernetes/client/informer/SharedInformerFactory.java
Labels: approved, cncf-cla: yes, lgtm, size/S

#810 declare QuantityAdapter static
  kubernetes/src/main/java/io/kubernetes/client/custom/Quantity.java
Labels: approved, cncf-cla: yes, lgtm, size/XS

#807 Extract thread pool shutdown to a separate method
  util/src/main/java/io/kubernetes/client/informer/SharedInformerFactory.java
Labels: approved, cncf-cla: yes, lgtm, size/S

#812 update snakeyaml to 1.25
  util/pom.xml
Labels: approved, cncf-cla: yes, lgtm, size/XS
