Repository kubernetes-client/java, pull requests merged in 2019-03, with the labels that each got.

#519 Fix some problems with watches that return a v1.Status
  util/src/main/java/io/kubernetes/client/util/Watch.java
  util/src/test/java/io/kubernetes/client/util/WatchTest.java
Labels: approved, cncf-cla: yes, lgtm, size/L

#520 Added support for KUBECONFIG environment variable with multiple paths.
  util/src/main/java/io/kubernetes/client/util/ClientBuilder.java
  util/src/test/java/io/kubernetes/client/util/ClientBuilderTest.java
Labels: approved, cncf-cla: yes, lgtm, size/M

#461 Java informer portal implementation
  examples/src/main/java/io/kubernetes/client/examples/InformerExample.java
  util/pom.xml
  util/src/main/java/io/kubernetes/client/informer/EventType.java
  util/src/main/java/io/kubernetes/client/informer/ListerWatcher.java
  util/src/main/java/io/kubernetes/client/informer/ResourceEventHandler.java
  util/src/main/java/io/kubernetes/client/informer/ResyncRunnable.java
  util/src/main/java/io/kubernetes/client/informer/SharedIndexInformer.java
  util/src/main/java/io/kubernetes/client/informer/SharedInformer.java
  util/src/main/java/io/kubernetes/client/informer/SharedInformerFactory.java
  util/src/main/java/io/kubernetes/client/informer/cache/Cache.java
  util/src/main/java/io/kubernetes/client/informer/cache/Controller.java
  util/src/main/java/io/kubernetes/client/informer/cache/DeltaFIFO.java
  util/src/main/java/io/kubernetes/client/informer/cache/Indexer.java
  util/src/main/java/io/kubernetes/client/informer/cache/Lister.java
  util/src/main/java/io/kubernetes/client/informer/cache/ProcessorListener.java
  util/src/main/java/io/kubernetes/client/informer/cache/ReflectorRunnable.java
  util/src/main/java/io/kubernetes/client/informer/cache/SharedProcessor.java
  util/src/main/java/io/kubernetes/client/informer/cache/Store.java
  util/src/main/java/io/kubernetes/client/informer/exception/BadNotificationException.java
  util/src/main/java/io/kubernetes/client/informer/exception/BadObjectException.java
  util/src/main/java/io/kubernetes/client/informer/exception/BuildInformerException.java
  util/src/main/java/io/kubernetes/client/informer/impl/DefaultSharedIndexInformer.java
  util/src/main/java/io/kubernetes/client/util/CallGeneratorParams.java
  util/src/main/java/io/kubernetes/client/util/Reflect.java
  util/src/main/java/io/kubernetes/client/util/Watch.java
  util/src/main/java/io/kubernetes/client/util/Watchable.java
  util/src/main/java/io/kubernetes/client/util/common/Collections.java
  util/src/main/java/io/kubernetes/client/util/exception/ObjectMetaReflectException.java
  util/src/test/java/io/kubernetes/client/informer/cache/CacheTest.java
  util/src/test/java/io/kubernetes/client/informer/cache/ControllerTest.java
  util/src/test/java/io/kubernetes/client/informer/cache/DeltaFIFOTest.java
  util/src/test/java/io/kubernetes/client/informer/cache/ListerTest.java
  util/src/test/java/io/kubernetes/client/informer/cache/MockWatch.java
  util/src/test/java/io/kubernetes/client/informer/cache/ProcessorListenerTest.java
  util/src/test/java/io/kubernetes/client/informer/cache/ReflectorRunnableTest.java
  util/src/test/java/io/kubernetes/client/informer/cache/SharedProcessorTest.java
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#522 Fixes watch conflict handling in informer and more test coverage
  util/src/main/java/io/kubernetes/client/informer/cache/ReflectorRunnable.java
  util/src/test/java/io/kubernetes/client/informer/cache/ControllerTest.java
  util/src/test/java/io/kubernetes/client/informer/cache/MockRunOnceListerWatcher.java
  util/src/test/java/io/kubernetes/client/informer/impl/DefaultSharedIndexInformerTest.java
Labels: approved, cncf-cla: yes, lgtm, size/L

#521 Delete non-Maven build scripts
  kubernetes/.gitignore
  kubernetes/.swagger-codegen-ignore
  kubernetes/.travis.yml
  kubernetes/build.gradle
  kubernetes/build.sbt
  kubernetes/gradle.properties
  kubernetes/gradle/wrapper/gradle-wrapper.jar
  kubernetes/gradle/wrapper/gradle-wrapper.properties
  kubernetes/gradlew
  kubernetes/gradlew.bat
  kubernetes/settings.gradle
Labels: approved, cncf-cla: yes, lgtm, size/L

#512 #238: support client.authentication.k8s.io/v1beta1 ExecCredential
  pom.xml
  util/src/main/java/io/kubernetes/client/util/ClientBuilder.java
  util/src/main/java/io/kubernetes/client/util/Config.java
  util/src/main/java/io/kubernetes/client/util/KubeConfig.java
  util/src/test/java/io/kubernetes/client/util/KubeConfigTest.java
Labels: approved, cncf-cla: yes, lgtm, size/L

#526 add new extended module
  extended/pom.xml
  pom.xml
Labels: approved, cncf-cla: yes, lgtm, size/L

#527 Adding pagination utility
  examples/src/main/java/io/kubernetes/client/examples/PagerExample.java
  util/src/main/java/io/kubernetes/client/pager/Pager.java
  util/src/main/java/io/kubernetes/client/pager/PagerParams.java
  util/src/test/java/io/kubernetes/client/pager/PagerTest.java
  util/src/test/resources/bad-token-status.json
  util/src/test/resources/namespace-list-status.json
  util/src/test/resources/namespace-list.json
  util/src/test/resources/status-400.json
Labels: approved, cncf-cla: yes, lgtm, size/L
