Repository kubernetes-client/java, pull requests merged in 2019-02, with the labels that each got.

#497 Mark com.microsoft.azure.adal4j optional
  util/pom.xml
Labels: approved, cncf-cla: yes, lgtm, size/S

#500 Fix DateTime string generation.
  util/src/main/java/io/kubernetes/client/util/Yaml.java
  util/src/test/java/io/kubernetes/client/util/YamlTest.java
  util/src/test/resources/test-pod.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#499 Improve script a little bit.
  examples/createPod.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#504 Update Dockerfile
  examples/Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#501 Updated OWNERS to include link to docs
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#505 Release 4.0.0
  examples/pom.xml
  kubernetes/pom.xml
  pom.xml
  proto/pom.xml
  util/pom.xml
Labels: approved, cncf-cla: yes, lgtm, size/S
