Repository kubernetes-client/java, pull requests merged in 2019-10, with the labels that each got.

#718 Implement copyFileToPod
  util/src/main/java/io/kubernetes/client/Copy.java
  util/src/test/java/io/kubernetes/client/CopyTest.java
Labels: approved, cncf-cla: yes, lgtm, size/M

#723 Set config file when using home directory
  util/src/main/java/io/kubernetes/client/util/ClientBuilder.java
  util/src/test/java/io/kubernetes/client/util/ClientBuilderTest.java
Labels: approved, cncf-cla: yes, lgtm, size/S

#712 "renewDeadline" support for leader election
  examples/src/main/java/io/kubernetes/client/examples/ControllerExample.java
  examples/src/main/java/io/kubernetes/client/examples/LeaderElectionExample.java
  extended/src/main/java/io/kubernetes/client/extended/leaderelection/LeaderElector.java
  extended/src/test/java/io/kubernetes/client/extended/controller/LeaderElectingControllerTest.java
  extended/src/test/java/io/kubernetes/client/extended/leaderelection/LeaderElectionTest.java
Labels: approved, cncf-cla: yes, lgtm, size/L

#724 EntrySet usage instread of get(prefix)
  util/src/main/java/io/kubernetes/client/util/Yaml.java
Labels: approved, cncf-cla: yes, lgtm, size/XS

#727 Magic exception message update + FileInputStream closing in SSLUtils
  util/src/main/java/io/kubernetes/client/ProtoClient.java
  util/src/main/java/io/kubernetes/client/util/SSLUtils.java
Labels: approved, cncf-cla: yes, lgtm, size/XS

#729 Upgrade Apache Compress 1.19
  util/pom.xml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#730 Refactor: Replace manual mocks with mockito helpers
  extended/src/test/java/io/kubernetes/client/extended/controller/DefaultControllerTest.java
  extended/src/test/java/io/kubernetes/client/extended/controller/LeaderElectingControllerTest.java
Labels: approved, cncf-cla: yes, lgtm, size/L

#731 Bugfix(informer): DeltaFIFO Replace method to prevent SharedIndexInformers from missing notifications
  util/src/main/java/io/kubernetes/client/informer/cache/DeltaFIFO.java
  util/src/test/java/io/kubernetes/client/informer/cache/DeltaFIFOTest.java
Labels: approved, cncf-cla: yes, lgtm, size/M

#733 Replace getDeclaredMethod vs getMethod to access parent class
  util/src/main/java/io/kubernetes/client/util/Reflect.java
Labels: approved, cncf-cla: yes, lgtm, size/XS

#745 Chore: Fix build flakiness
  extended/src/test/java/io/kubernetes/client/extended/controller/LeaderElectingControllerTest.java
  util/src/test/java/io/kubernetes/client/CopyTest.java
Labels: approved, cncf-cla: yes, lgtm, size/S

#732 Collections.java replace by apache.commons.collections4
  extended/pom.xml
  util/src/main/java/io/kubernetes/client/informer/SharedInformerFactory.java
  util/src/main/java/io/kubernetes/client/informer/cache/Cache.java
  util/src/main/java/io/kubernetes/client/informer/cache/DeltaFIFO.java
  util/src/main/java/io/kubernetes/client/informer/cache/SharedProcessor.java
  util/src/main/java/io/kubernetes/client/informer/impl/DefaultSharedIndexInformer.java
  util/src/main/java/io/kubernetes/client/util/common/Collections.java
Labels: approved, cncf-cla: yes, lgtm, size/M

#739 Adding UTF-8 support with config readers for kubeconfig files
  util/src/main/java/io/kubernetes/client/util/ClientBuilder.java
  util/src/test/java/io/kubernetes/client/util/ClientBuilderTest.java
  util/src/test/resources/kubeconfig-utf8
Labels: approved, cncf-cla: yes, lgtm, size/M

#746 Refactor: removing duplicate code snippet
  util/src/main/java/io/kubernetes/client/util/ClientBuilder.java
Labels: approved, cncf-cla: yes, lgtm, size/M

#750 Added example for create StatefulSet from file
  README.md
  examples/src/main/java/io/kubernetes/client/examples/YamlExample.java
  examples/test-svc.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#751 Ignore the flaking CopyTest w/ TODO comment left
  util/src/test/java/io/kubernetes/client/CopyTest.java
Labels: approved, cncf-cla: yes, lgtm, size/XS

#752 UTF-8 support for config class
  util/src/main/java/io/kubernetes/client/util/Config.java
Labels: approved, cncf-cla: yes, lgtm, size/S

#762 Dedicated OSGi bundle merging both `client-java` and `client-java-api`
  client-java-osgi/bnd.bnd
  client-java-osgi/pom.xml
  pom.xml
Labels: approved, cncf-cla: yes, lgtm, size/M

#754 Using GzipCompressorInputStream for decompressing .gz files.
  util/src/main/java/io/kubernetes/client/Copy.java
Labels: approved, cncf-cla: yes, lgtm, size/XS
