Repository kubernetes-client/java, pull requests merged in 2019-12, with the labels that each got.

#819 Minor cleanup in SharedInformerFactory
  util/src/main/java/io/kubernetes/client/informer/SharedInformerFactory.java
Labels: approved, cncf-cla: yes, lgtm, size/S

#798 Bump 7.0.0 release
  CHANGELOG.md
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#827 Introduce oneline patch util for overriding patch format from generated client
  util/src/main/java/io/kubernetes/client/util/PatchUtils.java
  util/src/test/java/io/kubernetes/client/util/PatchUtilsTest.java
Labels: approved, cncf-cla: yes, lgtm, size/L

#794 Uncommenting the test and changing wireMockRule to be used in instanc…
  util/src/test/java/io/kubernetes/client/CopyTest.java
Labels: approved, cncf-cla: yes, lgtm, size/M

#830 Update patch example to reflect usage of PatchUtil
  examples/src/main/java/io/kubernetes/client/examples/PatchExample.java
Labels: approved, cncf-cla: yes, lgtm, size/M

#833 V1PatchAdapter should be declared static
  kubernetes/src/main/java/io/kubernetes/client/custom/V1Patch.java
Labels: approved, cncf-cla: yes, lgtm, size/XS

#834 Implement DefaultSharedIndexInformer#addIndexers
  util/src/main/java/io/kubernetes/client/informer/cache/Cache.java
  util/src/main/java/io/kubernetes/client/informer/cache/Indexer.java
  util/src/main/java/io/kubernetes/client/informer/impl/DefaultSharedIndexInformer.java
  util/src/test/java/io/kubernetes/client/informer/cache/CacheTest.java
Labels: approved, cncf-cla: yes, lgtm, size/L
