Repository kubernetes-client/java, pull requests merged in 2019-07, with the labels that each got.

#590 leader election
  examples/src/main/java/io/kubernetes/client/examples/LeaderElectionExample.java
  extended/src/main/java/io/kubernetes/client/extended/leaderelection/LeaderElectionConfig.java
  extended/src/main/java/io/kubernetes/client/extended/leaderelection/LeaderElectionRecord.java
  extended/src/main/java/io/kubernetes/client/extended/leaderelection/LeaderElector.java
  extended/src/main/java/io/kubernetes/client/extended/leaderelection/Lock.java
  extended/src/main/java/io/kubernetes/client/extended/leaderelection/resourcelock/ConfigMapLock.java
  extended/src/main/java/io/kubernetes/client/extended/leaderelection/resourcelock/EndpointsLock.java
  extended/src/test/java/io/kubernetes/client/extended/leaderelection/LeaderElectionTest.java
  util/src/main/java/io/kubernetes/client/util/leaderelection/LeaderElectionConfig.java
  util/src/main/java/io/kubernetes/client/util/leaderelection/LeaderElectionRecord.java
  util/src/main/java/io/kubernetes/client/util/leaderelection/LeaderElector.java
  util/src/main/java/io/kubernetes/client/util/leaderelection/Lock.java
  util/src/main/java/io/kubernetes/client/util/leaderelection/resourcelock/ConfigMapLock.java
  util/src/main/java/io/kubernetes/client/util/leaderelection/resourcelock/EndpointsLock.java
  util/src/test/java/io/kubernetes/client/util/leaderelection/LeaderElectionTest.java
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#607 Improve the exec example.
  .travis.yml
  examples/pom.xml
  examples/src/main/java/io/kubernetes/client/examples/ExecExample.java
Labels: approved, cncf-cla: yes, lgtm, size/M

#614 Follow-up: Remove util leader election in the tree
  util/src/main/java/io/kubernetes/client/util/leaderelection/LeaderElectionConfig.java
  util/src/main/java/io/kubernetes/client/util/leaderelection/LeaderElectionRecord.java
  util/src/main/java/io/kubernetes/client/util/leaderelection/LeaderElector.java
  util/src/main/java/io/kubernetes/client/util/leaderelection/Lock.java
  util/src/main/java/io/kubernetes/client/util/leaderelection/resourcelock/ConfigMapLock.java
  util/src/main/java/io/kubernetes/client/util/leaderelection/resourcelock/EndpointsLock.java
  util/src/test/java/io/kubernetes/client/util/leaderelection/LeaderElectionTest.java
Labels: approved, cncf-cla: yes, lgtm, size/XL

#619 Chore: Remove duplicated patch format from ApiClient
  kubernetes/src/main/java/io/kubernetes/client/ApiClient.java
  util/src/test/java/io/kubernetes/client/util/ClientBuilderPatchTest.java
Labels: approved, cncf-cla: yes, lgtm, size/XS

#622 add v2beta2 apiversion for autoscaling/v2beta2/hpa
  util/src/main/java/io/kubernetes/client/util/Yaml.java
Labels: approved, cncf-cla: yes, lgtm, size/XS

#623 Chore: Add [in|out-of] cluster examples and enhance docs
  README.md
  examples/src/main/java/io/kubernetes/client/examples/InClusterClientExample.java
  examples/src/main/java/io/kubernetes/client/examples/KubeConfigFileClientExample.java
Labels: approved, cncf-cla: yes, lgtm, size/L

#525 add workqueue implementation for kube-style controller
  extended/src/main/java/io/kubernetes/client/extended/wait/Wait.java
  extended/src/main/java/io/kubernetes/client/extended/workqueue/DefaultDelayingQueue.java
  extended/src/main/java/io/kubernetes/client/extended/workqueue/DefaultRateLimitingQueue.java
  extended/src/main/java/io/kubernetes/client/extended/workqueue/DefaultWorkQueue.java
  extended/src/main/java/io/kubernetes/client/extended/workqueue/DelayingQueue.java
  extended/src/main/java/io/kubernetes/client/extended/workqueue/RateLimiter.java
  extended/src/main/java/io/kubernetes/client/extended/workqueue/RateLimitingQueue.java
  extended/src/main/java/io/kubernetes/client/extended/workqueue/WorkQueue.java
  extended/src/test/java/io/kubernetes/client/extended/workqueue/DefaultDelayingQueueTest.java
  extended/src/test/java/io/kubernetes/client/extended/workqueue/DefaultRateLimitQueueTest.java
  extended/src/test/java/io/kubernetes/client/extended/workqueue/DefaultWorkQueueTest.java
Labels: approved, cncf-cla: yes, lgtm, size/XL

#629 Chore: Fixes README stale versions
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#636 [Refactor] Add Call-generator interface throwing checked ApiException
  examples/src/main/java/io/kubernetes/client/examples/InformerExample.java
  util/pom.xml
  util/src/main/java/io/kubernetes/client/informer/SharedInformerFactory.java
  util/src/main/java/io/kubernetes/client/util/CallGenerator.java
  util/src/test/java/io/kubernetes/client/informer/SharedInformerFactoryTest.java
Labels: approved, cncf-cla: yes, lgtm, size/L

#645 Doc: Generate model from third-party-resources
  docs/generate-model-from-third-party-resources.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#635 Out-of-box controller runtime framework and builder library
  README.md
  examples/src/main/java/io/kubernetes/client/examples/ControllerExample.java
  extended/src/main/java/io/kubernetes/client/extended/controller/Controller.java
  extended/src/main/java/io/kubernetes/client/extended/controller/ControllerManager.java
  extended/src/main/java/io/kubernetes/client/extended/controller/Controllers.java
  extended/src/main/java/io/kubernetes/client/extended/controller/DefaultController.java
  extended/src/main/java/io/kubernetes/client/extended/controller/LeaderElectingController.java
  extended/src/main/java/io/kubernetes/client/extended/controller/WorkQueueResourceEventHandler.java
  extended/src/main/java/io/kubernetes/client/extended/controller/builder/Constants.java
  extended/src/main/java/io/kubernetes/client/extended/controller/builder/ControllerBuilder.java
  extended/src/main/java/io/kubernetes/client/extended/controller/builder/ControllerManangerBuilder.java
  extended/src/main/java/io/kubernetes/client/extended/controller/builder/DefaultControllerBuilder.java
  extended/src/main/java/io/kubernetes/client/extended/controller/reconciler/Reconciler.java
  extended/src/main/java/io/kubernetes/client/extended/controller/reconciler/Request.java
  extended/src/main/java/io/kubernetes/client/extended/controller/reconciler/Result.java
  extended/src/test/java/io/kubernetes/client/extended/controller/ControllerManagerTest.java
  extended/src/test/java/io/kubernetes/client/extended/controller/DefaultControllerTest.java
  extended/src/test/java/io/kubernetes/client/extended/controller/LeaderElectingControllerTest.java
  extended/src/test/java/io/kubernetes/client/extended/controller/WorkQueueResourceEventHandlerTest.java
  extended/src/test/java/io/kubernetes/client/extended/controller/builder/DefaultControllerBuilderTest.java
Labels: approved, cncf-cla: yes, lgtm, size/XXL
