Repository kubernetes-client/java, pull requests merged in 2019-08, with the labels that each got.

#647 Release/flush websocket buffers on abnormal closing
  util/src/main/java/io/kubernetes/client/util/WebSocketStreamHandler.java
  util/src/test/java/io/kubernetes/client/WebsocketStreamHandlerTest.java
Labels: approved, cncf-cla: yes, lgtm, size/M

#624 Add workqueue support
  extended/pom.xml
  extended/src/main/java/io/kubernetes/client/extended/workqueue/DefaultRateLimitingQueue.java
  extended/src/main/java/io/kubernetes/client/extended/workqueue/RateLimiter.java
  extended/src/main/java/io/kubernetes/client/extended/workqueue/ratelimiter/BucketRateLimiter.java
  extended/src/main/java/io/kubernetes/client/extended/workqueue/ratelimiter/DefaultControllerRateLimiter.java
  extended/src/main/java/io/kubernetes/client/extended/workqueue/ratelimiter/ItemExponentialFailureRateLimiter.java
  extended/src/main/java/io/kubernetes/client/extended/workqueue/ratelimiter/ItemFastSlowRateLimiter.java
  extended/src/main/java/io/kubernetes/client/extended/workqueue/ratelimiter/MaxOfRateLimiter.java
  extended/src/main/java/io/kubernetes/client/extended/workqueue/ratelimiter/RateLimiter.java
  extended/src/test/java/io/kubernetes/client/extended/workqueue/DefaultRateLimitQueueTest.java
  extended/src/test/java/io/kubernetes/client/extended/workqueue/ratelimiter/BucketRateLimiterTest.java
  extended/src/test/java/io/kubernetes/client/extended/workqueue/ratelimiter/ItemExponentialFailureRateLimiterTest.java
  extended/src/test/java/io/kubernetes/client/extended/workqueue/ratelimiter/ItemFastSlowRateLimiterTest.java
  extended/src/test/java/io/kubernetes/client/extended/workqueue/ratelimiter/MaxOfRateLimiterTest.java
Labels: approved, cncf-cla: yes, lgtm, size/XL

#648 Docs: Note examples' supported release version
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#618 serverside apply & example
  examples/src/main/java/io/kubernetes/client/examples/PatchExample.java
  kubernetes/src/main/java/io/kubernetes/client/custom/V1Patch.java
Labels: approved, cncf-cla: yes, lgtm, size/S

#649 Refactor: Add constructor for customizing index funcs
  util/src/main/java/io/kubernetes/client/informer/SharedInformerFactory.java
  util/src/main/java/io/kubernetes/client/informer/cache/Cache.java
  util/src/main/java/io/kubernetes/client/informer/cache/Caches.java
  util/src/main/java/io/kubernetes/client/informer/cache/Lister.java
  util/src/main/java/io/kubernetes/client/informer/impl/DefaultSharedIndexInformer.java
  util/src/test/java/io/kubernetes/client/informer/cache/CacheTest.java
  util/src/test/java/io/kubernetes/client/informer/cache/CachesTest.java
Labels: approved, cncf-cla: yes, lgtm, size/L

#659 show exception message when failing to acquire or renew election lock
  examples/src/main/java/io/kubernetes/client/examples/LeaderElectionExample.java
  extended/src/main/java/io/kubernetes/client/extended/leaderelection/LeaderElector.java
  extended/src/main/java/io/kubernetes/client/extended/leaderelection/resourcelock/ConfigMapLock.java
  extended/src/main/java/io/kubernetes/client/extended/leaderelection/resourcelock/EndpointsLock.java
Labels: approved, cncf-cla: yes, lgtm, size/XS

#651 Refactor: Follow-up of controller-builder utils
  examples/src/main/java/io/kubernetes/client/examples/ControllerExample.java
  extended/src/main/java/io/kubernetes/client/extended/controller/ControllerManager.java
  extended/src/main/java/io/kubernetes/client/extended/controller/ControllerWatch.java
  extended/src/main/java/io/kubernetes/client/extended/controller/DefaultControllerWatch.java
  extended/src/main/java/io/kubernetes/client/extended/controller/builder/ControllerBuilder.java
  extended/src/main/java/io/kubernetes/client/extended/controller/builder/ControllerManagerBuilder.java
  extended/src/main/java/io/kubernetes/client/extended/controller/builder/ControllerWatchBuilder.java
  extended/src/main/java/io/kubernetes/client/extended/controller/builder/DefaultControllerBuilder.java
  extended/src/main/java/io/kubernetes/client/extended/workqueue/DefaultRateLimitingQueue.java
  extended/src/test/java/io/kubernetes/client/extended/controller/ControllerManagerTest.java
  extended/src/test/java/io/kubernetes/client/extended/controller/ControllerWatchTest.java
  extended/src/test/java/io/kubernetes/client/extended/controller/WorkQueueResourceEventHandlerTest.java
  extended/src/test/java/io/kubernetes/client/extended/controller/builder/DefaultControllerBuilderTest.java
  util/src/main/java/io/kubernetes/client/informer/SharedInformerFactory.java
Labels: approved, cncf-cla: yes, lgtm, size/XL

#661 Fixes leaking informer#controller daemon thread
  util/src/main/java/io/kubernetes/client/informer/cache/Controller.java
  util/src/main/java/io/kubernetes/client/informer/impl/DefaultSharedIndexInformer.java
Labels: approved, cncf-cla: yes, lgtm, size/XS

#665 Fix: should not return from DefaultController.worker() method when re…
  extended/src/main/java/io/kubernetes/client/extended/controller/DefaultController.java
Labels: approved, cncf-cla: yes, lgtm, size/S

#662 manually set OKHttpClient read timeout zero ensure client doesnot tim…
  util/src/main/java/io/kubernetes/client/informer/SharedInformerFactory.java
Labels: approved, cncf-cla: yes, lgtm, size/S

#666 Fixes unexpectedly listener quitting leads to OOM
  util/src/main/java/io/kubernetes/client/informer/cache/ProcessorListener.java
Labels: approved, cncf-cla: yes, lgtm, size/M

#669 Fix: remove the capacity limit of ProcessorListener
  util/src/main/java/io/kubernetes/client/informer/cache/ProcessorListener.java
  util/src/test/java/io/kubernetes/client/informer/cache/ProcessorListenerTest.java
Labels: approved, cncf-cla: yes, lgtm, size/M

#672 Revise README for 6.0.0 release
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#677 676 - fix for EC cert loading exception
  util/src/main/java/io/kubernetes/client/util/SSLUtils.java
Labels: approved, cncf-cla: yes, lgtm, size/S

#678 maven-compiler-plugin 3.8.1
  pom.xml
Labels: approved, cncf-cla: yes, lgtm, size/XS
