Repository kubernetes-client/java, pull requests merged in 2020-05, with the labels that each got.

#933 Approach 2 - Fix for non closure of input stream for Copy utility
  util/src/main/java/io/kubernetes/client/Exec.java
  util/src/test/java/io/kubernetes/client/ExecTest.java
Labels: approved, cncf-cla: yes, lgtm, size/S

#905 Create job from cron job
  util/src/main/java/io/kubernetes/client/util/conversion/Jobs.java
Labels: approved, cncf-cla: yes, lgtm, size/M

#936 Fixes generic kubernetes api patches
  extended/src/main/java/io/kubernetes/client/extended/generic/GenericKubernetesApi.java
Labels: approved, cncf-cla: yes, lgtm, size/XS

#953 Fixes event-recorder event-source setting
  extended/src/main/java/io/kubernetes/client/extended/event/legacy/LegacyEventBroadcaster.java
  extended/src/main/java/io/kubernetes/client/extended/event/legacy/ObjectReferenceResolvingEventRecorder.java
Labels: approved, cncf-cla: yes, lgtm, size/S

#954 Release 8.0.2
  examples/pom.xml
  extended/pom.xml
  kubernetes/pom.xml
  pom.xml
  proto/pom.xml
  spring/pom.xml
  util/pom.xml
Labels: approved, cncf-cla: yes, lgtm, size/S

#955 Refresh README for latest release 8.0.2
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#956 Bring spring integration pom inline with other poms.
  spring/pom.xml
Labels: approved, cncf-cla: yes, lgtm, size/S

#957 Move to version 9.0.0 for 1.17 Kubernetes API.
  examples/pom.xml
  extended/pom.xml
  kubernetes/pom.xml
  pom.xml
  proto/pom.xml
  spring/pom.xml
  util/pom.xml
Labels: approved, cncf-cla: yes, lgtm, size/S

#962 Catches runtime-exception upon executing reconciler
  extended/src/main/java/io/kubernetes/client/extended/controller/DefaultController.java
  extended/src/test/java/io/kubernetes/client/extended/controller/DefaultControllerTest.java
Labels: approved, cncf-cla: yes, lgtm, size/S

#963 Supporting "BOOKMARK" watch event-type
  util/src/main/java/io/kubernetes/client/informer/EventType.java
  util/src/main/java/io/kubernetes/client/informer/cache/ReflectorRunnable.java
Labels: approved, cncf-cla: yes, lgtm, size/XS
