Repository kubernetes-client/java, pull requests merged in 2020-03, with the labels that each got.

#844 Event recorder equivalence for controller
  examples/src/main/java/io/kubernetes/client/examples/ControllerExample.java
  extended/src/main/java/io/kubernetes/client/extended/event/EventType.java
  extended/src/main/java/io/kubernetes/client/extended/event/legacy/EventAggregator.java
  extended/src/main/java/io/kubernetes/client/extended/event/legacy/EventBroadcaster.java
  extended/src/main/java/io/kubernetes/client/extended/event/legacy/EventCorrelator.java
  extended/src/main/java/io/kubernetes/client/extended/event/legacy/EventLogger.java
  extended/src/main/java/io/kubernetes/client/extended/event/legacy/EventRecorder.java
  extended/src/main/java/io/kubernetes/client/extended/event/legacy/EventSink.java
  extended/src/main/java/io/kubernetes/client/extended/event/legacy/EventSpamFilter.java
  extended/src/main/java/io/kubernetes/client/extended/event/legacy/EventUtils.java
  extended/src/main/java/io/kubernetes/client/extended/event/legacy/LegacyEventBroadcaster.java
  extended/src/main/java/io/kubernetes/client/extended/event/legacy/ObjectReferenceResolvingEventRecorder.java
  extended/src/main/java/io/kubernetes/client/extended/event/v1beta1/EventSink.java
  extended/src/test/java/io/kubernetes/client/extended/event/EventAggregatorTest.java
  extended/src/test/java/io/kubernetes/client/extended/event/EventCorrelatorTest.java
  extended/src/test/java/io/kubernetes/client/extended/event/EventLoggerTest.java
  extended/src/test/java/io/kubernetes/client/extended/event/EventSpamFilterTest.java
  util/src/main/java/io/kubernetes/client/util/TypeAccessor.java
  util/src/main/java/io/kubernetes/client/util/exception/TypeMetaReflectException.java
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#873 make background threads in LeaderElector to be daemon
  extended/src/main/java/io/kubernetes/client/extended/leaderelection/LeaderElector.java
Labels: approved, cncf-cla: yes, lgtm, size/S

#877 Unchain core/v1 resources for generic kubernetes client
  extended/src/main/java/io/kubernetes/client/extended/generic/GenericKubernetesApi.java
  extended/src/test/java/io/kubernetes/client/extended/generic/GenericKubernetesApiForCoreApiTest.java
Labels: approved, cncf-cla: yes, lgtm, size/L

#879 Wipe out unexpected occurrence of my aliases
  extended/src/test/java/io/kubernetes/client/extended/generic/GenericKubernetesGetApiTest.java
  util/src/main/java/io/kubernetes/client/util/Watchable.java
Labels: approved, cncf-cla: yes, lgtm, size/XS

#878 Spring integration: IoC injection for kubernetes informer/reconciler
  extended/src/main/java/io/kubernetes/client/extended/generic/GenericKubernetesApi.java
  extended/src/test/java/io/kubernetes/client/extended/generic/GenericKubernetesApiForCoreApiTest.java
  extended/src/test/java/io/kubernetes/client/extended/generic/GenericKubernetesApiTest.java
  pom.xml
  spring/pom.xml
  spring/src/main/java/io/kubernetes/client/spring/extended/controller/KubernetesInformerFactoryProcessor.java
  spring/src/main/java/io/kubernetes/client/spring/extended/controller/KubernetesReconcilerProcessor.java
  spring/src/main/java/io/kubernetes/client/spring/extended/controller/annotation/GroupVersionResource.java
  spring/src/main/java/io/kubernetes/client/spring/extended/controller/annotation/KubernetesInformer.java
  spring/src/main/java/io/kubernetes/client/spring/extended/controller/annotation/KubernetesInformers.java
  spring/src/main/java/io/kubernetes/client/spring/extended/controller/annotation/KubernetesReconciler.java
  spring/src/main/java/io/kubernetes/client/spring/extended/controller/annotation/KubernetesReconcilerReadyFuncs.java
  spring/src/main/java/io/kubernetes/client/spring/extended/controller/annotation/KubernetesReconcilerWatch.java
  spring/src/main/java/io/kubernetes/client/spring/extended/controller/annotation/KubernetesReconcilerWatches.java
  spring/src/main/java/io/kubernetes/client/spring/extended/controller/annotation/KubernetesReconcilerWorkerCount.java
  spring/src/test/java/io/kubernetes/client/spring/extended/controller/KubernetesInformerCreatorTest.java
  spring/src/test/java/io/kubernetes/client/spring/extended/controller/KubernetesReconcilerCreatorTest.java
  spring/src/test/java/io/kubernetes/client/spring/extended/controller/TestApplication.java
  spring/src/test/resources/spring/test-context.xml
Labels: approved, cncf-cla: yes, lgtm, size/XL

#884 Resetting wiremock rule to resolve flakiness
  spring/src/test/java/io/kubernetes/client/spring/extended/controller/KubernetesInformerCreatorTest.java
Labels: approved, cncf-cla: yes, lgtm, size/S

#882 Release 8.0
  examples/pom.xml
  extended/pom.xml
  kubernetes/pom.xml
  pom.xml
  proto/pom.xml
  spring/pom.xml
  util/pom.xml
Labels: approved, cncf-cla: yes, lgtm, size/S

#888 Update bouncy castle dependency to 1.64
  util/pom.xml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#890 Spring integration follow up
  extended/src/main/java/io/kubernetes/client/extended/controller/ControllerWatch.java
  extended/src/main/java/io/kubernetes/client/extended/controller/DefaultControllerWatch.java
  extended/src/main/java/io/kubernetes/client/extended/controller/builder/ControllerWatchBuilder.java
  extended/src/main/java/io/kubernetes/client/extended/controller/builder/DefaultControllerBuilder.java
  extended/src/test/java/io/kubernetes/client/extended/controller/ControllerWatchTest.java
  spring/src/main/java/io/kubernetes/client/spring/extended/controller/KubernetesReconcilerProcessor.java
  spring/src/main/java/io/kubernetes/client/spring/extended/controller/annotation/AddWatchEventFilter.java
  spring/src/main/java/io/kubernetes/client/spring/extended/controller/annotation/DeleteWatchEventFilter.java
  spring/src/main/java/io/kubernetes/client/spring/extended/controller/annotation/KubernetesReconcilerReadyFunc.java
  spring/src/main/java/io/kubernetes/client/spring/extended/controller/annotation/KubernetesReconcilerReadyFuncs.java
  spring/src/main/java/io/kubernetes/client/spring/extended/controller/annotation/KubernetesReconcilerWatch.java
  spring/src/main/java/io/kubernetes/client/spring/extended/controller/annotation/UpdateWatchEventFilter.java
  spring/src/test/java/io/kubernetes/client/spring/extended/controller/KubernetesReconcilerCreatorTest.java
Labels: approved, cncf-cla: yes, lgtm, size/L

#897 Fixes work-queue injection for spring integration
  spring/src/main/java/io/kubernetes/client/spring/extended/controller/KubernetesReconcilerProcessor.java
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#898 Adding example for spring-based controller construction
  README.md
  examples/pom.xml
  examples/src/main/java/io/kubernetes/client/examples/SpringControllerExample.java
  spring/pom.xml
  spring/src/main/java/io/kubernetes/client/spring/extended/controller/KubernetesInformerFactoryProcessor.java
Labels: approved, cncf-cla: yes, lgtm, size/L

#902 Generic kubernetes api example
  examples/src/main/java/io/kubernetes/client/examples/GenericClientExample.java
  extended/src/main/java/io/kubernetes/client/extended/generic/GenericKubernetesApi.java
Labels: approved, cncf-cla: yes, lgtm, size/M
