Repository kubernetes-client/java, pull requests merged in 2020-10, with the labels that each got.

#1314 Fix pager iterator and add test.
  extended/src/main/java/io/kubernetes/client/extended/pager/Pager.java
  extended/src/test/java/io/kubernetes/client/extended/pager/PagerTest.java
  extended/src/test/resources/namespace-list-pager0.json
Labels: approved, cncf-cla: yes, lgtm, size/M

#1315 Buffer writes > 16 MiB into multiple web socket messages.
  util/src/main/java/io/kubernetes/client/util/WebSocketStreamHandler.java
  util/src/test/java/io/kubernetes/client/WebsocketStreamHandlerTest.java
Labels: approved, cncf-cla: yes, lgtm, size/L

#1316 Add a helper method to obtain the namespace of a pod.
  util/src/main/java/io/kubernetes/client/util/Config.java
  util/src/main/java/io/kubernetes/client/util/Namespaces.java
Labels: approved, cncf-cla: yes, lgtm, size/S

#1321 Add a flush method to the websocket output stream.
  util/src/main/java/io/kubernetes/client/util/WebSocketStreamHandler.java
Labels: approved, cncf-cla: yes, lgtm, size/S

#1331 Bugfix: Suppress runtime exception upon non-status error responses
  util/src/main/java/io/kubernetes/client/util/generic/GenericKubernetesApi.java
  util/src/test/java/io/kubernetes/client/util/generic/KubernetesApiResponseTest.java
Labels: approved, cncf-cla: yes, lgtm, size/S

#1330 Provide base images for saving installation time
  client-java-contrib/Dockerfile
  client-java-contrib/Dockerfile.gen
  client-java-contrib/Dockerfile.gen-base
  client-java-contrib/cert-manager/update.sh
  client-java-contrib/prometheus-operator/update.sh
  client-java-contrib/publish-gen-image.sh
  docs/generate-model-from-third-party-resources.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#1332 fix reflector graceful shutdown by closing underlying watch
  util/src/main/java/io/kubernetes/client/informer/cache/ReflectorRunnable.java
Labels: approved, cncf-cla: yes, lgtm, size/M

#1320 Add async methods for Copy that return Futures.
  util/src/main/java/io/kubernetes/client/Copy.java
Labels: approved, cncf-cla: yes, lgtm, size/M

#1343 Kubeconfig Example: Replaces shell sugar `~` with env var `$HOME`
  examples/src/main/java/io/kubernetes/client/examples/KubeConfigFileClientExample.java
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1344 reflector: fix watch timeout by using it as seconds unit
  util/src/main/java/io/kubernetes/client/informer/cache/ReflectorRunnable.java
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1345 Feat: Adding lease lock implementation
  extended/src/main/java/io/kubernetes/client/extended/leaderelection/resourcelock/LeaseLock.java
Labels: approved, cncf-cla: yes, lgtm, size/L

#1349 Doc: Tutorial for re-writing a kubernetes replicaset-controller in Java
  README.md
  docs/java-controller-tutorial-rewrite-rs-controller.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#1352 unable to use autowired in the reconciler
  examples/src/main/java/io/kubernetes/client/examples/SpringControllerExample.java
  examples/src/main/resources/application.properties
  spring/src/main/java/io/kubernetes/client/spring/extended/controller/KubernetesReconcilerProcessor.java
  spring/src/main/java/io/kubernetes/client/spring/extended/controller/factory/KubernetesControllerFactory.java
Labels: approved, cncf-cla: yes, lgtm, size/XL
