Repository kubernetes-client/java, pull requests merged in 2020-09, with the labels that each got.

#1208 Code clean up
  util/src/main/java/io/kubernetes/client/Attach.java
  util/src/main/java/io/kubernetes/client/util/ConfigPersister.java
  util/src/main/java/io/kubernetes/client/util/WebSocketStreamHandler.java
  util/src/main/java/io/kubernetes/client/util/WebSockets.java
  util/src/main/java/io/kubernetes/client/util/authenticators/Authenticator.java
  util/src/main/java/io/kubernetes/client/util/taints/Taints.java
Labels: approved, cncf-cla: yes, lgtm, size/S

#1212 Fixes maven compile stackoverflow
  pom.xml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1211 Add kubectl drain.
  examples/src/main/java/io/kubernetes/client/examples/KubectlExample.java
  extended/src/main/java/io/kubernetes/client/extended/kubectl/Kubectl.java
  extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlCordon.java
  extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlDrain.java
  extended/src/test/java/io/kubernetes/client/extended/kubectl/KubectlDrainTest.java
  extended/src/test/resources/pod-list.json
Labels: approved, cncf-cla: yes, lgtm, size/L

#1214 flush stream after WebSocket handleMessage
  util/src/main/java/io/kubernetes/client/util/WebSocketStreamHandler.java
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1210 Publishes and documents crd-model-gen images
  client-java-contrib/cert-manager/update.sh
  docs/generate-model-from-third-party-resources.md
  scripts/publish-crd-model-gen-image.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#1184 Amend Compatibility table to document n-2 version guarantees.
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#1219 Remove some sleeps in tests to deflake.
  extended/src/test/java/io/kubernetes/client/extended/leaderelection/LeaderElectionTest.java
Labels: approved, cncf-cla: yes, lgtm, size/M

#1220 Move mbohlool to emeritus status.
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1224 CodeGen doc follow-up
  docs/generate-model-from-third-party-resources.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#1222 Remove a sleep from CopyTest to deflake it.
  util/src/test/java/io/kubernetes/client/CopyTest.java
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1228 Change wiremock to use dynamic ports.
  util/src/test/java/io/kubernetes/client/CopyTest.java
Labels: approved, cncf-cla: yes, lgtm, size/M

#1225 Refactor model mapper: adding group-version-resource mapping
  e2e/src/test/groovy/io/kubernetes/client/e2e/util/ModelMapperTest.groovy
  util/src/main/java/io/kubernetes/client/apimachinery/GroupVersion.java
  util/src/main/java/io/kubernetes/client/apimachinery/GroupVersionKind.java
  util/src/main/java/io/kubernetes/client/apimachinery/GroupVersionResource.java
  util/src/main/java/io/kubernetes/client/util/ModelMapper.java
  util/src/main/java/io/kubernetes/client/util/Yaml.java
  util/src/test/java/io/kubernetes/client/util/ModelMapperTest.java
Labels: approved, cncf-cla: yes, lgtm, size/L

#1231 junit 4.13
  pom.xml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1233 Change a bunch of tests to use dynamic ports for wire mocks.
  util/src/test/java/io/kubernetes/client/AttachTest.java
  util/src/test/java/io/kubernetes/client/DiscoveryTest.java
  util/src/test/java/io/kubernetes/client/ExecTest.java
  util/src/test/java/io/kubernetes/client/PodLogsTest.java
  util/src/test/java/io/kubernetes/client/PortForwardTest.java
Labels: approved, cncf-cla: yes, lgtm, size/M

#1226 Improve logging in leader election
  extended/src/main/java/io/kubernetes/client/extended/leaderelection/LeaderElector.java
  extended/src/main/java/io/kubernetes/client/extended/leaderelection/resourcelock/ConfigMapLock.java
  extended/src/main/java/io/kubernetes/client/extended/leaderelection/resourcelock/EndpointsLock.java
Labels: approved, cncf-cla: yes, lgtm, size/M

#1238 Removing static port in Junit tests
  util/src/test/java/io/kubernetes/client/informer/impl/DefaultSharedIndexInformerTest.java
  util/src/test/java/io/kubernetes/client/util/PatchUtilsTest.java
  util/src/test/java/io/kubernetes/client/util/credentials/TokenFileAuthenticationTest.java
  util/src/test/java/io/kubernetes/client/util/version/VersionTest.java
Labels: approved, cncf-cla: yes, lgtm, size/S

#1239 Fixes failing test: Sleep 2s before verfication
  util/src/test/java/io/kubernetes/client/CopyTest.java
Labels: approved, cncf-cla: yes, lgtm, size/S

#1241 Fixes crd validation precheck: ensure `.spec.preserveUnknownFields` set to false to enable pruning
  client-java-contrib/cert-manager/update.sh
  client-java-contrib/generate.sh
  client-java-contrib/prometheus-operator/update.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#1235 Enhancing model-mapper: adding bi-directional caches
  e2e/src/test/groovy/io/kubernetes/client/e2e/util/ModelMapperTest.groovy
  util/src/main/java/io/kubernetes/client/util/ModelMapper.java
  util/src/test/java/io/kubernetes/client/util/ModelMapperTest.java
Labels: approved, cncf-cla: yes, lgtm, size/L

#1242 Move away from static wire mocks.
  util/src/test/java/io/kubernetes/client/AttachTest.java
  util/src/test/java/io/kubernetes/client/DiscoveryTest.java
  util/src/test/java/io/kubernetes/client/ExecTest.java
  util/src/test/java/io/kubernetes/client/PodLogsTest.java
  util/src/test/java/io/kubernetes/client/PortForwardTest.java
Labels: approved, cncf-cla: yes, lgtm, size/M

#1243 Switch to a striped lock for better concurrency.
  util/src/main/java/io/kubernetes/client/util/ModelMapper.java
Labels: approved, cncf-cla: yes, lgtm, size/M

#1244 Refactor(kubectl): Automatic GVR discovery
  extended/src/main/java/io/kubernetes/client/extended/kubectl/Kubectl.java
  extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlAnnotate.java
  extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlApply.java
  extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlCordon.java
  extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlCreate.java
  extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlDrain.java
  extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlLabel.java
  extended/src/test/java/io/kubernetes/client/extended/kubectl/KubectlAnnotateTest.java
  extended/src/test/java/io/kubernetes/client/extended/kubectl/KubectlDrainTest.java
  extended/src/test/java/io/kubernetes/client/extended/kubectl/KubectlLabelTest.java
  util/src/main/java/io/kubernetes/client/util/generic/KubernetesApiResponse.java
  util/src/test/java/io/kubernetes/client/util/generic/KubernetesApiResponseTest.java
Labels: approved, cncf-cla: yes, lgtm, size/XL

#1250 Doc: Bump codegen image version to v1.0.1
  docs/generate-model-from-third-party-resources.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1252 Refactor: Generic kubernetes api failure flow
  examples/src/main/java/io/kubernetes/client/examples/GenericClientExample.java
  util/src/main/java/io/kubernetes/client/informer/SharedInformerFactory.java
Labels: approved, cncf-cla: yes, lgtm, size/S

#1256 Add kubectl replace.
  examples/src/main/java/io/kubernetes/client/examples/KubectlExample.java
  extended/src/main/java/io/kubernetes/client/extended/kubectl/Kubectl.java
  extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlReplace.java
Labels: approved, cncf-cla: yes, lgtm, size/M

#1255 Add kubectl delete.
  examples/src/main/java/io/kubernetes/client/examples/KubectlExample.java
  extended/src/main/java/io/kubernetes/client/extended/kubectl/Kubectl.java
  extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlDelete.java
Labels: approved, cncf-cla: yes, lgtm, size/M

#1182 Add support for Kubectl patch
  extended/src/main/java/io/kubernetes/client/extended/kubectl/Kubectl.java
  extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlPatch.java
Labels: approved, cncf-cla: yes, lgtm, size/M

#1237 fix JUnit version property usage
  kubernetes/.openapi-generator-ignore
  kubernetes/pom.xml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1251 Feat: Kubectl get implementation
  e2e/src/test/groovy/io/kubernetes/client/e2e/kubectl/KubectlApplyTest.groovy
  e2e/src/test/groovy/io/kubernetes/client/e2e/kubectl/KubectlCreateTest.groovy
  extended/src/main/java/io/kubernetes/client/extended/kubectl/Kubectl.java
  extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlGet.java
  extended/src/test/java/io/kubernetes/client/extended/kubectl/KubectlGetTest.java
Labels: approved, cncf-cla: yes, lgtm, size/L

#1259 fix issue 912: do dedupe with resourceVersion
  util/src/main/java/io/kubernetes/client/informer/SharedInformerFactory.java
  util/src/main/java/io/kubernetes/client/informer/cache/DeltaFIFO.java
  util/src/test/java/io/kubernetes/client/informer/cache/DeltaFIFOTest.java
Labels: approved, cncf-cla: yes, lgtm, size/M

#1265 Refactor(kubectl): Homogenize kubectl resource manipulating sub-commands (kubectl create/apply)
  e2e/src/test/groovy/io/kubernetes/client/e2e/kubectl/KubectlApplyTest.groovy
  e2e/src/test/groovy/io/kubernetes/client/e2e/kubectl/KubectlCreateTest.groovy
  extended/src/main/java/io/kubernetes/client/extended/kubectl/Kubectl.java
  extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlApply.java
  extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlCreate.java
  extended/src/test/java/io/kubernetes/client/extended/kubectl/KubectlApplyTest.java
  extended/src/test/java/io/kubernetes/client/extended/kubectl/KubectlCreateTest.java
Labels: approved, cncf-cla: yes, lgtm, size/L

#1266 Refactor(generic-api): adding throwsApiExcetion method as recommended error handler
  docs/generate-model-from-third-party-resources.md
  examples/src/main/java/io/kubernetes/client/examples/GenericClientExample.java
  examples/src/main/java/io/kubernetes/client/examples/PromOpExample.java
  extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlAnnotate.java
  extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlApply.java
  extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlCordon.java
  extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlCreate.java
  extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlDelete.java
  extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlGet.java
  extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlLabel.java
  extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlReplace.java
  util/src/main/java/io/kubernetes/client/informer/SharedInformerFactory.java
  util/src/main/java/io/kubernetes/client/util/generic/KubernetesApiResponse.java
Labels: approved, cncf-cla: yes, lgtm, size/L

#1267 Codegen should abort upon hitting any error
  .github/workflows/maven.yml
  client-java-contrib/cert-manager/update.sh
  client-java-contrib/generate.sh
  client-java-contrib/prometheus-operator/update.sh
  docs/generate-model-from-third-party-resources.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#1272 Fixes failing codegen CI test
  .github/workflows/maven.yml
  client-java-contrib/cert-manager/update.sh
  client-java-contrib/prometheus-operator/update.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#1275 Release 10.0.0
  client-java-contrib/cert-manager/pom.xml
  client-java-contrib/prometheus-operator/pom.xml
  e2e/pom.xml
  examples/pom.xml
  extended/pom.xml
  kubernetes/pom.xml
  pom.xml
  proto/pom.xml
  spring/pom.xml
  util/pom.xml
Labels: approved, cncf-cla: yes, lgtm, size/M

#1276 Update docs for the 10.0.0 release.
  CHANGELOG.md
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#1283 Revert version and skip nexus deploy for contrib models
  client-java-contrib/cert-manager/pom.xml
  client-java-contrib/prometheus-operator/pom.xml
  examples/pom.xml
Labels: approved, cncf-cla: yes, lgtm, size/M

#1284 Provide a factory bean approach to configure the informer/reconcilers in spring context
  examples/src/main/java/io/kubernetes/client/examples/SpringControllerExample.java
  spring/src/main/java/io/kubernetes/client/spring/extended/controller/KubernetesInformerConfigurer.java
  spring/src/main/java/io/kubernetes/client/spring/extended/controller/KubernetesInformerFactoryProcessor.java
  spring/src/main/java/io/kubernetes/client/spring/extended/controller/KubernetesReconcilerConfigurer.java
  spring/src/main/java/io/kubernetes/client/spring/extended/controller/KubernetesReconcilerProcessor.java
  spring/src/test/java/io/kubernetes/client/spring/extended/controller/KubernetesInformerCreatorTest.java
  spring/src/test/java/io/kubernetes/client/spring/extended/controller/KubernetesReconcilerCreatorTest.java
  spring/src/test/java/io/kubernetes/client/spring/extended/controller/TestApplication.java
Labels: approved, cncf-cla: yes, lgtm, size/L

#1285 Bugfix(kubectl): Name argument is not required for kubectl replace
  e2e/src/test/groovy/io/kubernetes/client/e2e/kubectl/KubectlApplyTest.groovy
  e2e/src/test/groovy/io/kubernetes/client/e2e/kubectl/KubectlCreateTest.groovy
  e2e/src/test/groovy/io/kubernetes/client/e2e/kubectl/KubectlLabelTest.groovy
  e2e/src/test/groovy/io/kubernetes/client/e2e/kubectl/KubectlNamespaceTest.groovy
  extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlReplace.java
Labels: approved, cncf-cla: yes, lgtm, size/L

#1288 Revert spotless plugin to 2.1.0
  pom.xml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1293 Chore: Adding known-issue section to README
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#1295 Chore: Merges dependency declaration into root pom
  kubernetes/pom.xml
  pom.xml
Labels: approved, cncf-cla: yes, lgtm, size/L
