Repository kubernetes-client/java, pull requests merged in 2020-01, with the labels that each got.

#840 Bugfix: Fixes ipv6 host support
  util/src/main/java/io/kubernetes/client/util/ClientBuilder.java
  util/src/test/java/io/kubernetes/client/util/ClientBuilderTest.java
Labels: approved, cncf-cla: yes, lgtm, size/M

#843 Bugfix: Eliminate initial delay of ready check
  extended/src/main/java/io/kubernetes/client/extended/controller/DefaultController.java
  extended/src/main/java/io/kubernetes/client/extended/wait/Wait.java
Labels: approved, cncf-cla: yes, lgtm, size/S

#851 Rev the sundrio version to 0.21.0
  kubernetes/pom.xml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#738 Generic kubernetes api client
  extended/src/main/java/io/kubernetes/client/extended/generic/GenericKubernetesApi.java
  extended/src/main/java/io/kubernetes/client/extended/generic/KubernetesApiResponse.java
  extended/src/main/java/io/kubernetes/client/extended/generic/options/CreateOptions.java
  extended/src/main/java/io/kubernetes/client/extended/generic/options/DeleteOptions.java
  extended/src/main/java/io/kubernetes/client/extended/generic/options/GetOptions.java
  extended/src/main/java/io/kubernetes/client/extended/generic/options/ListOptions.java
  extended/src/main/java/io/kubernetes/client/extended/generic/options/PatchOptions.java
  extended/src/main/java/io/kubernetes/client/extended/generic/options/UpdateOptions.java
  extended/src/test/java/io/kubernetes/client/extended/generic/FooCustomResource.java
  extended/src/test/java/io/kubernetes/client/extended/generic/FooCustomResourceList.java
  extended/src/test/java/io/kubernetes/client/extended/generic/GenericKubernetesApiTest.java
  extended/src/test/java/io/kubernetes/client/extended/generic/GenericKubernetesGetApiTest.java
Labels: approved, cncf-cla: yes, lgtm, size/XXL
