Repository kubernetes-client/java, pull requests merged in 2020-02, with the labels that each got.

#848 Builder-modes for attach() and exec()
  util/src/main/java/io/kubernetes/client/Attach.java
  util/src/main/java/io/kubernetes/client/Exec.java
  util/src/test/java/io/kubernetes/client/AttachTest.java
  util/src/test/java/io/kubernetes/client/ExecTest.java
Labels: approved, cncf-cla: yes, lgtm, size/L

#858 Simplify usage of Bucket4j via using new API method consumeIgnoringRateLimits which was added in the version 4.8.0
  extended/pom.xml
  extended/src/main/java/io/kubernetes/client/extended/workqueue/ratelimiter/BucketRateLimiter.java
Labels: approved, cncf-cla: yes, lgtm, size/S

#863 Fix javadoc for picky javascript detector.
  util/src/main/java/io/kubernetes/client/PortForward.java
Labels: approved, cncf-cla: yes, lgtm, size/XS

#864 Release 8.0.0-alpha1
  util/src/main/java/io/kubernetes/client/PortForward.java
Labels: approved, cncf-cla: yes, lgtm, size/XS

#871 Add openid connect support
  util/pom.xml
  util/src/main/java/io/kubernetes/client/util/KubeConfig.java
  util/src/main/java/io/kubernetes/client/util/authenticators/OpenIDConnectAuthenticator.java
  util/src/test/java/io/kubernetes/client/util/TestUtils.java
  util/src/test/java/io/kubernetes/client/util/credentials/OpenIDConnectAuthenticationTest.java
  util/src/test/resources/oidc-server.jks
  util/src/test/resources/oidc-signing.p12
Labels: approved, cncf-cla: yes, lgtm, size/XL
