Repository kubernetes-client/java, pull requests merged in 2020-11, with the labels that each got.

#1354 Doc: Kubectl Equivalence in Java
  docs/kubectl-equivalence-in-java.md
  extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlPatch.java
Labels: approved, cncf-cla: yes, lgtm, size/L

#1356 Controller EventFilter&ReadyFunc should return false upon InvocationException
  spring/src/main/java/io/kubernetes/client/spring/extended/controller/factory/KubernetesControllerFactory.java
Labels: approved, cncf-cla: yes, lgtm, size/M

#1361 Chore: Removes spammy warning message from reconciler processor
  spring/src/main/java/io/kubernetes/client/spring/extended/controller/factory/KubernetesControllerFactory.java
Labels: approved, cncf-cla: yes, lgtm, size/S

#1360 Feat: Controller metrics
  examples/pom.xml
  examples/src/main/java/io/kubernetes/client/examples/SpringControllerExample.java
  examples/src/main/resources/application.properties
  extended/src/main/java/io/kubernetes/client/extended/controller/DefaultController.java
  extended/src/main/java/io/kubernetes/client/extended/controller/builder/DefaultControllerBuilder.java
  extended/src/test/java/io/kubernetes/client/extended/controller/DefaultControllerTest.java
  pom.xml
  spring/pom.xml
  spring/src/main/java/io/kubernetes/client/spring/extended/controller/metrics/PrometheusScrapeEndpoint.java
Labels: approved, cncf-cla: yes, lgtm, size/L

#1369 Fixes kubectl-drain failures and adding e2e tests
  e2e/src/test/groovy/io/kubernetes/client/e2e/informer/NamespaceInformerTest.groovy
  e2e/src/test/groovy/io/kubernetes/client/e2e/kubectl/KubectlDrainTest.groovy
  e2e/src/test/groovy/io/kubernetes/client/e2e/kubectl/KubectlNamespaceTest.groovy
  extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlCordon.java
  extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlDrain.java
  extended/src/test/java/io/kubernetes/client/extended/kubectl/KubectlDrainTest.java
Labels: approved, cncf-cla: yes, lgtm, size/L

#1363 Add some null checking.
  extended/src/main/java/io/kubernetes/client/extended/kubectl/Kubectl.java
  extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlPatch.java
Labels: approved, cncf-cla: yes, lgtm, size/S

#1368 Reflector relists with last synced resource version
  pom.xml
  util/pom.xml
  util/src/main/java/io/kubernetes/client/informer/cache/ReflectorRunnable.java
  util/src/test/java/io/kubernetes/client/informer/cache/ReflectorRunnableTest.java
Labels: approved, cncf-cla: yes, lgtm, size/L

#1371 Feat(Spring-Integration): Support auto-configure to shorten configuration steps
  docs/java-controller-tutorial-rewrite-rs-controller.md
  examples/src/main/java/io/kubernetes/client/examples/SpringControllerExample.java
  spring/src/main/java/io/kubernetes/client/spring/extended/controller/KubernetesInformerConfigurer.java
  spring/src/main/java/io/kubernetes/client/spring/extended/controller/KubernetesInformerFactoryProcessor.java
  spring/src/main/java/io/kubernetes/client/spring/extended/controller/KubernetesReconcilerConfigurer.java
  spring/src/main/java/io/kubernetes/client/spring/extended/controller/KubernetesReconcilerProcessor.java
  spring/src/main/java/io/kubernetes/client/spring/extended/controller/annotation/KubernetesReconciler.java
  spring/src/main/java/io/kubernetes/client/spring/extended/controller/config/ConditionalOnActuatorPrometheusEndpointEnabled.java
  spring/src/main/java/io/kubernetes/client/spring/extended/controller/config/ConditionalOnKubernetesInformerEnabled.java
  spring/src/main/java/io/kubernetes/client/spring/extended/controller/config/ConditionalOnKubernetesReconcilerEnabled.java
  spring/src/main/java/io/kubernetes/client/spring/extended/controller/config/KubernetesInformerAutoConfiguration.java
  spring/src/main/java/io/kubernetes/client/spring/extended/controller/config/KubernetesReconcilerAutoConfiguration.java
  spring/src/main/resources/META-INF/spring.factories
  spring/src/test/java/io/kubernetes/client/spring/extended/controller/KubernetesInformerCreatorTest.java
  spring/src/test/java/io/kubernetes/client/spring/extended/controller/KubernetesReconcilerCreatorTest.java
Labels: approved, cncf-cla: yes, lgtm, size/L

#1373 Feat: Utilities for doing client-side load-balancing based-on endpoints
  extended/src/main/java/io/kubernetes/client/extended/network/EndpointsLoadBalancer.java
  extended/src/main/java/io/kubernetes/client/extended/network/EndpointsUtils.java
  extended/src/main/java/io/kubernetes/client/extended/network/LoadBalanceStrategy.java
  extended/src/main/java/io/kubernetes/client/extended/network/LoadBalancer.java
  extended/src/main/java/io/kubernetes/client/extended/network/RoundRobinLoadBalanceStrategy.java
  extended/src/test/java/io/kubernetes/client/extended/network/EndpointsLoadBalancerTests.java
  extended/src/test/java/io/kubernetes/client/extended/network/RoundRobinEndpointsLoadBalancerTests.java
Labels: approved, cncf-cla: yes, lgtm, size/L

#1381 [Code cleanup] making nested class static
  extended/src/main/java/io/kubernetes/client/extended/event/legacy/EventAggregator.java
  extended/src/main/java/io/kubernetes/client/extended/event/legacy/EventLogger.java
  extended/src/main/java/io/kubernetes/client/extended/workqueue/DefaultDelayingQueue.java
  extended/src/test/java/io/kubernetes/client/extended/controller/ControllerManagerTest.java
  spring/src/test/java/io/kubernetes/client/spring/extended/controller/KubernetesInformerCreatorTest.java
  util/src/test/java/io/kubernetes/client/WebsocketStreamHandlerTest.java
  util/src/test/java/io/kubernetes/client/util/KubeConfigTest.java
Labels: approved, cncf-cla: yes, lgtm, size/S

#1379 Trim controller example based on controller auto-configuration
  examples/src/main/java/io/kubernetes/client/examples/SpringControllerExample.java
Labels: approved, cncf-cla: yes, lgtm, size/M

#1391 Update maven.yml fix graalvm tests
  .github/workflows/maven.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1388 Create codeql-analysis.yml
  .github/workflows/codeql-analysis.yml
Labels: approved, cncf-cla: yes, lgtm, size/M

#1392 Doc: Use module name directly instead of symlink
  README.md
  examples/examples-release-last
Labels: approved, cncf-cla: yes, lgtm, size/M

#1395 Fixes a few places where the api-discovery is missed
  extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlCordon.java
  extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlGet.java
  extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlPatch.java
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1397 Triming readme page content by referencing wiki pages
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#1405 spring-boot: manage bean as infrastructure via KubectlCreate annotation
  spring/src/main/java/io/kubernetes/client/spring/extended/manifests/KubernetesKubectlCreateProcessor.java
  spring/src/main/java/io/kubernetes/client/spring/extended/manifests/annotation/KubectlCreate.java
  spring/src/main/java/io/kubernetes/client/spring/extended/manifests/config/ConditionalOnKubernetesManifestsEnabled.java
  spring/src/main/java/io/kubernetes/client/spring/extended/manifests/config/KubernetesManifestsAutoConfiguration.java
  spring/src/main/resources/META-INF/spring.factories
  spring/src/test/java/io/kubernetes/client/spring/extended/manifests/KubernetesManifestTest.java
  spring/src/test/java/io/kubernetes/client/spring/extended/manifests/TestApplication.java
  spring/src/test/resources/discovery-api-v1.json
  spring/src/test/resources/discovery-api.json
  spring/src/test/resources/discovery-apis.json
Labels: approved, cncf-cla: yes, lgtm, size/L
