Repository kubernetes-client/java, pull requests merged in 2020-08, with the labels that each got.

#1130 Little improvements to the update client script
  scripts/update-client.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#1135 Clean up/refactor kubectl to share some code and add kubectl exec.
  examples/src/main/java/io/kubernetes/client/examples/KubectlExample.java
  extended/src/main/java/io/kubernetes/client/extended/kubectl/Kubectl.java
  extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlExec.java
  extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlLabel.java
  extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlScale.java
  extended/src/test/java/io/kubernetes/client/extended/kubectl/KubectlScaleTest.java
Labels: approved, cncf-cla: yes, lgtm, size/L

#1136 Refactor(kubectl): get rid of force api type class casting
  extended/src/main/java/io/kubernetes/client/extended/kubectl/Kubectl.java
  extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlExec.java
  extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlLabel.java
  extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlScale.java
Labels: approved, cncf-cla: yes, lgtm, size/S

#1126 Kubectl annotate implementation
  extended/src/main/java/io/kubernetes/client/extended/kubectl/Kubectl.java
  extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlAnnotate.java
  extended/src/test/java/io/kubernetes/client/extended/kubectl/KubectlAnnotateTest.java
  util/src/main/java/io/kubernetes/client/util/annotations/Annotations.java
Labels: approved, cncf-cla: yes, lgtm, size/L

#1139 Kubectl exec follow-up & refactors
  examples/src/main/java/io/kubernetes/client/examples/KubectlExample.java
  extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlAnnotate.java
  extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlExec.java
Labels: approved, cncf-cla: yes, lgtm, size/S

#1138 Implement Kubectl Log
  examples/src/main/java/io/kubernetes/client/examples/KubectlExample.java
  extended/src/main/java/io/kubernetes/client/extended/kubectl/Kubectl.java
  extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlLog.java
Labels: approved, cncf-cla: yes, lgtm, size/M

#1140 Graceful shutdown sharedprocessor
  util/src/main/java/io/kubernetes/client/informer/cache/SharedProcessor.java
  util/src/test/java/io/kubernetes/client/informer/cache/SharedProcessorTest.java
Labels: approved, cncf-cla: yes, lgtm, size/M

#1145 Fix generic watches, add test.
  util/src/main/java/io/kubernetes/client/util/generic/GenericKubernetesApi.java
  util/src/test/java/io/kubernetes/client/util/generic/GenericKubernetesApiTest.java
Labels: approved, cncf-cla: yes, lgtm, size/S

#1137 Add devcontainer for github codespaces.
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  .devcontainer/library-scripts/README.md
  .devcontainer/library-scripts/common-debian.sh
  .devcontainer/library-scripts/node-debian.sh
  .devcontainer/maven-settings.xml
Labels: approved, cncf-cla: yes, lgtm, size/L

#1142 Promote apiGroup/apiVersion/resourceName to resourceBuilder
  extended/src/main/java/io/kubernetes/client/extended/kubectl/Kubectl.java
  extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlAnnotate.java
  extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlLabel.java
Labels: approved, cncf-cla: yes, lgtm, size/M

#1144 Add port forward to kubectl
  examples/src/main/java/io/kubernetes/client/examples/KubectlExample.java
  examples/src/main/java/io/kubernetes/client/examples/PortForwardExample.java
  extended/src/main/java/io/kubernetes/client/extended/kubectl/Kubectl.java
  extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlExec.java
  extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlPortForward.java
  util/src/main/java/io/kubernetes/client/PortForward.java
  util/src/main/java/io/kubernetes/client/util/WebSocketStreamHandler.java
  util/src/test/java/io/kubernetes/client/PortForwardTest.java
Labels: approved, cncf-cla: yes, lgtm, size/L

#1148 Cherry pick some fixes to set the stage for 9.0.1
  util/src/main/java/io/kubernetes/client/informer/cache/SharedProcessor.java
  util/src/main/java/io/kubernetes/client/util/generic/GenericKubernetesApi.java
  util/src/test/java/io/kubernetes/client/informer/cache/SharedProcessorTest.java
  util/src/test/java/io/kubernetes/client/util/generic/GenericKubernetesApiTest.java
Labels: approved, cncf-cla: yes, lgtm, size/M

#1150 Release 9.0.1
  examples/pom.xml
  extended/pom.xml
  kubernetes/pom.xml
  pom.xml
  proto/pom.xml
  spring/pom.xml
  util/pom.xml
Labels: approved, cncf-cla: yes, lgtm, size/S

#1147 kubectl(api-resources): api discovery implementation
  examples/src/main/java/io/kubernetes/client/examples/KubectlExample.java
  extended/src/main/java/io/kubernetes/client/extended/kubectl/Kubectl.java
  extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlApiResources.java
  util/src/main/java/io/kubernetes/client/Discovery.java
  util/src/test/java/io/kubernetes/client/DiscoveryTest.java
Labels: approved, cncf-cla: yes, lgtm, size/L

#1159 add overloading method to copy in memory binary data to pod
  util/src/main/java/io/kubernetes/client/Copy.java
  util/src/test/java/io/kubernetes/client/CopyTest.java
Labels: approved, cncf-cla: yes, lgtm, size/M

#1151 Add support for KubectlCopy.
  examples/src/main/java/io/kubernetes/client/examples/KubectlExample.java
  extended/src/main/java/io/kubernetes/client/extended/kubectl/Kubectl.java
  extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlCopy.java
Labels: approved, cncf-cla: yes, lgtm, size/L

#1153 Add node metrics helper utilities.
  examples/src/main/java/io/kubernetes/client/examples/MetricsExample.java
  kubernetes/src/main/java/io/kubernetes/client/custom/NodeMetrics.java
  kubernetes/src/main/java/io/kubernetes/client/custom/NodeMetricsList.java
  util/src/main/java/io/kubernetes/client/Metrics.java
Labels: approved, cncf-cla: yes, lgtm, size/L

#1164 Chore: Better error messages - save the exception tracestack context
  util/src/main/java/io/kubernetes/client/informer/cache/ProcessorListener.java
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1165 Doc: Fixes the gap between doc & impl for informer factory
  util/src/main/java/io/kubernetes/client/informer/SharedInformerFactory.java
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1157 Add support for taints and kubectl taint.
  examples/src/main/java/io/kubernetes/client/examples/KubectlExample.java
  extended/src/main/java/io/kubernetes/client/extended/kubectl/Kubectl.java
  extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlTaint.java
  util/src/main/java/io/kubernetes/client/util/taints/Taints.java
  util/src/test/java/io/kubernetes/client/util/taints/TaintsTest.java
Labels: approved, cncf-cla: yes, lgtm, size/L

#1166 Add support for Pod metrics.
  examples/src/main/java/io/kubernetes/client/examples/MetricsExample.java
  kubernetes/src/main/java/io/kubernetes/client/custom/ContainerMetrics.java
  kubernetes/src/main/java/io/kubernetes/client/custom/PodMetrics.java
  kubernetes/src/main/java/io/kubernetes/client/custom/PodMetricsList.java
  util/src/main/java/io/kubernetes/client/Metrics.java
Labels: approved, cncf-cla: yes, lgtm, size/L

#1167 Add utilities for instrumentation.
  examples/pom.xml
  examples/src/main/java/io/kubernetes/client/examples/PrometheusExample.java
  util/pom.xml
  util/src/main/java/io/kubernetes/client/monitoring/Monitoring.java
  util/src/main/java/io/kubernetes/client/monitoring/PrometheusInterceptor.java
Labels: approved, cncf-cla: yes, lgtm, size/L

#1107 Supporting copy operation when tar is not present
  util/src/main/java/io/kubernetes/client/Copy.java
  util/src/main/java/io/kubernetes/client/TreeNode.java
  util/src/test/java/io/kubernetes/client/CopyTest.java
Labels: approved, cncf-cla: yes, lgtm, size/L

#1172 Refactor: Share more codes between kubectl entry methods
  examples/src/main/java/io/kubernetes/client/examples/KubectlExample.java
  extended/src/main/java/io/kubernetes/client/extended/kubectl/Kubectl.java
  extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlAnnotate.java
  extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlApiResources.java
  extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlCopy.java
  extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlExec.java
  extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlLabel.java
  extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlLog.java
  extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlPortForward.java
  extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlScale.java
  extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlTaint.java
  extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlVersion.java
  extended/src/test/java/io/kubernetes/client/extended/kubectl/KubectlAnnotateTest.java
  extended/src/test/java/io/kubernetes/client/extended/kubectl/KubectlLabelTest.java
  extended/src/test/java/io/kubernetes/client/extended/kubectl/KubectlScaleTest.java
Labels: approved, cncf-cla: yes, lgtm, size/L

#1177 Refactor: Separate model mapper from Yaml
  util/src/main/java/io/kubernetes/client/util/ModelMapper.java
  util/src/main/java/io/kubernetes/client/util/Yaml.java
Labels: approved, cncf-cla: yes, lgtm, size/L

#1178 Add an initial implementation of top
  examples/src/main/java/io/kubernetes/client/examples/KubectlExample.java
  extended/src/main/java/io/kubernetes/client/extended/kubectl/Kubectl.java
  extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlTop.java
Labels: approved, cncf-cla: yes, lgtm, size/L

#1171 Instrumenting follow-up: metrics labelling w/ finer granularity
  pom.xml
  util/pom.xml
  util/src/main/java/io/kubernetes/client/apimachinery/GroupVersionKind.java
  util/src/main/java/io/kubernetes/client/apimachinery/GroupVersionResource.java
  util/src/main/java/io/kubernetes/client/apimachinery/KubernetesRequestDigest.java
  util/src/main/java/io/kubernetes/client/apimachinery/KubernetesResource.java
  util/src/main/java/io/kubernetes/client/apimachinery/KubernetesVerb.java
  util/src/main/java/io/kubernetes/client/apimachinery/ParseKubernetesResourceException.java
  util/src/main/java/io/kubernetes/client/monitoring/PrometheusInterceptor.java
Labels: approved, cncf-cla: yes, lgtm, size/L

#1189 Github action: GraalVM test
  .github/workflows/maven.yml
Labels: approved, cncf-cla: yes, lgtm, size/S

#1191 Refactor: Add informer constructor for generic api
  spring/src/main/java/io/kubernetes/client/spring/extended/controller/KubernetesInformerFactoryProcessor.java
  util/src/main/java/io/kubernetes/client/informer/SharedInformerFactory.java
Labels: approved, cncf-cla: yes, lgtm, size/M

#1192 Clean up- adding Standard Charset constant
  util/src/main/java/io/kubernetes/client/util/authenticators/OpenIDConnectAuthenticator.java
  util/src/main/java/io/kubernetes/client/util/credentials/UsernamePasswordAuthentication.java
  util/src/test/java/io/kubernetes/client/util/KubeConfigTest.java
  util/src/test/java/io/kubernetes/client/util/credentials/OpenIDConnectAuthenticationTest.java
Labels: approved, cncf-cla: yes, lgtm, size/S

#1190 E2E Test: BDD testing (groovy+spock) for informer utilities
  .github/workflows/maven.yml
  e2e/pom.xml
  e2e/src/test/groovy/io/kubernetes/client/e2e/informer/NamespaceInformerTest.groovy
  e2e/src/test/groovy/io/kubernetes/client/e2e/kubectl/KubectlLabelTest.groovy
  pom.xml
Labels: approved, cncf-cla: yes, lgtm, size/L

#1181 Add support for kubectl cordon.
  examples/src/main/java/io/kubernetes/client/examples/KubectlExample.java
  extended/src/main/java/io/kubernetes/client/extended/kubectl/Kubectl.java
  extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlCordon.java
Labels: approved, cncf-cla: yes, lgtm, size/M

#1193 Clean up various files
  util/src/main/java/io/kubernetes/client/informer/cache/DeltaFIFO.java
  util/src/main/java/io/kubernetes/client/util/ModelMapper.java
  util/src/main/java/io/kubernetes/client/util/Watch.java
  util/src/main/java/io/kubernetes/client/util/WebSocketStreamHandler.java
  util/src/main/java/io/kubernetes/client/util/Yaml.java
  util/src/main/java/io/kubernetes/client/util/authenticators/OpenIDConnectAuthenticator.java
  util/src/main/java/io/kubernetes/client/util/generic/GenericKubernetesApi.java
  util/src/main/java/io/kubernetes/client/util/taints/Taints.java
  util/src/test/java/io/kubernetes/client/util/TestUtils.java
  util/src/test/java/io/kubernetes/client/util/YamlTest.java
Labels: approved, cncf-cla: yes, lgtm, size/M

#1187 Equivalent for kubectl create
  extended/src/main/java/io/kubernetes/client/extended/kubectl/Kubectl.java
  extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlCreate.java
  extended/src/test/java/io/kubernetes/client/extended/kubectl/KubectlCreateTest.java
  extended/src/test/resources/discovery-api-v1.json
  extended/src/test/resources/discovery-api.json
  extended/src/test/resources/discovery-apis.json
  util/src/main/java/io/kubernetes/client/apimachinery/GroupVersionKind.java
  util/src/main/java/io/kubernetes/client/util/ModelMapper.java
  util/src/main/java/io/kubernetes/client/util/Namespaces.java
  util/src/main/java/io/kubernetes/client/util/generic/GenericKubernetesApi.java
  util/src/test/java/io/kubernetes/client/util/ModelMapperTest.java
Labels: approved, cncf-cla: yes, lgtm, size/L

#1201 Update gmaven-plus version.
  e2e/pom.xml
  pom.xml
Labels: approved, cncf-cla: yes, lgtm, size/XS
