Repository kubernetes-client/java, pull requests merged in 2020-07, with the labels that each got.

#1026 Reflector and leader-elector exception handlers
  extended/src/main/java/io/kubernetes/client/extended/leaderelection/LeaderElector.java
  extended/src/test/java/io/kubernetes/client/extended/leaderelection/LeaderElectionTest.java
  util/src/main/java/io/kubernetes/client/informer/cache/ReflectorRunnable.java
  util/src/test/java/io/kubernetes/client/informer/cache/ReflectorRunnableTest.java
Labels: approved, cncf-cla: yes, lgtm, size/L

#1031 Support on-new-leader hook for leader elector
  extended/src/main/java/io/kubernetes/client/extended/leaderelection/LeaderElector.java
  extended/src/test/java/io/kubernetes/client/extended/leaderelection/LeaderElectionTest.java
Labels: approved, cncf-cla: yes, lgtm, size/L

#1037 Chore: Github action testing against multiple JDK versions
  .github/workflows/maven.yml
  .travis.yml
Labels: approved, cncf-cla: yes, lgtm, size/S

#1044 Report controller loop abortion due to any unknown error
  extended/src/main/java/io/kubernetes/client/extended/controller/DefaultController.java
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1045 Prune "skip" configuration for deploying proto module
  proto/pom.xml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1047 Fixing build error that is thrown with Java 11 and above
  pom.xml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1054 Update Exec.java
  util/src/main/java/io/kubernetes/client/Exec.java
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1051 Removing duplicate code
  util/src/main/java/io/kubernetes/client/ProtoClient.java
Labels: approved, cncf-cla: yes, lgtm, size/S

#1063 Removing unused imports and adding a log parameter for placeholder
  util/src/main/java/io/kubernetes/client/informer/impl/DefaultSharedIndexInformer.java
  util/src/test/java/io/kubernetes/client/util/PatchUtilsTest.java
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1059 Clean up the code
  examples/src/main/java/io/kubernetes/client/examples/ExecExample.java
  util/src/main/java/io/kubernetes/client/Copy.java
  util/src/main/java/io/kubernetes/client/PortForward.java
  util/src/main/java/io/kubernetes/client/informer/cache/SharedProcessor.java
Labels: approved, cncf-cla: yes, lgtm, size/S, tide/merge-method-squash

#1066 Remove the lock and make methods synchronized
  util/src/main/java/io/kubernetes/client/informer/cache/Cache.java
Labels: approved, cncf-cla: yes, lgtm, size/L

#1070 Removing deprecated class in Junit
  util/src/test/java/io/kubernetes/client/util/ClientBuilderTest.java
  util/src/test/java/io/kubernetes/client/util/credentials/AccessTokenAuthenticationTest.java
  util/src/test/java/io/kubernetes/client/util/credentials/UsernamePasswordAuthenticationTest.java
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1071 Removing the deprecated method of Google Gson
  util/src/main/java/io/kubernetes/client/util/KubeConfig.java
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1076 Removing deprecated API
  util/src/test/java/io/kubernetes/client/util/YamlTest.java
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1085 README.md: simplify cd command
  README.md
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/XS

#1084 Switiching to apps/v1 deployment api in the examples
  examples/src/main/java/io/kubernetes/client/examples/ExpandedExample.java
  examples/src/main/java/io/kubernetes/client/examples/PatchExample.java
Labels: approved, cncf-cla: yes, lgtm, size/M

#1087 Move generic api to utility module
  examples/src/main/java/io/kubernetes/client/examples/GenericClientExample.java
  extended/src/main/java/io/kubernetes/client/extended/generic/GenericKubernetesApi.java
  spring/src/main/java/io/kubernetes/client/spring/extended/controller/KubernetesInformerFactoryProcessor.java
  util/src/main/java/io/kubernetes/client/util/generic/GenericKubernetesApi.java
  util/src/main/java/io/kubernetes/client/util/generic/KubernetesApiResponse.java
  util/src/main/java/io/kubernetes/client/util/generic/options/CreateOptions.java
  util/src/main/java/io/kubernetes/client/util/generic/options/DeleteOptions.java
  util/src/main/java/io/kubernetes/client/util/generic/options/GetOptions.java
  util/src/main/java/io/kubernetes/client/util/generic/options/ListOptions.java
  util/src/main/java/io/kubernetes/client/util/generic/options/PatchOptions.java
  util/src/main/java/io/kubernetes/client/util/generic/options/UpdateOptions.java
  util/src/test/java/io/kubernetes/client/util/generic/FooCustomResource.java
  util/src/test/java/io/kubernetes/client/util/generic/FooCustomResourceList.java
  util/src/test/java/io/kubernetes/client/util/generic/GenericKubernetesApiForCoreApiTest.java
  util/src/test/java/io/kubernetes/client/util/generic/GenericKubernetesApiTest.java
  util/src/test/java/io/kubernetes/client/util/generic/GenericKubernetesGetApiTest.java
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#1096 Gracefully shutdown listener pool
  util/src/main/java/io/kubernetes/client/informer/cache/SharedProcessor.java
  util/src/test/java/io/kubernetes/client/informer/cache/SharedProcessorTest.java
Labels: approved, cncf-cla: yes, lgtm, size/M

#1078 Kubectl label equivalence
  extended/src/main/java/io/kubernetes/client/extended/kubectl/Kubectl.java
  extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlLabel.java
  extended/src/main/java/io/kubernetes/client/extended/kubectl/exception/KubectlException.java
  extended/src/test/java/io/kubernetes/client/extended/kubectl/KubectlLabelTest.java
  util/src/main/java/io/kubernetes/client/util/generic/GenericKubernetesApi.java
  util/src/main/java/io/kubernetes/client/util/labels/Labels.java
  util/src/test/java/io/kubernetes/client/util/labels/LabelsTest.java
Labels: approved, cncf-cla: yes, lgtm, size/XL

#1088 Fluent error handling shortcut for generic api
  examples/src/main/java/io/kubernetes/client/examples/GenericClientExample.java
  util/src/main/java/io/kubernetes/client/util/generic/KubernetesApiResponse.java
  util/src/test/java/io/kubernetes/client/util/generic/KubernetesApiResponseTest.java
Labels: approved, cncf-cla: yes, lgtm, size/L

#1100 Release 9.0.0
  examples/pom.xml
  extended/pom.xml
  kubernetes/pom.xml
  pom.xml
  proto/pom.xml
  spring/pom.xml
  util/pom.xml
Labels: approved, cncf-cla: yes, lgtm, size/M

#1097 Chore: Adding maven central badge
  .github/workflows/maven.yml
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1102 Chore: Update compatability chart.
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#1103 Replace github action badge instead of travis badge
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1104 Throw the original exception if failed deserializing status
  extended/src/main/java/io/kubernetes/client/extended/generic/GenericKubernetesApi.java
  spring/src/main/java/io/kubernetes/client/spring/extended/controller/KubernetesInformerFactoryProcessor.java
  util/src/main/java/io/kubernetes/client/util/generic/GenericKubernetesApi.java
  util/src/test/java/io/kubernetes/client/util/generic/KubernetesApiResponseTest.java
Labels: approved, cncf-cla: yes, lgtm, size/M

#1105 Adding utility to get K8 version
  util/src/main/java/io/kubernetes/client/util/version/Version.java
  util/src/test/java/io/kubernetes/client/util/version/VersionTest.java
Labels: approved, cncf-cla: yes, lgtm, size/L

#1110 Documenting guidance on running formatter
  README.md
  scripts/update-client.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1111 Kubectl version wrapper and shortcut
  extended/src/main/java/io/kubernetes/client/extended/kubectl/Kubectl.java
  extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlVersion.java
Labels: approved, cncf-cla: yes, lgtm, size/M

#1112 Code generation: Refresh client version
  settings
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1115 Provide standard method to cleanup schedulers
  extended/src/main/java/io/kubernetes/client/extended/leaderelection/LeaderElector.java
Labels: approved, cncf-cla: yes, lgtm, size/S

#1116 Leader election autoclosable example
  examples/src/main/java/io/kubernetes/client/examples/LeaderElectionExample.java
Labels: approved, cncf-cla: yes, lgtm, size/S

#1113 Add an implementation of kubectl scale.
  examples/src/main/java/io/kubernetes/client/examples/Kubectl.java
  extended/src/main/java/io/kubernetes/client/extended/kubectl/Kubectl.java
  extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlLabel.java
  extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlScale.java
  extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlVersion.java
  extended/src/test/java/io/kubernetes/client/extended/kubectl/KubectlScaleTest.java
Labels: approved, cncf-cla: yes, lgtm, size/L

#1118 Support custom workqueue-keyfunc to directly manipulate work-queue instance
  extended/src/main/java/io/kubernetes/client/extended/controller/DefaultController.java
  extended/src/main/java/io/kubernetes/client/extended/controller/DefaultControllerWatch.java
  spring/src/main/java/io/kubernetes/client/spring/extended/controller/KubernetesReconcilerProcessor.java
  spring/src/main/java/io/kubernetes/client/spring/extended/controller/annotation/KubernetesReconcilerWatch.java
  spring/src/test/java/io/kubernetes/client/spring/extended/controller/KubernetesReconcilerCreatorTest.java
  util/src/main/java/io/kubernetes/client/informer/impl/DefaultSharedIndexInformer.java
Labels: approved, cncf-cla: yes, lgtm, size/L

#1122 Rev okhttp3 dependency to 3.14.9
  kubernetes/pom.xml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1121 Expand the kubectl example.
  examples/src/main/java/io/kubernetes/client/examples/Kubectl.java
  examples/src/main/java/io/kubernetes/client/examples/KubectlExample.java
Labels: approved, cncf-cla: yes, lgtm, size/L
