Repository kubernetes-client/java, pull requests merged in 2020-12, with the labels that each got.

#1407 Add source jars to deployment
  pom.xml
Labels: approved, cncf-cla: yes, lgtm, size/S

#1322 Exec.exec returning Future and hiding Process as an implementation detail
  kubernetes/src/main/java/io/kubernetes/client/custom/IOTrio.java
  util/src/main/java/io/kubernetes/client/Exec.java
  util/src/test/java/io/kubernetes/client/ExecCallbacksTest.java
Labels: approved, cncf-cla: yes, lgtm, size/XL

#1416 Allow controller builder to set ready timeout
  extended/src/main/java/io/kubernetes/client/extended/controller/builder/DefaultControllerBuilder.java
Labels: approved, cncf-cla: yes, lgtm, size/S

#1409 Feature: Support namespace-scoped informer
  pom.xml
  spring/src/main/java/io/kubernetes/client/spring/extended/controller/KubernetesInformerFactoryProcessor.java
  spring/src/main/java/io/kubernetes/client/spring/extended/controller/KubernetesReconcilerProcessor.java
  spring/src/main/java/io/kubernetes/client/spring/extended/controller/annotation/KubernetesInformer.java
  spring/src/test/java/io/kubernetes/client/spring/extended/controller/KubernetesInformerCreatorTest.java
  spring/src/test/java/io/kubernetes/client/spring/extended/controller/KubernetesReconcilerCreatorTest.java
  spring/src/test/java/io/kubernetes/client/spring/extended/controller/TestApplication.java
  util/pom.xml
  util/src/main/java/io/kubernetes/client/informer/SharedInformerFactory.java
  util/src/main/java/io/kubernetes/client/util/Namespaces.java
  util/src/main/java/io/kubernetes/client/util/generic/GenericKubernetesApi.java
  util/src/test/java/io/kubernetes/client/informer/SharedInformerFactoryTest.java
  util/src/test/java/io/kubernetes/client/util/generic/GenericKubernetesApiForCoreApiTest.java
Labels: approved, cncf-cla: yes, lgtm, size/L

#1410 Feat: From yaml injection
  spring/src/main/java/io/kubernetes/client/spring/extended/manifests/KubernetesFromYamlProcessor.java
  spring/src/main/java/io/kubernetes/client/spring/extended/manifests/annotation/FromYaml.java
  spring/src/main/java/io/kubernetes/client/spring/extended/manifests/config/KubernetesManifestsAutoConfiguration.java
  spring/src/test/java/io/kubernetes/client/spring/extended/manifests/KubernetesFromYamlTest.java
  spring/src/test/java/io/kubernetes/client/spring/extended/manifests/KubernetesManifestTest.java
  spring/src/test/java/io/kubernetes/client/spring/extended/manifests/TestApplication.java
  spring/src/test/resources/service.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#1420 Cast to Runnable to avoid compiler error
  util/src/main/java/io/kubernetes/client/informer/SharedInformerFactory.java
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1419 Add a KubectlApply processor for Spring.
  spring/src/main/java/io/kubernetes/client/spring/extended/manifests/KubernetesKubectlApplyProcessor.java
  spring/src/main/java/io/kubernetes/client/spring/extended/manifests/annotation/KubectlApply.java
  spring/src/main/java/io/kubernetes/client/spring/extended/manifests/config/KubernetesManifestsAutoConfiguration.java
  spring/src/test/java/io/kubernetes/client/spring/extended/manifests/KubernetesManifestTest.java
Labels: approved, cncf-cla: yes, lgtm, size/L

#1423 Make sundr codegen optional so it only applies to the k8s API code
  .gitignore
  extended/src/main/java/io/kubernetes/client/extended/event/legacy/EventUtils.java
  extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlAnnotate.java
  extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlDelete.java
  extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlGet.java
  extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlLabel.java
  extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlReplace.java
  kubernetes/pom.xml
  util/pom.xml
Labels: approved, cncf-cla: yes, lgtm, size/S

#1427 Allow specify an owner reference for leader election lock
  extended/src/main/java/io/kubernetes/client/extended/leaderelection/LeaderElectionConfig.java
  extended/src/main/java/io/kubernetes/client/extended/leaderelection/LeaderElectionRecord.java
  extended/src/main/java/io/kubernetes/client/extended/leaderelection/LeaderElector.java
  extended/src/main/java/io/kubernetes/client/extended/leaderelection/resourcelock/ConfigMapLock.java
  extended/src/main/java/io/kubernetes/client/extended/leaderelection/resourcelock/EndpointsLock.java
  extended/src/main/java/io/kubernetes/client/extended/leaderelection/resourcelock/LeaseLock.java
Labels: approved, cncf-cla: yes, lgtm, size/M

#1426 Add path normalization for archive files.
  pom.xml
  util/pom.xml
  util/src/main/java/io/kubernetes/client/Copy.java
Labels: approved, cncf-cla: yes, lgtm, size/S

#1430 Prevents event recorder worker thread leakage
  extended/src/main/java/io/kubernetes/client/extended/event/legacy/LegacyEventBroadcaster.java
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1425 Breaking sources when wildcard or guava imports present
  examples/examples-release-10/src/main/java/io/kubernetes/client/examples/InformerExample.java
  examples/examples-release-10/src/main/java/io/kubernetes/client/examples/SpringControllerExample.java
  examples/examples-release-11/src/main/java/io/kubernetes/client/examples/InformerExample.java
  examples/examples-release-11/src/main/java/io/kubernetes/client/examples/SpringControllerExample.java
  extended/src/test/java/io/kubernetes/client/extended/controller/builder/DefaultControllerBuilderTest.java
  extended/src/test/java/io/kubernetes/client/extended/kubectl/KubectlGetTest.java
  kubernetes/src/main/java/io/kubernetes/client/openapi/ApiClient.java
  kubernetes/src/main/java/io/kubernetes/client/openapi/GzipRequestInterceptor.java
  pom.xml
  spring/src/main/java/io/kubernetes/client/spring/extended/controller/KubernetesReconcilerProcessor.java
  spring/src/main/java/io/kubernetes/client/spring/extended/controller/annotation/KubernetesReconcilerWatch.java
  spring/src/main/java/io/kubernetes/client/spring/extended/controller/factory/KubernetesControllerFactory.java
  spring/src/main/java/io/kubernetes/client/spring/extended/manifests/config/ConditionalOnKubernetesManifestsEnabled.java
  spring/src/main/java/io/kubernetes/client/spring/extended/network/config/ConditionalOnKubernetesLoadBalancerEnabled.java
  spring/src/test/java/io/kubernetes/client/spring/extended/network/KubernetesEndpointsLoadBalancerCreatorTest.java
  util/src/main/java/io/kubernetes/client/util/ClientBuilder.java
  util/src/test/java/io/kubernetes/client/informer/cache/CacheTest.java
  util/src/test/java/io/kubernetes/client/informer/impl/DefaultSharedIndexInformerTest.java
  util/src/test/java/io/kubernetes/client/util/generic/GenericKubernetesApiForCoreApiTest.java
  util/src/test/java/io/kubernetes/client/util/generic/GenericKubernetesApiTest.java
  util/src/test/java/io/kubernetes/client/util/generic/KubernetesApiResponseTest.java
Labels: approved, cncf-cla: yes, lgtm, size/L

#1432 Caching local maven repositories for github action jobs to reduce flakiness
  .github/workflows/maven.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1429 Removes prometheus actuator endpoints
  spring/src/main/java/io/kubernetes/client/spring/extended/controller/config/ConditionalOnActuatorPrometheusEndpointEnabled.java
  spring/src/main/java/io/kubernetes/client/spring/extended/controller/config/KubernetesReconcilerAutoConfiguration.java
  spring/src/main/java/io/kubernetes/client/spring/extended/controller/metrics/PrometheusScrapeEndpoint.java
Labels: approved, cncf-cla: yes, lgtm, size/M

#1433 Cherry-pick #1426
  pom.xml
  util/pom.xml
  util/src/main/java/io/kubernetes/client/Copy.java
Labels: approved, cncf-cla: yes, lgtm, size/S

#1435 Release 9.0.2
  examples/pom.xml
  extended/pom.xml
  kubernetes/pom.xml
  pom.xml
  proto/pom.xml
  spring/pom.xml
  util/pom.xml
  util/src/main/java/io/kubernetes/client/informer/cache/SharedProcessor.java
  util/src/main/java/io/kubernetes/client/util/generic/GenericKubernetesApi.java
  util/src/test/java/io/kubernetes/client/informer/cache/SharedProcessorTest.java
  util/src/test/java/io/kubernetes/client/util/generic/GenericKubernetesApiTest.java
Labels: approved, cncf-cla: yes, lgtm, size/M

#1438 Fix Guava regexp in spotless config
  extended/src/test/java/io/kubernetes/client/extended/kubectl/KubectlApplyTest.java
  extended/src/test/java/io/kubernetes/client/extended/kubectl/KubectlCreateTest.java
  extended/src/test/java/io/kubernetes/client/extended/kubectl/KubectlDrainTest.java
  extended/src/test/java/io/kubernetes/client/extended/pager/PagerTest.java
  pom.xml
  spring/src/test/java/io/kubernetes/client/spring/extended/manifests/KubernetesManifestTest.java
  util/src/test/java/io/kubernetes/client/ExecTest.java
  util/src/test/java/io/kubernetes/client/PodLogsTest.java
  util/src/test/java/io/kubernetes/client/Resources.java
  util/src/test/java/io/kubernetes/client/informer/cache/DeltaFIFOTest.java
  util/src/test/java/io/kubernetes/client/util/ClientBuilderTest.java
  util/src/test/java/io/kubernetes/client/util/FilePersisterTest.java
  util/src/test/java/io/kubernetes/client/util/SSLUtilsTest.java
  util/src/test/java/io/kubernetes/client/util/YamlTest.java
  util/src/test/java/io/kubernetes/client/util/credentials/ClientCertificateAuthenticationTest.java
  util/src/test/java/io/kubernetes/client/util/credentials/OpenIDConnectAuthenticationTest.java
  util/src/test/java/io/kubernetes/client/util/credentials/TokenFileAuthenticationTest.java
  util/src/test/java/io/kubernetes/client/util/credentials/UsernamePasswordAuthenticationTest.java
Labels: approved, cncf-cla: yes, lgtm, size/L

#1444 Factor Guava out of examples
  examples/examples-release-10/pom.xml
  examples/examples-release-10/src/main/java/io/kubernetes/client/examples/AttachExample.java
  examples/examples-release-10/src/main/java/io/kubernetes/client/examples/CopyExample.java
  examples/examples-release-10/src/main/java/io/kubernetes/client/examples/ExecExample.java
  examples/examples-release-10/src/main/java/io/kubernetes/client/examples/KubectlExample.java
  examples/examples-release-10/src/main/java/io/kubernetes/client/examples/LogsExample.java
  examples/examples-release-10/src/main/java/io/kubernetes/client/examples/PortForwardExample.java
  examples/examples-release-10/src/main/java/io/kubernetes/client/examples/Streams.java
  examples/examples-release-11/pom.xml
  examples/examples-release-11/src/main/java/io/kubernetes/client/examples/AttachExample.java
  examples/examples-release-11/src/main/java/io/kubernetes/client/examples/CopyExample.java
  examples/examples-release-11/src/main/java/io/kubernetes/client/examples/ExecExample.java
  examples/examples-release-11/src/main/java/io/kubernetes/client/examples/KubectlExample.java
  examples/examples-release-11/src/main/java/io/kubernetes/client/examples/LogsExample.java
  examples/examples-release-11/src/main/java/io/kubernetes/client/examples/PortForwardExample.java
  examples/pom.xml
  pom.xml
Labels: approved, cncf-cla: yes, lgtm, size/L

#1445 Workaround for gson-syntax-exception upon deletion even if the deletion succeeds
  e2e/src/test/groovy/io/kubernetes/client/e2e/basic/CoreV1ApiTest.groovy
  kubernetes/src/main/java/io/kubernetes/client/gson/V1StatusPreProcessor.java
  kubernetes/src/main/java/io/kubernetes/client/openapi/JSON.java
  kubernetes/src/test/java/io/kubernetes/client/gson/V1StatusJsonDeserializerTest.java
Labels: approved, cncf-cla: yes, lgtm, size/L

#1450 Add path normalization for archive files.
  pom.xml
  util/pom.xml
  util/src/main/java/io/kubernetes/client/Copy.java
Labels: approved, cncf-cla: yes, lgtm, size/S

#1452 Release 10.0.1
  client-java-contrib/cert-manager/pom.xml
  client-java-contrib/prometheus-operator/pom.xml
  e2e/pom.xml
  examples/pom.xml
  extended/pom.xml
  kubernetes/pom.xml
  pom.xml
  proto/pom.xml
  spring/pom.xml
  util/pom.xml
Labels: approved, cncf-cla: yes, lgtm, size/S

#1460 Leader to give up leadership lock on graceful shutdown
  extended/src/main/java/io/kubernetes/client/extended/leaderelection/LeaderElector.java
  extended/src/main/java/io/kubernetes/client/extended/leaderelection/resourcelock/ConfigMapLock.java
  extended/src/main/java/io/kubernetes/client/extended/leaderelection/resourcelock/EndpointsLock.java
  extended/src/test/java/io/kubernetes/client/extended/controller/LeaderElectingControllerTest.java
  extended/src/test/java/io/kubernetes/client/extended/leaderelection/LeaderElectionTest.java
  extended/src/test/java/io/kubernetes/client/extended/leaderelection/LeaderElectorTest.java
  extended/src/test/java/io/kubernetes/client/extended/leaderelection/LockSmith.java
Labels: approved, cncf-cla: yes, lgtm, size/L
