Repository kubernetes-client/java, pull requests merged in 2020-04, with the labels that each got.

#901 Require Kubernetes API type for event-filter annotation
  spring/src/main/java/io/kubernetes/client/spring/extended/controller/KubernetesReconcilerProcessor.java
  spring/src/main/java/io/kubernetes/client/spring/extended/controller/annotation/AddWatchEventFilter.java
  spring/src/main/java/io/kubernetes/client/spring/extended/controller/annotation/DeleteWatchEventFilter.java
  spring/src/main/java/io/kubernetes/client/spring/extended/controller/annotation/KubernetesReconciler.java
  spring/src/main/java/io/kubernetes/client/spring/extended/controller/annotation/KubernetesReconcilerWorkerCount.java
  spring/src/main/java/io/kubernetes/client/spring/extended/controller/annotation/UpdateWatchEventFilter.java
  spring/src/test/java/io/kubernetes/client/spring/extended/controller/KubernetesReconcilerCreatorTest.java
Labels: approved, cncf-cla: yes, lgtm, size/L

#913 Setup GH action CI flow
  .github/workflows/maven.yml
Labels: approved, cncf-cla: yes, lgtm, size/S

#916 Fixes unit-test CI failure
  spring/src/main/java/io/kubernetes/client/spring/extended/controller/KubernetesReconcilerProcessor.java
Labels: approved, cncf-cla: yes, lgtm, size/XS

#911 Issue:#845, added 'null' string check to allow to pass null values in…
  util/src/main/java/io/kubernetes/client/util/Yaml.java
Labels: approved, cncf-cla: yes, lgtm, size/XS

#900 Feat: Implementing resizable/error exec stream
  util/src/main/java/io/kubernetes/client/Exec.java
Labels: approved, cncf-cla: yes, lgtm, size/S
