Repository kubernetes-client/java, pull requests merged in 2020-06, with the labels that each got.

#960 Defaulting okhttp client protocols to HTTP1.1
  util/src/main/java/io/kubernetes/client/util/ClientBuilder.java
Labels: approved, cncf-cla: yes, lgtm, size/S

#970 Generic kubernetes client example
  README.md
  examples/src/main/java/io/kubernetes/client/examples/GenericClientExample.java
  extended/src/main/java/io/kubernetes/client/extended/generic/GenericKubernetesApi.java
Labels: approved, cncf-cla: yes, lgtm, size/S

#967 reload service account token after expiry
  examples/src/main/java/io/kubernetes/client/examples/InClusterClientExample.java
  util/src/main/java/io/kubernetes/client/util/ClientBuilder.java
  util/src/main/java/io/kubernetes/client/util/credentials/TokenFileAuthentication.java
  util/src/test/java/io/kubernetes/client/util/credentials/TokenFileAuthenticationTest.java
  util/src/test/resources/token1
  util/src/test/resources/token2
Labels: approved, cncf-cla: yes, lgtm, size/L

#972 Update GenericKubernetesApi.java
  extended/src/main/java/io/kubernetes/client/extended/generic/GenericKubernetesApi.java
Labels: approved, cncf-cla: yes, lgtm, size/XS

#975 Chore: Pom clean up and merges properties/versions definitions to parent pom
  examples/pom.xml
  extended/pom.xml
  pom.xml
  proto/pom.xml
  spring/pom.xml
  util/pom.xml
Labels: approved, cncf-cla: yes, lgtm, size/L

#974 Adding a check to test if Tar utility is present in the target container
  examples/src/main/java/io/kubernetes/client/examples/CopyExample.java
  util/src/main/java/io/kubernetes/client/Copy.java
  util/src/main/java/io/kubernetes/client/util/exception/CopyNotSupportedException.java
Labels: approved, cncf-cla: yes, lgtm, size/M, tide/merge-method-squash

#979 Chore: Enhances ReflectorRunner error log
  util/src/main/java/io/kubernetes/client/informer/cache/ReflectorRunnable.java
Labels: approved, cncf-cla: yes, lgtm, size/XS

#981 Revise CRD generation guides: uses generator script instead of running images
  docs/generate-model-from-third-party-resources.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#983 add dependabot.yml for dependency management
  .github/dependabot.yml
Labels: approved, cncf-cla: yes, lgtm, size/S

#980 Chore: Docs java highlights
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1001 Applies common object interfaces to utils
  extended/src/main/java/io/kubernetes/client/extended/controller/ControllerWatch.java
  extended/src/main/java/io/kubernetes/client/extended/controller/Controllers.java
  extended/src/main/java/io/kubernetes/client/extended/controller/DefaultControllerWatch.java
  extended/src/main/java/io/kubernetes/client/extended/controller/builder/ControllerBuilder.java
  extended/src/main/java/io/kubernetes/client/extended/controller/builder/ControllerWatchBuilder.java
  extended/src/main/java/io/kubernetes/client/extended/controller/builder/DefaultControllerBuilder.java
  extended/src/main/java/io/kubernetes/client/extended/generic/GenericKubernetesApi.java
  extended/src/test/java/io/kubernetes/client/extended/generic/FooCustomResource.java
  extended/src/test/java/io/kubernetes/client/extended/generic/FooCustomResourceList.java
  spring/src/main/java/io/kubernetes/client/spring/extended/controller/KubernetesInformerFactoryProcessor.java
  spring/src/main/java/io/kubernetes/client/spring/extended/controller/annotation/AddWatchEventFilter.java
  spring/src/main/java/io/kubernetes/client/spring/extended/controller/annotation/DeleteWatchEventFilter.java
  spring/src/main/java/io/kubernetes/client/spring/extended/controller/annotation/KubernetesInformer.java
  spring/src/main/java/io/kubernetes/client/spring/extended/controller/annotation/KubernetesReconcilerWatch.java
  util/src/main/java/io/kubernetes/client/informer/ListerWatcher.java
  util/src/main/java/io/kubernetes/client/informer/ResourceEventHandler.java
  util/src/main/java/io/kubernetes/client/informer/ResyncRunnable.java
  util/src/main/java/io/kubernetes/client/informer/SharedIndexInformer.java
  util/src/main/java/io/kubernetes/client/informer/SharedInformer.java
  util/src/main/java/io/kubernetes/client/informer/SharedInformerFactory.java
  util/src/main/java/io/kubernetes/client/informer/cache/Cache.java
  util/src/main/java/io/kubernetes/client/informer/cache/Controller.java
  util/src/main/java/io/kubernetes/client/informer/cache/DeltaFIFO.java
  util/src/main/java/io/kubernetes/client/informer/cache/Lister.java
  util/src/main/java/io/kubernetes/client/informer/cache/ProcessorListener.java
  util/src/main/java/io/kubernetes/client/informer/cache/ReflectorRunnable.java
  util/src/main/java/io/kubernetes/client/informer/cache/SharedProcessor.java
  util/src/main/java/io/kubernetes/client/informer/impl/DefaultSharedIndexInformer.java
  util/src/test/java/io/kubernetes/client/informer/cache/CacheTest.java
  util/src/test/java/io/kubernetes/client/informer/cache/MockRunOnceListerWatcher.java
  util/src/test/java/io/kubernetes/client/informer/cache/SharedProcessorTest.java
Labels: approved, cncf-cla: yes, lgtm, size/L

#1013 Revises leader election example for clarification
  examples/src/main/java/io/kubernetes/client/examples/LeaderElectionExample.java
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1014 Clarifying requirement for extended module in the example list
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1015 Switch to kubernetes object common interfaces for informers
  util/src/main/java/io/kubernetes/client/informer/ResyncRunnable.java
  util/src/main/java/io/kubernetes/client/informer/cache/Cache.java
  util/src/main/java/io/kubernetes/client/informer/cache/Caches.java
  util/src/main/java/io/kubernetes/client/informer/cache/Controller.java
  util/src/main/java/io/kubernetes/client/informer/cache/DeltaFIFO.java
  util/src/main/java/io/kubernetes/client/informer/cache/Lister.java
  util/src/main/java/io/kubernetes/client/informer/cache/ReflectorRunnable.java
  util/src/main/java/io/kubernetes/client/informer/exception/BadObjectException.java
  util/src/main/java/io/kubernetes/client/informer/exception/BuildInformerException.java
  util/src/main/java/io/kubernetes/client/informer/impl/DefaultSharedIndexInformer.java
  util/src/main/java/io/kubernetes/client/util/ListAccessor.java
  util/src/main/java/io/kubernetes/client/util/ObjectAccessor.java
  util/src/test/java/io/kubernetes/client/informer/cache/ControllerTest.java
  util/src/test/java/io/kubernetes/client/informer/cache/DeltaFIFOTest.java
  util/src/test/java/io/kubernetes/client/informer/cache/ReflectorRunnableTest.java
Labels: approved, cncf-cla: yes, lgtm, size/L

#1020 Doc: Note CRD models can be written manually as alternative
  docs/generate-model-from-third-party-resources.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1021 Apply kubernetes common interface to more extended utilities
  extended/src/main/java/io/kubernetes/client/extended/controller/Controllers.java
  extended/src/main/java/io/kubernetes/client/extended/event/legacy/EventRecorder.java
  extended/src/main/java/io/kubernetes/client/extended/event/legacy/ObjectReferenceResolvingEventRecorder.java
  extended/src/main/java/io/kubernetes/client/extended/generic/GenericKubernetesApi.java
  extended/src/main/java/io/kubernetes/client/extended/generic/KubernetesApiResponse.java
  extended/src/main/java/io/kubernetes/client/extended/pager/Pager.java
  util/src/main/java/io/kubernetes/client/informer/cache/Caches.java
  util/src/main/java/io/kubernetes/client/informer/cache/ReflectorRunnable.java
Labels: approved, cncf-cla: yes, lgtm, size/L
