Repository kubernetes-client/java, pull requests merged in 2021-06, with the labels that each got.

#1733 Update to the latest sundr generator.
  .github/workflows/maven.yml
  extended/src/main/java/io/kubernetes/client/extended/event/legacy/EventAggregator.java
  pom.xml
  util/src/main/java/io/kubernetes/client/util/labels/LabelSelector.java
  util/src/test/java/io/kubernetes/client/util/labels/LabelSelectorTest.java
Labels: approved, cncf-cla: yes, lgtm, size/M

#1744 Revise the way we cache maven builds to include the java version, and get rid of restore-keys
  .github/workflows/maven.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1742 Cherry-pick of #1631 into Release-12
  extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlPatch.java
Labels: approved, cncf-cla: yes, lgtm, size/S

#1743 Cherry-pick of #1631 into Release-11
  extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlPatch.java
Labels: approved, cncf-cla: yes, lgtm, size/S

#1766 Fix a test that was broken on some systems.
  util/src/test/java/io/kubernetes/client/util/ClientBuilderTest.java
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1769 Chore: Trimming pom files for fluent modules
  fluent-gen/pom.xml
  fluent/pom.xml
  pom.xml
Labels: approved, cncf-cla: yes, lgtm, size/L
