Repository kubernetes-client/java, pull requests merged in 2021-11, with the labels that each got.

#1965 Release 12.0.2
  client-java-contrib/cert-manager/pom.xml
  client-java-contrib/prometheus-operator/pom.xml
  e2e/pom.xml
  examples/examples-release-10/pom.xml
  examples/examples-release-11/pom.xml
  examples/examples-release-12/pom.xml
  examples/pom.xml
  extended/pom.xml
  kubernetes/pom.xml
  pom.xml
  proto/pom.xml
  spring/pom.xml
  util/pom.xml
Labels: cncf-cla: yes, size/M, approved, lgtm

#1964 Release 11.0.3
  client-java-contrib/cert-manager/pom.xml
  client-java-contrib/prometheus-operator/pom.xml
  e2e/pom.xml
  examples/pom.xml
  extended/pom.xml
  kubernetes/pom.xml
  pom.xml
  proto/pom.xml
  spring/pom.xml
  util/pom.xml
Labels: cncf-cla: yes, size/S, approved, lgtm

#1976 Release 14
  client-java-contrib/admissionreview/pom.xml
  client-java-contrib/cert-manager/pom.xml
  client-java-contrib/prometheus-operator/pom.xml
  e2e/pom.xml
  examples/examples-release-10/pom.xml
  examples/examples-release-11/pom.xml
  examples/examples-release-12/pom.xml
  examples/examples-release-13/pom.xml
  examples/pom.xml
  extended/pom.xml
  fluent/pom.xml
  kubernetes/pom.xml
  pom.xml
  proto/pom.xml
  spring/pom.xml
  util/pom.xml
Labels: cncf-cla: yes, size/M, approved, lgtm

#1977 Adding release note for release-14
  CHANGELOG.md
Labels: cncf-cla: yes, size/S, approved, lgtm

#1979 Fix formatting
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: cncf-cla: yes, size/XS, approved, lgtm

#1973 Update kubectl-equivalence-in-java.md
  docs/kubectl-equivalence-in-java.md
Labels: cncf-cla: yes, size/S, approved, lgtm

#1983 #1802 Check if server is available from kubeconfig.
  util/src/main/java/io/kubernetes/client/util/ClientBuilder.java
  util/src/test/java/io/kubernetes/client/util/ClientBuilderTest.java
Labels: cncf-cla: yes, size/S, approved, lgtm

#1999 Reduce the java matrix to just LTS versions.
  .github/workflows/maven.yml
Labels: cncf-cla: yes, size/XS, approved, lgtm

#1980 chore: 'adopt' --> 'temurin'
  .github/workflows/maven.yml
Labels: cncf-cla: yes, size/XS, approved, lgtm

#1992 Add exception handler to SharedInformerFactory
  util/src/main/java/io/kubernetes/client/informer/SharedInformerFactory.java
  util/src/main/java/io/kubernetes/client/informer/cache/Controller.java
  util/src/main/java/io/kubernetes/client/informer/cache/ReflectorRunnable.java
  util/src/main/java/io/kubernetes/client/informer/impl/DefaultSharedIndexInformer.java
  util/src/test/java/io/kubernetes/client/informer/cache/ControllerTest.java
  util/src/test/java/io/kubernetes/client/informer/cache/ReflectorRunnableTest.java
  util/src/test/java/io/kubernetes/client/informer/impl/DefaultSharedIndexInformerTest.java
  util/src/test/java/io/kubernetes/client/informer/impl/DefaultSharedIndexInformerWireMockTest.java
Labels: cncf-cla: yes, approved, size/XL, lgtm

#2000 Add Windows to our build matrix.
  .github/workflows/maven.yml
  extended/pom.xml
  extended/src/main/java/io/kubernetes/client/extended/workqueue/DefaultDelayingQueue.java
  extended/src/test/java/io/kubernetes/client/extended/kubectl/KubectlApplyTest.java
  extended/src/test/java/io/kubernetes/client/extended/kubectl/KubectlCreateTest.java
  extended/src/test/java/io/kubernetes/client/extended/kubectl/KubectlDrainTest.java
  extended/src/test/java/io/kubernetes/client/extended/kubectl/KubectlPatchTest.java
  extended/src/test/java/io/kubernetes/client/extended/kubectl/KubectlRolloutTest.java
  extended/src/test/java/io/kubernetes/client/extended/kubectl/util/deployment/DeploymentHelperTest.java
  extended/src/test/java/io/kubernetes/client/extended/pager/PagerTest.java
  extended/src/test/java/io/kubernetes/client/extended/workqueue/DefaultDelayingQueueTest.java
  spring/pom.xml
  spring/src/main/java/io/kubernetes/client/spring/extended/manifests/KubernetesFromYamlProcessor.java
  util/pom.xml
  util/src/main/java/io/kubernetes/client/Copy.java
  util/src/main/java/io/kubernetes/client/util/ClientBuilder.java
  util/src/test/java/io/kubernetes/client/util/ClientBuilderTest.java
  util/src/test/java/io/kubernetes/client/util/ConfigTest.java
  util/src/test/java/io/kubernetes/client/util/KubeConfigTest.java
  util/src/test/java/io/kubernetes/client/util/SSLUtilsTest.java
  util/src/test/java/io/kubernetes/client/util/YamlTest.java
  util/src/test/java/io/kubernetes/client/util/credentials/ClientCertificateAuthenticationTest.java
  util/src/test/java/io/kubernetes/client/util/credentials/TokenFileAuthenticationTest.java
  util/src/test/java/io/kubernetes/client/util/generic/dynamic/DynamicsTest.java
Labels: size/L, cncf-cla: yes, approved, lgtm
