Repository kubernetes-client/java, pull requests merged in 2021-07, with the labels that each got.

#1774 Add AdmissionReview models.
  client-java-contrib/admissionreview/admission-swagger-1.20.4.json
  client-java-contrib/admissionreview/generate.sh
  client-java-contrib/admissionreview/pom.xml
  client-java-contrib/admissionreview/src/main/java/io/kubernetes/client/admissionreview/models/AdmissionRequest.java
  client-java-contrib/admissionreview/src/main/java/io/kubernetes/client/admissionreview/models/AdmissionResponse.java
  client-java-contrib/admissionreview/src/main/java/io/kubernetes/client/admissionreview/models/AdmissionReview.java
  client-java-contrib/admissionreview/src/main/java/io/kubernetes/client/admissionreview/models/GroupVersionKind.java
  client-java-contrib/admissionreview/src/main/java/io/kubernetes/client/admissionreview/models/GroupVersionResource.java
  client-java-contrib/admissionreview/src/main/java/io/kubernetes/client/admissionreview/models/ListMeta.java
  client-java-contrib/admissionreview/src/main/java/io/kubernetes/client/admissionreview/models/Status.java
  client-java-contrib/admissionreview/src/main/java/io/kubernetes/client/admissionreview/models/StatusCause.java
  client-java-contrib/admissionreview/src/main/java/io/kubernetes/client/admissionreview/models/StatusDetails.java
  client-java-contrib/admissionreview/src/main/java/io/kubernetes/client/admissionreview/models/UserInfo.java
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#1782 Flake: Reduce controller-test flakiness via awaitility
  util/src/test/java/io/kubernetes/client/informer/cache/ControllerTest.java
Labels: approved, cncf-cla: yes, lgtm, size/S

#1784 Release 13.0.0
  client-java-contrib/admissionreview/pom.xml
  client-java-contrib/cert-manager/pom.xml
  client-java-contrib/prometheus-operator/pom.xml
  e2e/pom.xml
  examples/examples-release-10/pom.xml
  examples/examples-release-11/pom.xml
  examples/examples-release-12/pom.xml
  examples/examples-release-13/pom.xml
  examples/pom.xml
  extended/pom.xml
  fluent/pom.xml
  kubernetes/pom.xml
  pom.xml
  proto/pom.xml
  spring/pom.xml
  util/pom.xml
Labels: approved, cncf-cla: yes, lgtm, size/M

#1789 Flake: Reduce controller-test flakiness via changing popProcessFunc
  util/src/test/java/io/kubernetes/client/informer/cache/ControllerTest.java
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1783 Feat: Adding a retry util in case of failing updates due to stale RV
  util/src/main/java/io/kubernetes/client/util/ApiInvocation.java
  util/src/main/java/io/kubernetes/client/util/RetryUtils.java
  util/src/test/java/io/kubernetes/client/util/RetryUtilsTest.java
Labels: approved, cncf-cla: yes, lgtm, size/L

#1793 Reduce controller test flakiness by distinguishing resource-versions
  util/src/test/java/io/kubernetes/client/informer/cache/ControllerTest.java
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1795 remove Thread.sleep in ProcessorListenerTest.java
  util/src/test/java/io/kubernetes/client/informer/cache/ProcessorListenerTest.java
Labels: approved, cncf-cla: yes, lgtm, size/S

#1805 Chore: Warn if no kubernetes api models were loaded
  util/src/main/java/io/kubernetes/client/util/ModelMapper.java
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1804 Bugfix: CRD's openapi schema extension cannot be properly serialized
  util/src/main/java/io/kubernetes/client/util/Yaml.java
  util/src/test/java/io/kubernetes/client/util/YamlTest.java
  util/src/test/resources/crd-int-or-string.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#1807 Release note for 13.0.0
  CHANGELOG.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#1808 Adding a constructor which accepts custom dumper/loader options
  util/src/main/java/io/kubernetes/client/util/Yaml.java
Labels: approved, cncf-cla: yes, lgtm, size/S

#1809 Fix/scale for stateful sets
  extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlScale.java
  extended/src/test/java/io/kubernetes/client/extended/kubectl/KubectlScaleTest.java
Labels: approved, cncf-cla: yes, lgtm, size/M
