Repository kubernetes-client/java, pull requests merged in 2021-01, with the labels that each got.

#1463 leaderelection sanity e2e integration tests
  e2e/pom.xml
  e2e/src/test/java/io/kubernetes/client/e2e/extended/leaderelection/LeaderElectorTest.java
  extended/src/main/java/io/kubernetes/client/extended/leaderelection/LeaderElector.java
  extended/src/main/java/io/kubernetes/client/extended/leaderelection/resourcelock/LeaseLock.java
Labels: approved, cncf-cla: yes, lgtm, size/L

#1465 Swap javadoc for filter annotations
  spring/src/main/java/io/kubernetes/client/spring/extended/controller/annotation/DeleteWatchEventFilter.java
  spring/src/main/java/io/kubernetes/client/spring/extended/controller/annotation/UpdateWatchEventFilter.java
Labels: approved, cncf-cla: yes, lgtm, size/S

#1468 first commit
  util/src/main/java/io/kubernetes/client/apimachinery/GroupVersion.java
  util/src/main/java/io/kubernetes/client/util/Preconditions.java
  util/src/main/java/io/kubernetes/client/util/Strings.java
  util/src/test/java/io/kubernetes/client/apimachinery/GroupVersionTest.java
  util/src/test/java/io/kubernetes/client/util/PreconditionsTest.java
Labels: approved, cncf-cla: yes, lgtm, size/L

#1467 clean-up, fix a bug, tests
  util/src/main/java/io/kubernetes/client/informer/ResyncRunnable.java
  util/src/test/java/io/kubernetes/client/informer/ResyncRunnableTest.java
Labels: approved, cncf-cla: yes, lgtm, size/M

#1466 minor improvement
  util/src/main/java/io/kubernetes/client/informer/EventType.java
  util/src/main/java/io/kubernetes/client/informer/cache/ReflectorRunnable.java
Labels: approved, cncf-cla: yes, lgtm, size/M

#1470 Add updateStatus() convenience methods to GenericKubernetesApi
  util/src/main/java/io/kubernetes/client/util/generic/GenericKubernetesApi.java
  util/src/test/java/io/kubernetes/client/util/generic/GenericKubernetesApiTest.java
Labels: approved, cncf-cla: yes, lgtm, size/L

#1473 Add documentation for the FAQ
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1477 Support rfc3339 micro-sec (6 digit) timestamp
  e2e/src/test/java/io/kubernetes/client/e2e/extended/leaderelection/LeaderElectorTest.java
  extended/src/main/java/io/kubernetes/client/extended/leaderelection/resourcelock/LeaseLock.java
  kubernetes/src/main/java/io/kubernetes/client/openapi/JSON.java
  kubernetes/src/test/java/io/kubernetes/client/openapi/JSONTest.java
Labels: approved, cncf-cla: yes, lgtm, size/L

#1478 Fixes leader-election unit-test flakiness
  extended/src/test/java/io/kubernetes/client/extended/leaderelection/LeaderElectorTest.java
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1474 Fix examples so they compile and tests are green
  .github/workflows/maven.yml
  examples/examples-release-11/pom.xml
  examples/examples-release-12/pom.xml
  examples/pom.xml
Labels: approved, cncf-cla: yes, lgtm, size/M

#1490 use Preconditions::precondition + add tests
  util/src/main/java/io/kubernetes/client/apimachinery/GroupVersionKind.java
  util/src/main/java/io/kubernetes/client/apimachinery/GroupVersionResource.java
  util/src/main/java/io/kubernetes/client/apimachinery/NamespaceName.java
  util/src/test/java/io/kubernetes/client/apimachinery/GroupVersionKindTest.java
  util/src/test/java/io/kubernetes/client/apimachinery/GroupVersionResourceTest.java
  util/src/test/java/io/kubernetes/client/apimachinery/GroupVersionTest.java
  util/src/test/java/io/kubernetes/client/apimachinery/NamespaceNameTest.java
Labels: approved, cncf-cla: yes, lgtm, size/L

#1498 Update client builder to be more robust by default
  util/src/main/java/io/kubernetes/client/util/ClientBuilder.java
Labels: approved, cncf-cla: yes, lgtm, size/M

#1504 Fallback to BKS when JKS is not available
  util/src/main/java/io/kubernetes/client/util/SSLUtils.java
Labels: approved, cncf-cla: yes, lgtm, size/S
