Repository kubernetes-client/java, pull requests merged in 2021-10, with the labels that each got.

#1905 Cherrypick-13: Bugfix: stale watch event should be handled properly
  util/src/main/java/io/kubernetes/client/informer/cache/ReflectorRunnable.java
  util/src/main/java/io/kubernetes/client/informer/exception/WatchExpiredException.java
  util/src/test/java/io/kubernetes/client/informer/cache/ReflectorRunnableTest.java
Labels: cncf-cla: yes, size/M, approved, lgtm

#1908 Cherrypick-13: Passing list-options in generic api based informers
  util/src/main/java/io/kubernetes/client/informer/SharedInformerFactory.java
Labels: cncf-cla: yes, size/S, approved, lgtm

#1919 CRD-Gen: Pin gen commit and bump 1.0.6
  client-java-contrib/Dockerfile
  client-java-contrib/admissionreview/generate.sh
  client-java-contrib/cert-manager/update.sh
  client-java-contrib/prometheus-operator/update.sh
  client-java-contrib/publish-gen-image.sh
  docs/generate-model-from-third-party-resources.md
Labels: cncf-cla: yes, size/S, approved, lgtm

#1920 Flake: Catching illegal-state-exception in the copy test
  util/src/test/java/io/kubernetes/client/CopyTest.java
Labels: cncf-cla: yes, size/XS, approved, lgtm

#1931 Release 13.0.1
  client-java-contrib/admissionreview/pom.xml
  client-java-contrib/cert-manager/pom.xml
  client-java-contrib/prometheus-operator/pom.xml
  e2e/pom.xml
  examples/examples-release-10/pom.xml
  examples/examples-release-11/pom.xml
  examples/examples-release-12/pom.xml
  examples/examples-release-13/pom.xml
  examples/pom.xml
  extended/pom.xml
  fluent/pom.xml
  kubernetes/pom.xml
  pom.xml
  proto/pom.xml
  spring/pom.xml
  util/pom.xml
Labels: cncf-cla: yes, size/M, approved, lgtm

#1938 Chore: Adding release notes for 13.0.1
  CHANGELOG.md
Labels: cncf-cla: yes, size/XS, approved, lgtm
