Repository kubernetes-client/java, pull requests merged in 2021-08, with the labels that each got.

#1812 feat : add a selector util for tranforming V1LabelSelector to LabelSelector
  util/src/main/java/io/kubernetes/client/util/labels/LabelSelector.java
  util/src/test/java/io/kubernetes/client/util/labels/LabelSelectorTest.java
Labels: approved, cncf-cla: yes, lgtm, size/L

#1813 Feat/kubectl deployment util
  extended/src/main/java/io/kubernetes/client/extended/kubectl/util/deployment/DeploymentHelper.java
  extended/src/test/java/io/kubernetes/client/extended/kubectl/util/deployment/DeploymentHelperTest.java
  extended/src/test/resources/deployment.json
  extended/src/test/resources/replicaset-list.json
Labels: cncf-cla: yes, size/XXL, approved, lgtm

#1810 support gcp authentication refresh token
  util/src/main/java/io/kubernetes/client/util/authenticators/GCPAuthenticator.java
  util/src/test/java/io/kubernetes/client/util/KubeConfigTest.java
  util/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
Labels: cncf-cla: yes, size/M, approved, lgtm

#1814 Feat/kubectl rollout history deployment
  extended/src/main/java/io/kubernetes/client/extended/kubectl/Kubectl.java
  extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlRolloutHistory.java
  extended/src/test/java/io/kubernetes/client/extended/kubectl/KubectlRolloutHistoryTest.java
Labels: size/L, cncf-cla: yes, approved, lgtm

#1823 Optimize DeltaFIFO.combineDeltas
  util/src/main/java/io/kubernetes/client/informer/cache/DeltaFIFO.java
Labels: cncf-cla: yes, size/S, approved, lgtm

#1824 Fix GCPAuthenticator to compose a correct command
  util/src/main/java/io/kubernetes/client/util/authenticators/GCPAuthenticator.java
  util/src/test/java/io/kubernetes/client/util/authenticators/GCPAuthenticatorTest.java
Labels: size/L, cncf-cla: yes, approved, lgtm

#1817 Additional debugging option for printing http2 frames
  util/src/main/java/io/kubernetes/client/util/okhttp/HTTP2ConsoleHandler.java
  util/src/main/java/io/kubernetes/client/util/okhttp/HTTP2Logging.java
Labels: cncf-cla: yes, size/M, approved, lgtm

#1832 Bugfix: Stale watch event should be handled properly
  util/src/main/java/io/kubernetes/client/informer/cache/ReflectorRunnable.java
  util/src/main/java/io/kubernetes/client/informer/exception/WatchExpiredException.java
  util/src/test/java/io/kubernetes/client/informer/cache/ReflectorRunnableTest.java
Labels: cncf-cla: yes, size/M, approved, lgtm

#1833 Chore: Reformat comments
  util/src/main/java/io/kubernetes/client/informer/cache/ReflectorRunnable.java
Labels: cncf-cla: yes, size/S, approved, lgtm

#1849 Kill the sleep in AttachTest
  util/src/test/java/io/kubernetes/client/AttachTest.java
Labels: cncf-cla: yes, size/S, approved, lgtm

#1835 Updated WebSocketStreamHandler.write() to calculate 'remaining' bytes properly : Fixed destPath normalization for potential Windows delimiters
  util/src/main/java/io/kubernetes/client/Copy.java
  util/src/main/java/io/kubernetes/client/util/WebSocketStreamHandler.java
  util/src/test/java/io/kubernetes/client/CopyTest.java
Labels: cncf-cla: yes, size/S, approved, lgtm

#1818 Feat/kubectl rollout history daemonset
  extended/src/main/java/io/kubernetes/client/extended/kubectl/History.java
  extended/src/main/java/io/kubernetes/client/extended/kubectl/Kubectl.java
  extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlRollout.java
  extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlRolloutHistory.java
  extended/src/main/java/io/kubernetes/client/extended/kubectl/PatchHelper.java
  extended/src/test/java/io/kubernetes/client/extended/kubectl/KubectlRolloutHistoryTest.java
  extended/src/test/java/io/kubernetes/client/extended/kubectl/KubectlRolloutTest.java
  extended/src/test/resources/daemonset-controllerrevision-list.json
  extended/src/test/resources/daemonset.json
  extended/src/test/resources/patched-daemonset.json
Labels: cncf-cla: yes, size/XXL, approved, lgtm

#1850 Test: Adding an e2e play script that exercises kubectl rollout daemonset/deployment/statefulset
  e2e/src/test/groovy/io/kubernetes/client/e2e/kubectl/KubectlRolloutTest.groovy
  e2e/src/test/resources/test-daemonset-updated.yaml
  e2e/src/test/resources/test-daemonset.yaml
  e2e/src/test/resources/test-deployment-updated.yaml
  e2e/src/test/resources/test-deployment.yaml
  e2e/src/test/resources/test-statefulset-updated.yaml
  e2e/src/test/resources/test-statefulset.yaml
Labels: size/L, cncf-cla: yes, approved, lgtm

#1861 Chore: Sort list-watcher exception catch flow
  util/src/main/java/io/kubernetes/client/informer/cache/ReflectorRunnable.java
Labels: cncf-cla: yes, size/XS, approved, lgtm

#1852 Bugfix: Passing list-options in generic api based informers
  util/src/main/java/io/kubernetes/client/informer/SharedInformerFactory.java
Labels: cncf-cla: yes, size/S, approved, lgtm

#1863 Bugfix: Move Pager's concurrently read fields to nested class
  extended/src/main/java/io/kubernetes/client/extended/pager/Pager.java
Labels: cncf-cla: yes, size/S, approved, lgtm

#1864 Chore: Bump crd-model-gen image to v1.0.4
  client-java-contrib/admissionreview/generate.sh
  client-java-contrib/cert-manager/update.sh
  client-java-contrib/prometheus-operator/update.sh
  client-java-contrib/publish-gen-image.sh
  docs/generate-model-from-third-party-resources.md
Labels: cncf-cla: yes, size/S, approved, lgtm
