Repository kubernetes-client/java, pull requests merged in 2021-05, with the labels that each got.

#1685 Added explicit runtime dependency for logback
  examples/examples-release-12/pom.xml
  examples/examples-release-13/pom.xml
Labels: approved, cncf-cla: yes, lgtm, size/S

#1686 Fix SpringExampleController so it doesn't crash on startup
  examples/examples-release-12/src/main/java/io/kubernetes/client/examples/SpringControllerExample.java
  examples/examples-release-13/src/main/java/io/kubernetes/client/examples/SpringControllerExample.java
Labels: approved, cncf-cla: yes, lgtm, size/S

#1676 Update the CustomConstructor class for SnakeYAML.
  util/src/main/java/io/kubernetes/client/util/Yaml.java
  util/src/test/java/io/kubernetes/client/util/TestPoJ.java
  util/src/test/java/io/kubernetes/client/util/YamlTest.java
  util/src/test/resources/pod-tag.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#1692 Cherry-pick 11: Update the CustomConstructor class for SnakeYAML
  util/src/main/java/io/kubernetes/client/util/Yaml.java
  util/src/test/java/io/kubernetes/client/util/TestPoJ.java
  util/src/test/java/io/kubernetes/client/util/YamlTest.java
  util/src/test/resources/pod-tag.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#1691 Cherry-pick 12: Update the CustomConstructor class for SnakeYAML
  util/src/main/java/io/kubernetes/client/util/Yaml.java
  util/src/test/java/io/kubernetes/client/util/TestPoJ.java
  util/src/test/java/io/kubernetes/client/util/YamlTest.java
  util/src/test/resources/pod-tag.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#1688 Tidy up SpringBootTests
  spring/src/test/java/io/kubernetes/client/spring/extended/controller/KubernetesInformerCreatorTest.java
  spring/src/test/java/io/kubernetes/client/spring/extended/manifests/KubernetesFromConfigMapTest.java
  spring/src/test/java/io/kubernetes/client/spring/extended/manifests/KubernetesFromYamlTest.java
  spring/src/test/java/io/kubernetes/client/spring/extended/manifests/KubernetesManifestTest.java
  spring/src/test/java/io/kubernetes/client/spring/extended/network/KubernetesEndpointsLoadBalancerCreatorTest.java
  spring/src/test/java/io/kubernetes/client/spring/extended/network/TestApplication.java
Labels: approved, cncf-cla: yes, lgtm, size/L

#1699 Switching JUnit system-rules dependency to system-lambda
  extended/pom.xml
  pom.xml
  util/pom.xml
  util/src/test/java/io/kubernetes/client/informer/cache/CacheTest.java
  util/src/test/java/io/kubernetes/client/informer/cache/ControllerTest.java
  util/src/test/java/io/kubernetes/client/informer/cache/DeltaFIFOTest.java
  util/src/test/java/io/kubernetes/client/informer/cache/ListerTest.java
  util/src/test/java/io/kubernetes/client/informer/cache/ProcessorListenerTest.java
  util/src/test/java/io/kubernetes/client/informer/cache/ReflectorRunnableTest.java
  util/src/test/java/io/kubernetes/client/informer/cache/SharedProcessorTest.java
  util/src/test/java/io/kubernetes/client/util/ClientBuilderTest.java
  util/src/test/java/io/kubernetes/client/util/ConfigTest.java
Labels: approved, cncf-cla: yes, lgtm, size/L

#1705 Github action: Triggering testing jobs for release-** branch
  .github/workflows/maven.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1703 Cherry pick 12: Java 16 compatibility pt1: Reducing inaccessibility impact
  spring/src/main/java/io/kubernetes/client/spring/extended/manifests/KubernetesFromYamlProcessor.java
Labels: approved, cncf-cla: yes, lgtm, size/S

#1704 Cherry pick 11: Java 16 compatibility pt1: Reducing inaccessibility impact
  spring/src/main/java/io/kubernetes/client/spring/extended/manifests/KubernetesFromYamlProcessor.java
Labels: approved, cncf-cla: yes, lgtm, size/S

#1702 Java 16 compatibility pt1: Reducing inaccessibility impact
  spring/src/main/java/io/kubernetes/client/spring/extended/manifests/KubernetesFromConfigMapProcessor.java
  spring/src/main/java/io/kubernetes/client/spring/extended/manifests/KubernetesFromYamlProcessor.java
Labels: approved, cncf-cla: yes, lgtm, size/S

#1706 Cherry pick 11: GH action release branch testing
  .github/workflows/maven.yml
  extended/src/test/java/io/kubernetes/client/extended/event/legacy/EventLoggerTest.java
  spring/src/test/java/io/kubernetes/client/spring/extended/controller/KubernetesReconcilerProcessorTest.java
Labels: approved, cncf-cla: yes, lgtm, size/S

#1711 Release 12.0.1
  client-java-contrib/cert-manager/pom.xml
  client-java-contrib/prometheus-operator/pom.xml
  e2e/pom.xml
  examples/examples-release-10/pom.xml
  examples/examples-release-11/pom.xml
  examples/examples-release-12/pom.xml
  examples/pom.xml
  extended/pom.xml
  kubernetes/pom.xml
  pom.xml
  proto/pom.xml
  spring/pom.xml
  util/pom.xml
Labels: approved, cncf-cla: yes, lgtm, size/M

#1712 Release 11.0.2
  client-java-contrib/cert-manager/pom.xml
  client-java-contrib/prometheus-operator/pom.xml
  e2e/pom.xml
  examples/pom.xml
  extended/pom.xml
  kubernetes/pom.xml
  pom.xml
  proto/pom.xml
  spring/pom.xml
  util/pom.xml
Labels: approved, cncf-cla: yes, lgtm, size/S

#1687 Removes Kubernetes annotations from Spring integration
  examples/examples-release-13/src/main/java/io/kubernetes/client/examples/SpringControllerExample.java
  examples/examples-release-13/src/main/java/io/kubernetes/client/examples/SpringLoadBalancerExample.java
  spring/src/main/java/io/kubernetes/client/spring/extended/controller/KubernetesInformerFactoryProcessor.java
  spring/src/main/java/io/kubernetes/client/spring/extended/controller/KubernetesReconcilerProcessor.java
  spring/src/main/java/io/kubernetes/client/spring/extended/controller/annotation/AddWatchEventFilter.java
  spring/src/main/java/io/kubernetes/client/spring/extended/controller/annotation/DeleteWatchEventFilter.java
  spring/src/main/java/io/kubernetes/client/spring/extended/controller/annotation/GroupVersionResource.java
  spring/src/main/java/io/kubernetes/client/spring/extended/controller/annotation/KubernetesInformer.java
  spring/src/main/java/io/kubernetes/client/spring/extended/controller/annotation/KubernetesInformers.java
  spring/src/main/java/io/kubernetes/client/spring/extended/controller/annotation/KubernetesReconciler.java
  spring/src/main/java/io/kubernetes/client/spring/extended/controller/annotation/KubernetesReconcilerReadyFunc.java
  spring/src/main/java/io/kubernetes/client/spring/extended/controller/annotation/KubernetesReconcilerWatch.java
  spring/src/main/java/io/kubernetes/client/spring/extended/controller/annotation/UpdateWatchEventFilter.java
  spring/src/main/java/io/kubernetes/client/spring/extended/controller/factory/KubernetesControllerFactory.java
Labels: approved, cncf-cla: yes, lgtm, size/L

#1709 Cherry pick 12: GH action release branch testing
  .github/workflows/maven.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1718 Cherry pick 11: Bump bouncycastle.version from 1.66 to 1.68
  pom.xml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1669 Revise the Java versions we test to LTS + latest non-LTS version.
  .github/workflows/maven.yml
  spring/pom.xml
  util/pom.xml
  util/src/test/java/io/kubernetes/client/util/generic/GenericKubernetesApiTest.java
Labels: approved, cncf-cla: yes, lgtm, size/L

#1727 Fixes duplicated SharedProcessor#shouldResync calls
  util/src/main/java/io/kubernetes/client/informer/ResyncRunnable.java
  util/src/test/java/io/kubernetes/client/informer/ResyncRunnableTest.java
Labels: approved, cncf-cla: yes, lgtm, size/S
