Repository kubernetes-client/java, pull requests merged in 2021-09, with the labels that each got.

#1868 chore: rollout exception message
  e2e/pom.xml
  e2e/src/test/groovy/io/kubernetes/client/e2e/kubectl/KubectlRolloutTest.groovy
  extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlRollout.java
Labels: size/L, cncf-cla: yes, approved, lgtm

#1865 Kill some hard-coded sleep in tests
  util/src/test/java/io/kubernetes/client/CopyTest.java
  util/src/test/java/io/kubernetes/client/PortForwardTest.java
Labels: cncf-cla: yes, size/S, approved, lgtm

#1876 Test: Fixes constant maven download failure by escalating mvn permission
  .github/workflows/maven.yml
Labels: cncf-cla: yes, size/XS, approved, lgtm

#1874 update maven wrapper
  .mvn/wrapper/MavenWrapperDownloader.java
  .mvn/wrapper/maven-wrapper.jar
  .mvn/wrapper/maven-wrapper.properties
  mvnw
  mvnw.cmd
Labels: size/L, cncf-cla: yes, approved, lgtm

#1880 Tweak call for CoreV1 group properly
  extended/src/test/java/io/kubernetes/client/extended/kubectl/KubectlApplyTest.java
  util/src/main/java/io/kubernetes/client/util/generic/GenericKubernetesApi.java
  util/src/test/java/io/kubernetes/client/util/generic/GenericKubernetesApiForCoreApiTest.java
Labels: cncf-cla: yes, size/M, approved, lgtm

#1888 Return specific api type in patchContent and patchType
  extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlPatch.java
  extended/src/test/java/io/kubernetes/client/extended/kubectl/KubectlPatchTest.java
Labels: size/L, cncf-cla: yes, approved, lgtm

#1899 Fix arguments to dockerfiles
  client-java-contrib/Dockerfile.gen
  client-java-contrib/Dockerfile.gen-base
Labels: cncf-cla: yes, size/XS, approved, lgtm

#1894 Guard against NPE in manageRelationFromResourceToSubResources from Discovery class
  util/src/main/java/io/kubernetes/client/Discovery.java
Labels: cncf-cla: yes, size/XS, approved, lgtm

#1907 Cherrypick-13: Test: Fixes constant maven download failure by escalating mvn permission
  .github/workflows/maven.yml
Labels: cncf-cla: yes, size/XS, approved, lgtm
