Repository kubernetes-client/java, pull requests merged in 2021-12, with the labels that each got.

#2012 De-flake a couple tests.
  extended/src/test/java/io/kubernetes/client/extended/controller/builder/DefaultControllerBuilderTest.java
  extended/src/test/java/io/kubernetes/client/extended/workqueue/DefaultDelayingQueueTest.java
  spring/src/test/java/io/kubernetes/client/spring/extended/controller/KubernetesInformerCreatorTest.java
Labels: size/L, cncf-cla: yes, approved, lgtm

#2009 support certificate chain when reading client certificate(s)
  util/src/main/java/io/kubernetes/client/util/SSLUtils.java
Labels: cncf-cla: yes, size/S, approved, lgtm

#2007 GCPAuthenticator support without gcloud
  pom.xml
  util/pom.xml
  util/src/main/java/io/kubernetes/client/util/authenticators/GCPAuthenticator.java
  util/src/test/java/io/kubernetes/client/util/KubeConfigTest.java
  util/src/test/java/io/kubernetes/client/util/authenticators/GCPAuthenticatorTest.java
Labels: size/L, cncf-cla: yes, approved, lgtm

#2026 Cherry pick for #1802 and #1629 to release 14
  util/src/main/java/io/kubernetes/client/informer/SharedInformerFactory.java
  util/src/main/java/io/kubernetes/client/informer/cache/Controller.java
  util/src/main/java/io/kubernetes/client/informer/cache/ReflectorRunnable.java
  util/src/main/java/io/kubernetes/client/informer/impl/DefaultSharedIndexInformer.java
  util/src/main/java/io/kubernetes/client/util/ClientBuilder.java
  util/src/test/java/io/kubernetes/client/informer/cache/ControllerTest.java
  util/src/test/java/io/kubernetes/client/informer/cache/ReflectorRunnableTest.java
  util/src/test/java/io/kubernetes/client/informer/impl/DefaultSharedIndexInformerTest.java
  util/src/test/java/io/kubernetes/client/informer/impl/DefaultSharedIndexInformerWireMockTest.java
  util/src/test/java/io/kubernetes/client/util/ClientBuilderTest.java
Labels: cncf-cla: yes, approved, size/XL, lgtm

#1963 Return a default APIClient if we run into an exception
  spring/src/main/java/io/kubernetes/client/spring/extended/controller/config/KubernetesInformerAutoConfiguration.java
Labels: cncf-cla: yes, size/S, approved, lgtm

#2043 Cherry Pick #1963 To Master
  spring/src/main/java/io/kubernetes/client/spring/extended/controller/config/KubernetesInformerAutoConfiguration.java
Labels: cncf-cla: yes, size/S, approved, lgtm

#2040 gh-action: Upload snapshot as post-commit job
  .github/workflows/snapshot.yml
  README.md
Labels: cncf-cla: yes, size/S, approved, lgtm

#2046 Fix arrayIndexOutOfBounds exception for overloaded addModelMap method
  util/src/main/java/io/kubernetes/client/util/ModelMapper.java
  util/src/test/java/io/kubernetes/client/util/ModelMapperTest.java
Labels: cncf-cla: yes, size/S, approved, lgtm

#2050 Release: Fixes snapshot job env var name
  .github/workflows/snapshot.yml
Labels: cncf-cla: yes, size/XS, approved, lgtm
