Repository kubernetes-client/java, pull requests merged in 2021-02, with the labels that each got.

#1517 Chore: Removes stdout loggings
  util/src/main/java/io/kubernetes/client/util/ModelMapper.java
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1516 Register ControllerFactory bean definition as opposite to bean instance
  spring/src/main/java/io/kubernetes/client/spring/extended/controller/KubernetesReconcilerProcessor.java
  spring/src/test/java/io/kubernetes/client/spring/extended/controller/KubernetesReconcilerProcessorTest.java
Labels: approved, cncf-cla: yes, lgtm, size/L

#1518 Create LoadBalancer by hand instead of via annotation
  examples/examples-release-12/src/main/java/io/kubernetes/client/examples/SpringLoadBalancerExample.java
  spring/src/main/java/io/kubernetes/client/spring/extended/network/KubernetesEndpointsLoadBalancerProcessor.java
  spring/src/main/java/io/kubernetes/client/spring/extended/network/annotation/KubernetesEndpointsLoadBalanced.java
  spring/src/main/java/io/kubernetes/client/spring/extended/network/config/ConditionalOnKubernetesLoadBalancerEnabled.java
  spring/src/main/java/io/kubernetes/client/spring/extended/network/config/KubernetesLoadBalancerAutoConfiguration.java
  spring/src/main/java/io/kubernetes/client/spring/extended/network/endpoints/InformerEndpointsGetter.java
  spring/src/main/java/io/kubernetes/client/spring/extended/network/endpoints/PollingEndpointsGetter.java
  spring/src/main/resources/META-INF/spring.factories
  spring/src/test/java/io/kubernetes/client/spring/extended/controller/KubernetesInformerCreatorTest.java
  spring/src/test/java/io/kubernetes/client/spring/extended/network/KubernetesEndpointsLoadBalancerCreatorTest.java
  spring/src/test/java/io/kubernetes/client/spring/extended/network/TestApplication.java
Labels: approved, cncf-cla: yes, lgtm, size/L

#1529 Passing actual response status code in generic api's error handler
  util/src/main/java/io/kubernetes/client/util/generic/KubernetesApiResponse.java
  util/src/test/java/io/kubernetes/client/util/generic/KubernetesApiResponseTest.java
Labels: approved, cncf-cla: yes, lgtm, size/S

#1537 Fixes to handle better error cases
  util/src/main/java/io/kubernetes/client/PortForward.java
  util/src/main/java/io/kubernetes/client/util/ModelMapper.java
  util/src/test/java/io/kubernetes/client/PortForwardTest.java
Labels: approved, cncf-cla: yes, lgtm, size/M

#1532 Ensure KubernetesInformerFactoryProcessor does not access any beans
  spring/src/main/java/io/kubernetes/client/spring/extended/controller/KubernetesInformerConfigurer.java
  spring/src/main/java/io/kubernetes/client/spring/extended/controller/KubernetesInformerFactoryProcessor.java
  spring/src/main/java/io/kubernetes/client/spring/extended/controller/config/KubernetesInformerAutoConfiguration.java
  spring/src/test/java/io/kubernetes/client/spring/extended/controller/KubernetesInformerCreatorTest.java
  spring/src/test/java/io/kubernetes/client/spring/extended/controller/KubernetesReconcilerCreatorTest.java
  spring/src/test/java/io/kubernetes/client/spring/extended/controller/KubernetesReconcilerProcessorTest.java
Labels: approved, cncf-cla: yes, lgtm, size/L

#1543 Fixes reflector list expiration
  util/src/main/java/io/kubernetes/client/informer/cache/ReflectorRunnable.java
  util/src/test/java/io/kubernetes/client/informer/cache/ReflectorRunnableTest.java
Labels: approved, cncf-cla: yes, lgtm, size/M

#1544 Update the client library version in examples to 10.0.1
  examples/examples-release-10/pom.xml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1528 Feat: Dynamic kubernetes api for classless api requesting
  e2e/src/test/groovy/io/kubernetes/client/e2e/dynamic/DynamicApiTest.groovy
  examples/examples-release-12/pom.xml
  examples/examples-release-12/src/main/java/io/kubernetes/client/examples/DynamicClientExample.java
  util/src/main/java/io/kubernetes/client/util/generic/dynamic/DynamicKubernetesApi.java
  util/src/main/java/io/kubernetes/client/util/generic/dynamic/DynamicKubernetesListObject.java
  util/src/main/java/io/kubernetes/client/util/generic/dynamic/DynamicKubernetesObject.java
  util/src/main/java/io/kubernetes/client/util/generic/dynamic/DynamicKubernetesTypeAdaptorFactory.java
  util/src/main/java/io/kubernetes/client/util/generic/dynamic/Dynamics.java
  util/src/test/java/io/kubernetes/client/util/generic/dynamic/DynamicKubernetesApiTest.java
  util/src/test/java/io/kubernetes/client/util/generic/dynamic/DynamicKubernetesTypeAdaptorFactoryTest.java
Labels: approved, cncf-cla: yes, lgtm, size/XL

#1552 Cherrypick for RELEASE-11: Fixes reflector list expiration
  util/src/main/java/io/kubernetes/client/informer/cache/ReflectorRunnable.java
  util/src/test/java/io/kubernetes/client/informer/cache/ReflectorRunnableTest.java
Labels: approved, cncf-cla: yes, lgtm, size/M

#1550 Supporting password protected key-store
  util/src/main/java/io/kubernetes/client/util/ClientBuilder.java
  util/src/main/java/io/kubernetes/client/util/credentials/ClientCertificateAuthentication.java
  util/src/main/java/io/kubernetes/client/util/credentials/DummyAuthentication.java
  util/src/main/java/io/kubernetes/client/util/credentials/KubeconfigAuthentication.java
  util/src/test/java/io/kubernetes/client/util/ClientBuilderTest.java
  util/src/test/resources/kubeconfig-https-x509
Labels: approved, cncf-cla: yes, lgtm, size/L

#1559 Fixes event patching - unquote event count
  extended/src/main/java/io/kubernetes/client/extended/event/legacy/EventLogger.java
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1522 Make Maven reactor build work
  client-java-contrib/cert-manager/pom.xml
  client-java-contrib/prometheus-operator/pom.xml
  e2e/pom.xml
  examples/examples-release-10/pom.xml
  examples/examples-release-11/pom.xml
  examples/examples-release-12/pom.xml
  examples/examples-release-12/src/main/java/io/kubernetes/client/examples/DynamicClientExample.java
  examples/examples-release-12/src/main/java/io/kubernetes/client/examples/SpringLoadBalancerExample.java
  examples/pom.xml
  extended/pom.xml
  kubernetes/pom.xml
  pom.xml
  proto/pom.xml
  spring/pom.xml
  util/pom.xml
Labels: approved, cncf-cla: yes, lgtm, size/L

#1560 Spotless: groovy formatting
  e2e/src/test/groovy/io/kubernetes/client/e2e/basic/CoreV1ApiTest.groovy
  e2e/src/test/groovy/io/kubernetes/client/e2e/csr/CSRTest.groovy
  e2e/src/test/groovy/io/kubernetes/client/e2e/dynamic/DynamicApiTest.groovy
  e2e/src/test/groovy/io/kubernetes/client/e2e/informer/NamespaceInformerTest.groovy
  e2e/src/test/groovy/io/kubernetes/client/e2e/kubectl/KubectlDrainTest.groovy
  e2e/src/test/groovy/io/kubernetes/client/e2e/kubectl/KubectlNamespaceTest.groovy
  e2e/src/test/groovy/io/kubernetes/client/e2e/util/ModelMapperTest.groovy
  pom.xml
Labels: approved, cncf-cla: yes, lgtm, size/L
