Repository kubernetes-client/java, pull requests merged in 2021-04, with the labels that each got.

#1622 Improve docs for running examples.
  examples/examples-release-11/README.md
  examples/examples-release-12/README.md
  examples/examples-release-12/pom.xml
  examples/examples-release-13/README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#1625 bugfix KubectlGetSingle.execute() error
  extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlGet.java
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1617 Bugfix: Properly handling non-410 ApiExcetion in the reflector
  util/src/main/java/io/kubernetes/client/informer/cache/ReflectorRunnable.java
  util/src/test/java/io/kubernetes/client/informer/cache/ReflectorRunnableTest.java
Labels: approved, cncf-cla: yes, lgtm, size/M

#1627 Fix name and shutdown resync executor in Controller.shutdown
  util/src/main/java/io/kubernetes/client/informer/cache/Controller.java
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1624 Updating okhttpclient to 4.9.1
  pom.xml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1626 Add more debug/error logs and ensure controllerManager shutdown in case of exception
  extended/src/main/java/io/kubernetes/client/extended/controller/ControllerManager.java
  extended/src/main/java/io/kubernetes/client/extended/controller/DefaultController.java
Labels: approved, cncf-cla: yes, lgtm, size/S

#1631 bugfix KubernetesApiResponse cannot be cast to class KubernetesObject
  extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlPatch.java
Labels: approved, cncf-cla: yes, lgtm, size/S, tide/merge-method-squash

#1656 Feat: Jittering informer client-side watch timeout between 5~10 minutes
  spring/src/main/java/io/kubernetes/client/spring/extended/controller/config/KubernetesInformerProperties.java
  util/src/main/java/io/kubernetes/client/informer/cache/ReflectorRunnable.java
Labels: approved, cncf-cla: yes, lgtm, size/S

#1655 Chore: Removing version from default user-agent header
  kubernetes/src/main/java/io/kubernetes/client/openapi/ApiClient.java
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1658 Chore: Adding static helper to register lister kind to ModelMapper
  util/src/main/java/io/kubernetes/client/util/ModelMapper.java
Labels: approved, cncf-cla: yes, lgtm, size/M

#1667 Flake: Relaxing FromConfigMap tests timeout to 2s
  spring/src/test/java/io/kubernetes/client/spring/extended/manifests/KubernetesFromConfigMapTest.java
Labels: approved, cncf-cla: yes, lgtm, size/S

#1672 Bugfix: Defaulting status code to 200 for succeeding api response
  util/src/main/java/io/kubernetes/client/util/generic/KubernetesApiResponse.java
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1673 Doc: Registering generated classes via model mapper
  docs/generate-model-from-third-party-resources.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#1675 Feat: More dynamic shortcut utilities
  util/src/main/java/io/kubernetes/client/util/generic/dynamic/DynamicKubernetesObject.java
  util/src/main/java/io/kubernetes/client/util/generic/dynamic/Dynamics.java
  util/src/test/java/io/kubernetes/client/util/generic/dynamic/DynamicsTest.java
  util/src/test/resources/test-pod.json
Labels: approved, cncf-cla: yes, lgtm, size/L
