Repository kubernetes-client/java, pull requests merged in 2021-03, with the labels that each got.

#1569 Fixes eventlogger timestamp format
  extended/src/main/java/io/kubernetes/client/extended/event/legacy/EventLogger.java
  extended/src/test/java/io/kubernetes/client/extended/event/legacy/EventLoggerTest.java
Labels: approved, cncf-cla: yes, lgtm, size/M

#1570 Cherrypick for RELEASE-11: Fixes event-logger patch content
  extended/src/main/java/io/kubernetes/client/extended/event/legacy/EventLogger.java
  extended/src/test/java/io/kubernetes/client/extended/event/legacy/EventLoggerTest.java
Labels: approved, cncf-cla: yes, lgtm, size/M

#1572 Fix the build for JODA time
  extended/src/main/java/io/kubernetes/client/extended/event/legacy/EventLogger.java
  extended/src/test/java/io/kubernetes/client/extended/event/legacy/EventLoggerTest.java
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1583 Cherrypick for RELEASE-11: Passing actual response status code in error-handler
  util/src/main/java/io/kubernetes/client/util/generic/KubernetesApiResponse.java
  util/src/test/java/io/kubernetes/client/util/generic/KubernetesApiResponseTest.java
Labels: approved, cncf-cla: yes, lgtm, size/S

#1585 Cherrypick for RELEASE-11: Ensure KubernetesInformerFactoryProcessor does not access any beans
  spring/src/main/java/io/kubernetes/client/spring/extended/controller/KubernetesInformerConfigurer.java
  spring/src/main/java/io/kubernetes/client/spring/extended/controller/KubernetesInformerFactoryProcessor.java
  spring/src/main/java/io/kubernetes/client/spring/extended/controller/config/KubernetesInformerAutoConfiguration.java
  spring/src/test/java/io/kubernetes/client/spring/extended/controller/KubernetesInformerCreatorTest.java
  spring/src/test/java/io/kubernetes/client/spring/extended/controller/KubernetesReconcilerCreatorTest.java
  spring/src/test/java/io/kubernetes/client/spring/extended/controller/KubernetesReconcilerProcessorTest.java
Labels: approved, cncf-cla: yes, lgtm, size/L

#1589 Flake: Fixes leader-election e2e flakiness by relaxing timeout to 45s
  e2e/src/test/java/io/kubernetes/client/e2e/extended/leaderelection/LeaderElectorTest.java
Labels: approved, cncf-cla: yes, lgtm, size/XS

#1590 Release: Adding 12.0.0 release note
  CHANGELOG.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#1595 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#1592 Release 12.0.0
  client-java-contrib/cert-manager/pom.xml
  client-java-contrib/prometheus-operator/pom.xml
  e2e/pom.xml
  examples/examples-release-10/pom.xml
  examples/examples-release-11/pom.xml
  examples/examples-release-12/pom.xml
  examples/pom.xml
  extended/pom.xml
  kubernetes/pom.xml
  pom.xml
  proto/pom.xml
  spring/pom.xml
  util/pom.xml
Labels: approved, cncf-cla: yes, lgtm, size/M

#1594 Feat(spring): Adding FromConfigMap annotation that dynamically maps data config-map to map
  spring/pom.xml
  spring/src/main/java/io/kubernetes/client/spring/extended/manifests/KubernetesFromConfigMapProcessor.java
  spring/src/main/java/io/kubernetes/client/spring/extended/manifests/annotation/FromConfigMap.java
  spring/src/main/java/io/kubernetes/client/spring/extended/manifests/config/KubernetesManifestsAutoConfiguration.java
  spring/src/main/java/io/kubernetes/client/spring/extended/manifests/config/KubernetesManifestsProperties.java
  spring/src/main/java/io/kubernetes/client/spring/extended/manifests/configmaps/ConfigMapGetter.java
  spring/src/main/java/io/kubernetes/client/spring/extended/manifests/configmaps/InformerConfigMapGetter.java
  spring/src/main/java/io/kubernetes/client/spring/extended/manifests/configmaps/PollingConfigMapGetter.java
  spring/src/test/java/io/kubernetes/client/spring/extended/manifests/KubernetesFromConfigMapTest.java
Labels: approved, cncf-cla: yes, lgtm, size/XL

#1588 Enforcing read-timeout for informer-factory processor via property "kubernetes.informer.clientReadTimeout" (default 5min)
  spring/src/main/java/io/kubernetes/client/spring/extended/controller/KubernetesInformerFactoryProcessor.java
  spring/src/main/java/io/kubernetes/client/spring/extended/controller/config/KubernetesInformerAutoConfiguration.java
  spring/src/main/java/io/kubernetes/client/spring/extended/controller/config/KubernetesInformerProperties.java
  util/src/main/java/io/kubernetes/client/informer/cache/ReflectorRunnable.java
Labels: approved, cncf-cla: yes, lgtm, size/M

#1602 Chore: Improve leader-election logging, prints out current lock helder
  extended/src/main/java/io/kubernetes/client/extended/leaderelection/LeaderElector.java
  extended/src/test/java/io/kubernetes/client/extended/leaderelection/LeaderElectorTest.java
Labels: approved, cncf-cla: yes, lgtm, size/M

#1603 Chore: Support KubernetesInformers annotation on bean constructor
  spring/src/main/java/io/kubernetes/client/spring/extended/controller/KubernetesInformerFactoryProcessor.java
  spring/src/main/java/io/kubernetes/client/spring/extended/controller/annotation/KubernetesInformers.java
  spring/src/test/java/io/kubernetes/client/spring/extended/controller/KubernetesInformerCreatorTest.java
Labels: approved, cncf-cla: yes, lgtm, size/M

#1607 Update Spring versions (finally)
  pom.xml
  proto/pom.xml
Labels: approved, cncf-cla: yes, lgtm, size/S

#1611 Chore: Reducing rewatch logging verbosity upon normal re-connection
  util/src/main/java/io/kubernetes/client/informer/cache/ReflectorRunnable.java
Labels: approved, cncf-cla: yes, lgtm, size/S

#1481 Add logging dependency to e2e tests.
  e2e/pom.xml
Labels: approved, cncf-cla: yes, lgtm, size/S

#1620 Fixed Bug
  extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlLog.java
Labels: approved, cncf-cla: yes, lgtm, size/XS
