Repository kubernetes-client/java, pull requests merged in 2022-08, with the labels that each got.

#2321 Add support for dynamic objects to kubectl apply.
  extended/src/main/java/io/kubernetes/client/extended/kubectl/Kubectl.java
  extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlApply.java
  extended/src/test/java/io/kubernetes/client/extended/kubectl/KubectlApplyTest.java
  util/src/main/java/io/kubernetes/client/util/ModelMapper.java
Labels: size/L, cncf-cla: yes, approved, lgtm

#2339 Add null handling for a missing expiresOn field.
  util/src/main/java/io/kubernetes/client/util/authenticators/AzureActiveDirectoryAuthenticator.java
Labels: cncf-cla: yes, size/XS, approved, lgtm

#2343 fix for NO_EXECUTE toString Method
  util/src/main/java/io/kubernetes/client/util/taints/Taints.java
  util/src/test/java/io/kubernetes/client/util/taints/TaintsTest.java
Labels: cncf-cla: yes, size/S, approved, lgtm

#2353 Update logback-classic to 1.3.0
  pom.xml
Labels: cncf-cla: yes, size/XS, approved, lgtm
