Repository kubernetes-client/java, pull requests merged in 2022-02, with the labels that each got.

#2120 Deflake ExecTest
  util/src/test/java/io/kubernetes/client/ExecTest.java
Labels: cncf-cla: yes, size/S, approved, lgtm

#2124 Deflake the DefaultControllerTest.
  extended/src/test/java/io/kubernetes/client/extended/controller/DefaultControllerTest.java
Labels: cncf-cla: yes, size/M, approved, lgtm

#2129 Deflake another test
  extended/src/test/java/io/kubernetes/client/extended/controller/DefaultControllerTest.java
  extended/src/test/java/io/kubernetes/client/extended/controller/LeaderElectingControllerTest.java
Labels: cncf-cla: yes, size/M, approved, lgtm

#2148 Add support for transforming objects in shared informers
  util/src/main/java/io/kubernetes/client/informer/SharedInformer.java
  util/src/main/java/io/kubernetes/client/informer/TransformFunc.java
  util/src/main/java/io/kubernetes/client/informer/exception/ObjectTransformException.java
  util/src/main/java/io/kubernetes/client/informer/impl/DefaultSharedIndexInformer.java
  util/src/test/java/io/kubernetes/client/informer/impl/DefaultSharedIndexInformerWireMockTest.java
Labels: size/L, cncf-cla: yes, approved, lgtm
