Repository kubernetes-client/java, pull requests merged in 2022-04, with the labels that each got.

#2197 Adding a gh-action for generated java job
  .github/workflows/generate.yml
  .gitignore
  fluent-gen/README.md
  fluent-gen/generate.sh
Labels: size/L, cncf-cla: yes, approved, lgtm

#2205 Cherrypick #2197 to release-15
  .github/workflows/generate.yml
  .gitignore
  fluent-gen/README.md
  fluent-gen/generate.sh
Labels: size/L, cncf-cla: yes, approved, lgtm

#2207 Set permissions for GitHub actions
  .github/workflows/codeql-analysis.yml
  .github/workflows/generate.yml
  .github/workflows/snapshot.yml
Labels: cncf-cla: yes, size/S, approved, lgtm

#2216 official Apache Maven wrapper
  .mvn/wrapper/maven-wrapper.jar
  .mvn/wrapper/maven-wrapper.properties
  mvnw
  mvnw.cmd
Labels: size/L, cncf-cla: yes, approved, lgtm

#2222 Fix the default datetime formatter of OffsetDateTime dropping time zone info
  kubernetes/src/main/java/io/kubernetes/client/openapi/JSON.java
Labels: cncf-cla: yes, size/XS, approved, lgtm
