Repository kubernetes-client/java, pull requests merged in 2022-01, with the labels that each got.

#2054 Fixes snapshot job pt3
  .github/workflows/snapshot.yml
Labels: cncf-cla: yes, size/S, approved, lgtm

#2056 Sync automated release 10.0.2
  client-java-contrib/cert-manager/pom.xml
  client-java-contrib/prometheus-operator/pom.xml
  e2e/pom.xml
  examples/pom.xml
  extended/pom.xml
  kubernetes/pom.xml
  pom.xml
  proto/pom.xml
  spring/pom.xml
  util/pom.xml
Labels: cncf-cla: yes, size/S, approved, lgtm

#2057 Adding an manual release job that applies to release branches publishing maven releases
  .github/workflows/release.yml
  RELEASES.md
Labels: size/L, cncf-cla: yes, approved, lgtm

#2062 Cherry-pick(release-11): Adding a release job receiving manual input
  .github/workflows/release.yml
  RELEASES.md
Labels: size/L, cncf-cla: yes, approved, lgtm

#2063 Cherrypick(release-12): Adding a release job receiving manual input
  .github/workflows/release.yml
  RELEASES.md
Labels: size/L, cncf-cla: yes, approved, lgtm

#2064 Cherrypick(release-13): Adding a release job receiving manual input
  .github/workflows/release.yml
  RELEASES.md
Labels: size/L, cncf-cla: yes, approved, lgtm

#2065 Cherrypick(release-14): Adding a release job receiving manual input
  .github/workflows/release.yml
  RELEASES.md
Labels: size/L, cncf-cla: yes, approved, lgtm

#2070 Release Action: Send PR instead of direct push
  .github/workflows/release.yml
Labels: cncf-cla: yes, size/S, approved, lgtm

#2069 Release: 11.0.4
  client-java-contrib/cert-manager/pom.xml
  client-java-contrib/prometheus-operator/pom.xml
  e2e/pom.xml
  examples/pom.xml
  extended/pom.xml
  kubernetes/pom.xml
  pom.xml
  proto/pom.xml
  spring/pom.xml
  util/pom.xml
Labels: cncf-cla: yes, size/S, approved, lgtm

#2074 Cherrypick(release-11): Release job send pr instead of direct push
  .github/workflows/release.yml
Labels: cncf-cla: yes, size/S, approved, lgtm

#2078 Fixes java 16 compability
  pom.xml
  spring/pom.xml
  spring/src/test/java/io/kubernetes/client/spring/extended/controller/KubernetesInformerCreatorTest.java
  util/pom.xml
  util/src/main/java/io/kubernetes/client/util/Watch.java
  util/src/test/java/io/kubernetes/client/util/ClientBuilderTest.java
  util/src/test/java/io/kubernetes/client/util/ConfigTest.java
  util/src/test/java/io/kubernetes/client/util/generic/GenericKubernetesApiForCoreApiTest.java
  util/src/test/java/io/kubernetes/client/util/generic/GenericKubernetesApiTest.java
  util/src/test/java/io/kubernetes/client/util/generic/GenericKubernetesGetApiTest.java
Labels: size/L, cncf-cla: yes, approved, lgtm

#2079 Cherry Pick #1963 To 13.0
  spring/src/main/java/io/kubernetes/client/spring/extended/controller/config/KubernetesInformerAutoConfiguration.java
Labels: cncf-cla: yes, size/S, approved, lgtm

#2098 Flakiness: Fixes attach test failure by applying a longer delay
  util/src/test/java/io/kubernetes/client/AttachTest.java
Labels: cncf-cla: yes, size/XS, approved, lgtm

#2096 Chore: Clarify platform os on github action build
  .github/workflows/maven.yml
Labels: cncf-cla: yes, size/XS, approved, lgtm

#2099 Bump okhttp to 4.9.2
  pom.xml
Labels: cncf-cla: yes, size/XS, approved, lgtm

#2080 Improve descriptions a little bit with examples.
  .github/workflows/release.yml
Labels: cncf-cla: yes, size/XS, approved, lgtm

#2103 Fix OWNERS file : reviewer to reviewers
  OWNERS
Labels: cncf-cla: yes, size/XS, approved, lgtm

#2115 Deprecating no-arg informer-factory
  examples/examples-release-13/src/main/java/io/kubernetes/client/examples/InformerExample.java
  examples/examples-release-14/src/main/java/io/kubernetes/client/examples/InformerExample.java
  examples/examples-release-15/src/main/java/io/kubernetes/client/examples/InformerExample.java
  util/src/main/java/io/kubernetes/client/informer/SharedInformerFactory.java
Labels: cncf-cla: yes, size/S, approved, lgtm

#2116 Add Deployment rollout restart example
  examples/examples-release-15/src/main/java/io/kubernetes/client/examples/DeployRolloutRestartExample.java
Labels: size/L, cncf-cla: yes, approved, lgtm
