Repository kubernetes-client/java, pull requests merged in 2022-09, with the labels that each got.

#2362 Bump OkHttp From 4.9.2 To 4.10.0
  pom.xml
Labels: cncf-cla: yes, size/XS, approved, lgtm

#2366 Add a consumer for unhandled errors to Exec.java
  extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlExec.java
  extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlPortForward.java
  util/src/main/java/io/kubernetes/client/Exec.java
  util/src/test/java/io/kubernetes/client/ExecTest.java
Labels: size/L, cncf-cla: yes, approved, lgtm

#2381 docs(build): link added to build badge #2380
  README.md
Labels: cncf-cla: yes, size/XS, approved, lgtm

#2388 fix: WebSocketOutputStream wait to write until WebSocket queue is released
  util/src/main/java/io/kubernetes/client/util/WebSocketStreamHandler.java
Labels: cncf-cla: yes, size/M, approved, lgtm
