Repository kubernetes-client/java, pull requests merged in 2022-12, with the labels that each got.

#2473 update kubernetes links & others
  .gitignore
  RELEASES.md
  client-java-contrib/prometheus-operator/src/main/java/com/coreos/monitoring/models/V1AlertmanagerSpec.java
  client-java-contrib/prometheus-operator/src/main/java/com/coreos/monitoring/models/V1AlertmanagerSpecPodMetadata.java
  client-java-contrib/prometheus-operator/src/main/java/com/coreos/monitoring/models/V1PrometheusSpec.java
  client-java-contrib/prometheus-operator/src/main/java/com/coreos/monitoring/models/V1PrometheusSpecPodMetadata.java
  client-java-contrib/prometheus-operator/src/main/java/com/coreos/monitoring/models/V1ThanosRulerSpecStorageEmptyDir.java
  kubernetes/docs/V1CrossVersionObjectReference.md
  kubernetes/docs/V1ObjectMeta.md
  kubernetes/docs/V2CrossVersionObjectReference.md
  kubernetes/docs/V2beta2CrossVersionObjectReference.md
  proto/src/main/java/io/kubernetes/client/proto/Meta.java
  proto/src/main/java/io/kubernetes/client/proto/V1Autoscaling.java
  proto/src/main/java/io/kubernetes/client/proto/V1beta1Apps.java
  proto/src/main/java/io/kubernetes/client/proto/V1beta1Extensions.java
  proto/src/main/java/io/kubernetes/client/proto/V1beta2Apps.java
  proto/src/main/java/io/kubernetes/client/proto/V2beta1Autoscaling.java
  proto/src/main/java/io/kubernetes/client/proto/V2beta2Autoscaling.java
Labels: size/L, cncf-cla: yes, approved, lgtm

#2457 add a module for Spring Boot 3 AOT
  .github/workflows/codeql-analysis.yml
  .github/workflows/maven.yml
  pom.xml
  spring-aot/pom.xml
  spring-aot/src/main/java/io/kubernetes/client/spring/aot/KubernetesBeanFactoryInitializationAotProcessor.java
  spring-aot/src/main/resources/META-INF/spring/aot.factories
  spring/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
Labels: size/L, cncf-cla: yes, approved, lgtm

#2479 Cherrypick(release-15): Bump OkHttp From 4.9.2 To 4.10.0
  pom.xml
Labels: cncf-cla: yes, size/XS, approved, lgtm

#2481 Cherrypick(release-16): Bump okhttp from 4.9.2 to 4.10.0
  pom.xml
Labels: cncf-cla: yes, size/XS, approved, lgtm

#2482 Cherrypick(release-16): Bump protobuf-java from 3.21.2 to 3.21.8
  pom.xml
Labels: cncf-cla: yes, size/XS, approved, lgtm

#2484 Workflow: Bumping snapshot workflow to JDK 17
  .github/workflows/snapshot.yml
Labels: cncf-cla: yes, size/XS, approved, lgtm

#2487 Switch to Java 17 for release action.
  .github/workflows/release.yml
Labels: cncf-cla: yes, size/XS, approved, lgtm

#2488 Cherry pick some github actions fixes into the release-17 branch.
  .github/workflows/release.yml
  .github/workflows/snapshot.yml
Labels: cncf-cla: yes, size/XS, approved, lgtm

#2492 Bump to 18.0.0-SNAPSHOT prepared for next release
  client-java-contrib/admissionreview/pom.xml
  client-java-contrib/cert-manager/pom.xml
  client-java-contrib/prometheus-operator/pom.xml
  e2e/pom.xml
  examples/examples-release-13/pom.xml
  examples/examples-release-14/pom.xml
  examples/examples-release-15/pom.xml
  examples/pom.xml
  extended/pom.xml
  fluent-gen/pom.xml
  fluent/pom.xml
  kubernetes/pom.xml
  kubernetes/src/main/java/io/kubernetes/client/openapi/ApiClient.java
  pom.xml
  proto/pom.xml
  spring-aot/pom.xml
  spring/pom.xml
  util/pom.xml
Labels: cncf-cla: yes, size/M, approved, lgtm

#2493 Chore: Merge jacoco maven plugin declaration to parent pom
  pom.xml
  spring-aot/pom.xml
  spring/pom.xml
  util/pom.xml
Labels: cncf-cla: yes, size/M, approved, lgtm

#2503 doDrain(): Don't try to delete daemonset pods and wait longer than grace period before timing out
  extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlDrain.java
Labels: cncf-cla: yes, size/S, approved, lgtm

#2505 Fix path for CRD GHA in docs
  docs/generate-model-from-third-party-resources.md
Labels: cncf-cla: yes, size/XS, approved, lgtm
