Repository kubernetes-client/java, pull requests merged in 2022-11, with the labels that each got.

#2435 Fix the default delay queue to use a fixed time source.
  extended/src/main/java/io/kubernetes/client/extended/workqueue/DefaultDelayingQueue.java
  extended/src/test/java/io/kubernetes/client/extended/workqueue/DefaultDelayingQueueTest.java
Labels: cncf-cla: yes, size/M, approved, lgtm

#2441 Refactor SSLUtils.loadKey using PEMParser
  util/src/main/java/io/kubernetes/client/util/SSLUtils.java
Labels: size/L, cncf-cla: yes, approved, lgtm

#2442 Refactor SSLUtilsTest with shared method and algorithm assertions
  util/src/test/java/io/kubernetes/client/util/SSLUtilsTest.java
Labels: cncf-cla: yes, size/M, approved, lgtm

#2462 update readme links
  README.md
Labels: cncf-cla: yes, size/XS, approved, lgtm

#2471 Add validation that the request body is as expected in kubectl label.
  extended/src/test/java/io/kubernetes/client/extended/kubectl/KubectlLabelTest.java
Labels: cncf-cla: yes, size/S, approved, lgtm

#2465 Delete label
  extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlLabel.java
  extended/src/test/java/io/kubernetes/client/extended/kubectl/KubectlLabelTest.java
Labels: cncf-cla: yes, size/M, approved, lgtm
