Repository kubernetes-client/java, pull requests merged in 2023-11, with the labels that each got.

#2897 Fix order-dependent flakiness in KubernetesReconcilerCreatorTest.java
  spring/src/test/java/io/kubernetes/client/spring/extended/controller/KubernetesReconcilerCreatorTest.java
Labels: cncf-cla: yes, size/XS, approved, lgtm

#2898 Add ignoreNotFound flag to KubectlDelete.java
  extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlDelete.java
Labels: cncf-cla: yes, size/S, approved, lgtm

#2906 Add Kubectl delete tests
  extended/src/test/java/io/kubernetes/client/extended/kubectl/KubectlDeleteTest.java
  extended/src/test/resources/deleted-add-job.json
  extended/src/test/resources/deleted-get-batch.json
  extended/src/test/resources/deleted-not-found.json
  extended/src/test/resources/deleted-success.json
Labels: cncf-cla: yes, approved, size/XL, lgtm
