Repository kubernetes-client/java, pull requests merged in 2023-02, with the labels that each got.

#2540 Add asynchronous methods to GenericKubernetesApi
  extended/src/test/java/io/kubernetes/client/extended/kubectl/KubectlAnnotateTest.java
  extended/src/test/java/io/kubernetes/client/extended/kubectl/KubectlApplyTest.java
  extended/src/test/java/io/kubernetes/client/extended/kubectl/KubectlCreateTest.java
  extended/src/test/java/io/kubernetes/client/extended/kubectl/KubectlLabelTest.java
  util/src/main/java/io/kubernetes/client/util/generic/GenericKubernetesApi.java
  util/src/test/java/io/kubernetes/client/util/generic/GenericKubernetesApiForCoreApiTest.java
  util/src/test/java/io/kubernetes/client/util/generic/GenericKubernetesApiTest.java
  util/src/test/java/io/kubernetes/client/util/generic/GenericKubernetesGetApiTest.java
  util/src/test/java/io/kubernetes/client/util/generic/KubernetesApiResponseTest.java
Labels: cncf-cla: yes, size/XXL, approved, lgtm, ok-to-test

#2549 Bugfix: Fixes indexKeys NPE
  util/src/main/java/io/kubernetes/client/informer/cache/Cache.java
Labels: cncf-cla: yes, size/XS, approved, lgtm

#2551 Builder methods for *Options classes
  util/src/main/java/io/kubernetes/client/util/generic/options/CreateOptions.java
  util/src/main/java/io/kubernetes/client/util/generic/options/ListOptions.java
  util/src/main/java/io/kubernetes/client/util/generic/options/PatchOptions.java
  util/src/main/java/io/kubernetes/client/util/generic/options/UpdateOptions.java
Labels: cncf-cla: yes, size/M, approved, lgtm

#2550 Support PartialObjectMetadata requests
  util/src/main/java/io/kubernetes/client/util/generic/GenericKubernetesApi.java
  util/src/main/java/io/kubernetes/client/util/generic/options/GetOptions.java
  util/src/main/java/io/kubernetes/client/util/generic/options/ListOptions.java
  util/src/test/java/io/kubernetes/client/util/generic/GenericKubernetesApiTest.java
Labels: size/L, cncf-cla: yes, approved, lgtm

#2553 Fix `DynamicKubernetesTypeAdaptorFactory` when it does not apply.
  util/src/main/java/io/kubernetes/client/util/generic/dynamic/DynamicKubernetesTypeAdaptorFactory.java
  util/src/test/java/io/kubernetes/client/util/generic/dynamic/DynamicKubernetesTypeAdaptorFactoryTest.java
Labels: cncf-cla: yes, size/S, approved, lgtm

#2561 added ability to inject threads
  util/src/main/java/io/kubernetes/client/util/Threads.java
Labels: cncf-cla: yes, size/XS, approved, lgtm

#2567 fixed: An error.
  docs/generate-model-from-third-party-resources.md
Labels: cncf-cla: yes, size/XS, approved, lgtm

#2574 WebSockets: handle onClosing
  util/src/main/java/io/kubernetes/client/util/WebSockets.java
Labels: cncf-cla: yes, size/XS, approved, lgtm

#2580 Compensating changes for SnakeYAML 2.0
  pom.xml
  util/src/main/java/io/kubernetes/client/util/FilePersister.java
  util/src/main/java/io/kubernetes/client/util/KubeConfig.java
  util/src/main/java/io/kubernetes/client/util/Yaml.java
  util/src/main/java/io/kubernetes/client/util/generic/dynamic/Dynamics.java
Labels: cncf-cla: yes, size/S, approved, lgtm
