Repository kubernetes-client/java, pull requests merged in 2023-04, with the labels that each got.

#2612 Cherry Pick For 17.x - Compensating changes for SnakeYAML 2.0
  pom.xml
  util/src/main/java/io/kubernetes/client/util/FilePersister.java
  util/src/main/java/io/kubernetes/client/util/KubeConfig.java
  util/src/main/java/io/kubernetes/client/util/Yaml.java
  util/src/main/java/io/kubernetes/client/util/generic/dynamic/Dynamics.java
Labels: cncf-cla: yes, size/S, approved, lgtm

#2613 Cherry Pick For 13.x snakeyaml 2.0
  pom.xml
  util/src/main/java/io/kubernetes/client/util/FilePersister.java
  util/src/main/java/io/kubernetes/client/util/KubeConfig.java
  util/src/main/java/io/kubernetes/client/util/Yaml.java
  util/src/main/java/io/kubernetes/client/util/generic/dynamic/Dynamics.java
Labels: cncf-cla: yes, size/M, approved, lgtm

#2617 tweak graceful shutdown of LeaderElector
  extended/src/main/java/io/kubernetes/client/extended/leaderelection/LeaderElector.java
Labels: cncf-cla: yes, size/M, approved, lgtm

#2611 Updated elgohr/Publish-Docker-Github-Action to a supported version (v5)
  .github/workflows/maven.yml
Labels: cncf-cla: yes, size/XS, approved, lgtm

#2620 Handle nested JAR files in getClassNamesFromPackage and reduce cognit…
  util/src/main/java/io/kubernetes/client/util/ModelMapper.java
  util/src/test/java/io/kubernetes/client/util/ModelMapperTest.java
Labels: size/L, cncf-cla: yes, approved, lgtm

#2635 Revert "build(deps): bump jacoco-maven-plugin from 0.8.8 to 0.8.9"
  extended/pom.xml
  pom.xml
Labels: cncf-cla: yes, size/XS, approved, lgtm

#2645 Fixed bug: label being set as null instead of deleted
  extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlLabel.java
  extended/src/test/java/io/kubernetes/client/extended/kubectl/KubectlLabelTest.java
Labels: cncf-cla: yes, size/XS, approved, lgtm
