Repository kubernetes-client/java, pull requests merged in 2023-05, with the labels that each got.

#2657 use dl.k8s.io, not kubernetes-release bucket
  client-java-contrib/Dockerfile
Labels: cncf-cla: yes, size/XS, approved, kind/cleanup, lgtm, kind/deprecation

#2670 Update generate.sh
  client-java-contrib/generate.sh
Labels: cncf-cla: yes, size/XS, approved, lgtm

#2675 Fix Maven build warnings and minor doc issues
  .github/workflows/maven.yml
  CONTRIBUTING.md
  examples/examples-release-14/README.md
  examples/examples-release-15/README.md
  fluent-gen/pom.xml
  kubernetes/pom.xml
  pom.xml
Labels: cncf-cla: yes, size/M, approved, lgtm
