Repository kubernetes-client/java, pull requests merged in 2023-09, with the labels that each got.

#2787 No need to compare format when compare Quantity
  kubernetes/src/main/java/io/kubernetes/client/custom/Quantity.java
  kubernetes/src/test/java/io/kubernetes/client/custom/QuantityFormatterTest.java
Labels: cncf-cla: yes, size/S, approved, lgtm

#2801 Fixing flaky rate-limiting test
  extended/src/test/java/io/kubernetes/client/extended/workqueue/DefaultRateLimitQueueTest.java
Labels: cncf-cla: yes, size/XS, approved, lgtm

#2796 Update pom.xml to skip release (I hope)
  client-java-contrib/admissionreview/pom.xml
  examples/examples-release-16/pom.xml
  examples/examples-release-17/pom.xml
  examples/examples-release-18/pom.xml
  examples/pom.xml
Labels: cncf-cla: yes, size/M, approved, lgtm
