Repository kubernetes-client/java, pull requests merged in 2023-10, with the labels that each got.

#2812 Add jakarta.annotation dependency for future code generation.
  kubernetes/pom.xml
  pom.xml
Labels: cncf-cla: yes, size/S, approved, lgtm

#2815 Bump staging version to 20.0.0-SNAPSHOT
  client-java-contrib/admissionreview/pom.xml
  client-java-contrib/cert-manager/pom.xml
  client-java-contrib/prometheus-operator/pom.xml
  e2e/pom.xml
  examples/examples-release-16/pom.xml
  examples/examples-release-17/pom.xml
  examples/examples-release-18/pom.xml
  examples/examples-release-19/pom.xml
  examples/pom.xml
  extended/pom.xml
  fluent-gen/pom.xml
  fluent/pom.xml
  kubernetes/pom.xml
  kubernetes/src/main/java/io/kubernetes/client/openapi/ApiClient.java
  pom.xml
  proto/pom.xml
  spring-aot/pom.xml
  spring/pom.xml
  util/pom.xml
Labels: cncf-cla: yes, size/M, approved, lgtm

#2806 EKS authentication based on AWS Sigv4
  examples/examples-release-19/pom.xml
  examples/examples-release-19/src/main/java/io/kubernetes/client/examples/EKSAuthenticationExample.java
  pom.xml
  util/pom.xml
  util/src/main/java/io/kubernetes/client/persister/ConfigPersister.java
  util/src/main/java/io/kubernetes/client/persister/FilePersister.java
  util/src/main/java/io/kubernetes/client/util/ClientBuilder.java
  util/src/main/java/io/kubernetes/client/util/KubeConfig.java
  util/src/main/java/io/kubernetes/client/util/credentials/EKSAuthentication.java
  util/src/main/java/io/kubernetes/client/util/eks/AWS4STSSigner.java
  util/src/main/java/io/kubernetes/client/util/eks/AWS4SignerBase.java
  util/src/main/java/io/kubernetes/client/util/eks/BinaryUtils.java
  util/src/main/java/io/kubernetes/client/util/eks/HttpUtils.java
  util/src/test/java/io/kubernetes/client/util/FilePersisterTest.java
  util/src/test/java/io/kubernetes/client/util/credentials/EKSAuthenticationTest.java
Labels: cncf-cla: yes, approved, size/XL, lgtm

#2826 Update pom.xml
  pom.xml
Labels: cncf-cla: yes, size/S, approved, lgtm

#2827 Cherry pick #2826 Update pom.xml into release 19 branch.
  pom.xml
Labels: cncf-cla: yes, size/S, approved, lgtm

#2828 Release-19: Reset release 19 pom version to 19.0.0-SNAPSHOT
  client-java-contrib/admissionreview/pom.xml
  client-java-contrib/cert-manager/pom.xml
  client-java-contrib/prometheus-operator/pom.xml
  e2e/pom.xml
  examples/examples-release-16/pom.xml
  examples/examples-release-17/pom.xml
  examples/examples-release-18/pom.xml
  examples/examples-release-19/pom.xml
  examples/pom.xml
  extended/pom.xml
  fluent/pom.xml
  kubernetes/pom.xml
  pom.xml
  proto/pom.xml
  spring-aot/pom.xml
  spring/pom.xml
  util/pom.xml
Labels: cncf-cla: yes, size/M, approved, lgtm

#2833 Update pom for release-19 examples [cherrypick to release-19 branch]
  examples/examples-release-18/pom.xml
  examples/examples-release-19/pom.xml
Labels: cncf-cla: yes, size/M, approved, lgtm

#2832 Update pom.xml for release-19 examples.
  examples/examples-release-18/pom.xml
  examples/examples-release-19/pom.xml
Labels: cncf-cla: yes, size/M, approved, lgtm

#2818 Remove JSON.java from openapi ignore file.
  kubernetes/.openapi-generator-ignore
Labels: cncf-cla: yes, size/XS, approved, lgtm

#2846 Ignore json test temporarily for code generation
  kubernetes/src/test/java/io/kubernetes/client/openapi/JSONTest.java
Labels: cncf-cla: yes, size/XS, approved, lgtm

#2845 Revert "Release-19: Reset release 19 pom version to 19.0.0-SNAPSHOT"
  client-java-contrib/admissionreview/pom.xml
  client-java-contrib/cert-manager/pom.xml
  client-java-contrib/prometheus-operator/pom.xml
  e2e/pom.xml
  examples/examples-release-16/pom.xml
  examples/examples-release-17/pom.xml
  examples/examples-release-18/pom.xml
  examples/examples-release-19/pom.xml
  examples/pom.xml
  extended/pom.xml
  fluent/pom.xml
  kubernetes/pom.xml
  pom.xml
  proto/pom.xml
  spring-aot/pom.xml
  spring/pom.xml
  util/pom.xml
Labels: cncf-cla: yes, size/M, approved, lgtm

#2851 Suppress JSON unit test for code generation
  kubernetes/src/test/java/io/kubernetes/client/openapi/JSONTest.java
Labels: cncf-cla: yes, size/XS, approved, lgtm

#2853 Ignore all JSON test for next code gen
  kubernetes/src/test/java/io/kubernetes/client/openapi/JSONTest.java
Labels: cncf-cla: yes, size/XS, approved, lgtm

#2860 Expose resize & connection-error streams for Attach
  util/src/main/java/io/kubernetes/client/Attach.java
Labels: cncf-cla: yes, size/XS, approved, lgtm
