Repository kubernetes-client/java, pull requests merged in 2023-03, with the labels that each got.

#2598 Use synchronization classes instead of Thread.sleep in test cases
  util/src/test/java/io/kubernetes/client/informer/cache/SharedProcessorTest.java
Labels: cncf-cla: yes, size/M, approved, lgtm

#2586 Don't try to pull request if dry run is true.
  .github/workflows/release.yml
Labels: cncf-cla: yes, size/XS, approved, lgtm

#2588 Update spotless testing to use JDK 11
  .github/workflows/maven.yml
Labels: cncf-cla: yes, size/XS, approved, lgtm

#2608 Use synchronization classes instead of Thread.sleep and fix flaky test
  util/src/test/java/io/kubernetes/client/informer/impl/DefaultSharedIndexInformerWireMockTest.java
Labels: size/L, cncf-cla: yes, approved, lgtm

#2605 add exceptionHandler for SharedInformerFactory.sharedIndexInformerFor
  util/src/main/java/io/kubernetes/client/informer/SharedInformerFactory.java
Labels: cncf-cla: yes, size/M, approved, lgtm
