Repository kubernetes-client/java, pull requests merged in 2024-08, with the labels that each got.

#3595 feat: add support for FIPS bouncy castle #3590
  util/src/main/java/io/kubernetes/client/util/SSLUtils.java
Labels: cncf-cla: yes, size/S, approved, lgtm

#3612 Update codeql action to remove autobuild
  .github/workflows/codeql-analysis.yml
Labels: cncf-cla: yes, size/XS, approved

#3627 optional 3rd party ignored (issue #3596)
  extended/pom.xml
  fluent-gen/pom.xml
  pom.xml
  spring/pom.xml
  util/pom.xml
Labels: cncf-cla: yes, size/M, approved, lgtm

#3642 Add token refresh for exec credentials.
  util/src/main/java/io/kubernetes/client/util/ClientBuilder.java
  util/src/main/java/io/kubernetes/client/util/credentials/KubeconfigAuthentication.java
  util/src/main/java/io/kubernetes/client/util/credentials/RefreshAuthentication.java
  util/src/test/java/io/kubernetes/client/util/credentials/KubeconfigAuthenticationTest.java
  util/src/test/java/io/kubernetes/client/util/credentials/RefreshAuthenticationTest.java
Labels: size/L, cncf-cla: yes, approved, lgtm
