Repository kubernetes-client/java, pull requests merged in 2024-12, with the labels that each got.

#3813 Update gson version to 2.11.0
  .github/workflows/maven.yml
  pom.xml
Labels: cncf-cla: yes, size/S, approved, lgtm

#3801 Add support for terminal resize in ExecProcess
  util/src/main/java/io/kubernetes/client/Exec.java
  util/src/main/java/io/kubernetes/client/util/WebSocketStreamHandler.java
  util/src/test/java/io/kubernetes/client/ExecTest.java
Labels: cncf-cla: yes, size/M, approved, lgtm

#3814 Cherry Pick #2952 To Release 19
  util/src/main/java/io/kubernetes/client/util/ModelMapper.java
Labels: cncf-cla: yes, size/S, approved, lgtm

#3817 Refactor: Merge TokenFile auth with refresh auth
  util/src/main/java/io/kubernetes/client/util/credentials/RefreshAuthentication.java
  util/src/main/java/io/kubernetes/client/util/credentials/TokenFileAuthentication.java
  util/src/main/java/io/kubernetes/client/util/exception/TokenAquisitionException.java
  util/src/test/java/io/kubernetes/client/util/credentials/TokenFileAuthenticationTest.java
Labels: size/L, cncf-cla: yes, approved, lgtm
