Repository kubernetes-client/java, pull requests merged in 2024-03, with the labels that each got.

#3144 Skip deployment of E2E test module to maven repository
  e2e/pom.xml
  examples/examples-release-17/pom.xml
  examples/examples-release-18/pom.xml
  examples/examples-release-19/pom.xml
  examples/examples-release-20/pom.xml
  examples/examples-release-latest/pom.xml
Labels: cncf-cla: yes, size/S, approved, lgtm

#3145 Migrates e2e tests from spock to plain JUnit
  e2e/pom.xml
  e2e/src/test/groovy/io/kubernetes/client/e2e/basic/CoreV1ApiTest.groovy
  e2e/src/test/groovy/io/kubernetes/client/e2e/csr/CSRTest.groovy
  e2e/src/test/groovy/io/kubernetes/client/e2e/dynamic/DynamicApiTest.groovy
  e2e/src/test/groovy/io/kubernetes/client/e2e/informer/NamespaceInformerTest.groovy
  e2e/src/test/groovy/io/kubernetes/client/e2e/kubectl/KubectlDrainTest.groovy
  e2e/src/test/groovy/io/kubernetes/client/e2e/kubectl/KubectlNamespaceTest.groovy
  e2e/src/test/groovy/io/kubernetes/client/e2e/kubectl/KubectlRolloutTest.groovy
  e2e/src/test/groovy/io/kubernetes/client/e2e/util/ModelMapperTest.groovy
  e2e/src/test/java/io/kubernetes/client/e2e/basic/CoreV1ApiTest.java
  e2e/src/test/java/io/kubernetes/client/e2e/csr/CSRTest.java
  e2e/src/test/java/io/kubernetes/client/e2e/dynamic/DynamicApiTest.java
  e2e/src/test/java/io/kubernetes/client/e2e/informer/NamespaceInformerTest.java
  e2e/src/test/java/io/kubernetes/client/e2e/kubectl/KubectlDrainTest.java
  e2e/src/test/java/io/kubernetes/client/e2e/kubectl/KubectlNamespaceTest.java
  e2e/src/test/java/io/kubernetes/client/e2e/kubectl/KubectlRolloutTest.java
  e2e/src/test/java/io/kubernetes/client/e2e/util/ModelMapperTest.java
  extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlRollout.java
Labels: cncf-cla: yes, size/XXL, approved, lgtm

#3170 openrewrite: apply Slf4jBestPractices
  examples/examples-release-17/src/main/java/io/kubernetes/client/examples/ExpandedExample.java
  examples/examples-release-18/src/main/java/io/kubernetes/client/examples/ExpandedExample.java
  examples/examples-release-19/src/main/java/io/kubernetes/client/examples/ExpandedExample.java
  examples/examples-release-20/src/main/java/io/kubernetes/client/examples/ExpandedExample.java
  examples/examples-release-latest/src/main/java/io/kubernetes/client/examples/ExpandedExample.java
  extended/src/main/java/io/kubernetes/client/extended/controller/ControllerManager.java
  spring-aot/src/main/java/io/kubernetes/client/spring/aot/KubernetesBeanFactoryInitializationAotProcessor.java
  spring/src/main/java/io/kubernetes/client/spring/extended/controller/config/KubernetesInformerAutoConfiguration.java
  util/src/main/java/io/kubernetes/client/Copy.java
  util/src/main/java/io/kubernetes/client/informer/cache/ReflectorRunnable.java
  util/src/main/java/io/kubernetes/client/util/ClientBuilder.java
  util/src/main/java/io/kubernetes/client/util/KubeConfig.java
  util/src/main/java/io/kubernetes/client/util/ModelMapper.java
  util/src/main/java/io/kubernetes/client/util/Yaml.java
  util/src/main/java/io/kubernetes/client/util/eks/HttpUtils.java
Labels: cncf-cla: yes, size/M, approved, lgtm

#3171 Update google-java-format to LTS 17
  pom.xml
Labels: cncf-cla: yes, size/XS, approved, lgtm

#3175 Resolve indirect dep CVE from adal4j
  pom.xml
Labels: cncf-cla: yes, size/XS, approved, lgtm

#3174 build(deps): bump org.apache.commons:commons-compress
  pom.xml
Labels: cncf-cla: yes, size/XS, approved, lgtm

#3176 Fix CVEs brought in by accidental spring boot version override
  spring-aot/pom.xml
Labels: cncf-cla: yes, size/XS, approved, lgtm

#3193 Update devcontainer to use Java 17 (required for Spring >= 6)
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
Labels: cncf-cla: yes, size/XS, approved, lgtm

#3194 build(deps): bump org.apache.commons:commons-compress
  pom.xml
Labels: cncf-cla: yes, size/XS, approved, lgtm

#3195 Upgrade to apache commons compress 1.26.1
  pom.xml
Labels: cncf-cla: yes, size/XS, approved, lgtm

#3203 Fix typo in pom.xml
  client-java-contrib/admissionreview/pom.xml
  client-java-contrib/cert-manager/pom.xml
  client-java-contrib/prometheus-operator/pom.xml
  e2e/pom.xml
  examples/examples-release-16/pom.xml
  examples/examples-release-17/pom.xml
  examples/examples-release-18/pom.xml
  examples/examples-release-19/pom.xml
  examples/pom.xml
  extended/pom.xml
  fluent-gen/pom.xml
  fluent/pom.xml
  kubernetes/pom.xml
  pom.xml
  proto/pom.xml
  spring-aot/pom.xml
  spring/pom.xml
  util/pom.xml
Labels: cncf-cla: yes, size/M, approved
