Repository kubernetes-client/java, pull requests merged in 2024-01, with the labels that each got.

#2945 Branch(java8): Add `-legacy` version qualifier to java8 compatible modules
  client-java-contrib/admissionreview/pom.xml
  client-java-contrib/cert-manager/pom.xml
  client-java-contrib/prometheus-operator/pom.xml
  e2e/pom.xml
  examples/examples-release-16/pom.xml
  examples/examples-release-17/pom.xml
  examples/examples-release-18/pom.xml
  examples/examples-release-19/pom.xml
  examples/pom.xml
  extended/pom.xml
  fluent-gen/pom.xml
  fluent/pom.xml
  kubernetes/pom.xml
  kubernetes/src/main/java/io/kubernetes/client/openapi/ApiClient.java
  pom.xml
  proto/pom.xml
  spring-aot/pom.xml
  spring/pom.xml
  util/pom.xml
Labels: cncf-cla: yes, size/M, approved, lgtm

#2974 Chore: Run github action for PR against `master-java8` branch
  .github/workflows/maven.yml
Labels: cncf-cla: yes, size/XS, approved, lgtm

#2952 #2241 fix bug: when running with a fat jar, need to read entries with openConnection
  util/src/main/java/io/kubernetes/client/util/ModelMapper.java
Labels: cncf-cla: yes, size/S, approved, lgtm

#2981 Branch(master-java8): Pin generator version to v4.3.1
  .github/workflows/generate.yml
  .github/workflows/maven.yml
Labels: cncf-cla: yes, size/XS, approved, lgtm

#3014 Upgrade okhttp to 4.12.0
  pom.xml
Labels: cncf-cla: yes, size/XS, approved, lgtm

#3019 Adding release note for 20.0.0 breaking change
  README.md
Labels: cncf-cla: yes, size/XS, approved, lgtm

#3021 Tracking manual edits in git diffs to unlock openapi ignore
  .github/workflows/generate.yml
  kubernetes/.openapi-generator-ignore
  scripts/patches/json.diff
  scripts/patches/list-meta.diff
  scripts/patches/status.diff
Labels: size/L, cncf-cla: yes, approved, lgtm
