Repository kubernetes-client/java, pull requests merged in 2024-02, with the labels that each got.

#3025 Fixes secret deep-compare issue and track the change by patches
  kubernetes/src/main/java/io/kubernetes/client/custom/MapUtils.java
  kubernetes/src/main/java/io/kubernetes/client/openapi/models/V1Secret.java
  kubernetes/src/test/java/io/kubernetes/client/custom/MapUtilsTest.java
  kubernetes/src/test/java/io/kubernetes/client/openapi/V1SecretTest.java
  scripts/patches/secret.diff
Labels: size/L, cncf-cla: yes, approved, lgtm

#3032 Update dependabot.yml
  .github/dependabot.yml
Labels: cncf-cla: yes, size/XS, approved, lgtm

#3050 Add additional command line argument for client generation script
  client-java-contrib/generate.sh
Labels: cncf-cla: yes, size/XS, approved, lgtm

#3051 Update git generated commit author to pass CLA
  .github/workflows/generate.yml
  .github/workflows/release.yml
Labels: cncf-cla: yes, size/XS, approved, lgtm

#3040 Doc: Update release doc for clarifying legacy branch workflow
  RELEASES.md
Labels: cncf-cla: yes, size/S, approved, lgtm

#3041 Release: Adjust release workflow validate logic for legacy-branch
  .github/workflows/release.yml
Labels: cncf-cla: yes, size/XS, approved, lgtm

#3081 Add null guards for Exec.ExecutionBuilder
  util/src/main/java/io/kubernetes/client/Exec.java
  util/src/test/java/io/kubernetes/client/ExecTest.java
Labels: cncf-cla: yes, size/S, approved, lgtm

#3111 Change DefaultSharedIndexInformer constructor to use threadFactory
  util/src/main/java/io/kubernetes/client/informer/impl/DefaultSharedIndexInformer.java
  util/src/test/java/io/kubernetes/client/informer/impl/DefaultSharedIndexInformerTest.java
Labels: cncf-cla: yes, size/M, approved, lgtm

#3126 update: update wiremock & jackson
  examples/examples-release-17/pom.xml
  examples/examples-release-18/pom.xml
  examples/examples-release-19/pom.xml
  examples/examples-release-20/pom.xml
  examples/examples-release-latest/pom.xml
  extended/pom.xml
  pom.xml
  spring/pom.xml
  util/pom.xml
Labels: cncf-cla: yes, size/M, approved, lgtm

#3124 build: remove redundant groupId in poms that do it
  client-java-contrib/admissionreview/pom.xml
  e2e/pom.xml
  fluent-gen/pom.xml
  fluent/pom.xml
  kubernetes/pom.xml
  proto/pom.xml
  spring-aot/pom.xml
  spring/pom.xml
  util/pom.xml
Labels: cncf-cla: yes, size/XS, approved, lgtm

#3118 update maven wrapper to latest, and adjust CI to use it
  .github/workflows/maven.yml
  .github/workflows/release.yml
  .mvn/wrapper/MavenWrapperDownloader.java
  .mvn/wrapper/maven-wrapper.jar
  .mvn/wrapper/maven-wrapper.properties
  RELEASES.md
  mvnw
  mvnw.cmd
Labels: size/L, cncf-cla: yes, approved, lgtm
