Repository kubernetes-client/java, pull requests merged in 2024-07, with the labels that each got.

#3534 Update pom.xml - com.bucket4j migration
  extended/pom.xml
  pom.xml
Labels: cncf-cla: yes, size/XS, approved, lgtm

#3563 Migrate deprecated Bucket4J class usage to Bucket class to unblock upgrade
  extended/src/main/java/io/kubernetes/client/extended/event/legacy/EventSpamFilter.java
  extended/src/main/java/io/kubernetes/client/extended/workqueue/ratelimiter/BucketRateLimiter.java
  pom.xml
Labels: cncf-cla: yes, size/XS, approved, lgtm

#3560 Move `optional` tags to module POMs
  extended/pom.xml
  pom.xml
  spring/pom.xml
  util/pom.xml
Labels: cncf-cla: yes, size/M, approved, lgtm

#3569 Fix for comment in example code snippet is inconsistent #3506
  examples/examples-release-17/src/main/java/io/kubernetes/client/examples/KubeConfigFileClientExample.java
  examples/examples-release-18/src/main/java/io/kubernetes/client/examples/KubeConfigFileClientExample.java
  examples/examples-release-19/src/main/java/io/kubernetes/client/examples/KubeConfigFileClientExample.java
  examples/examples-release-20/src/main/java/io/kubernetes/client/examples/KubeConfigFileClientExample.java
  examples/examples-release-latest/src/main/java/io/kubernetes/client/examples/KubeConfigFileClientExample.java
Labels: cncf-cla: yes, size/S, approved, lgtm

#3572 Added support for passing delete options when using kubectlDelete.#3463
  extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlDelete.java
  extended/src/test/java/io/kubernetes/client/extended/kubectl/KubectlDeleteTest.java
  util/src/main/java/io/kubernetes/client/util/generic/GenericKubernetesApi.java
Labels: cncf-cla: yes, size/S, approved, lgtm

#3582 fix: correct work of DaemonSetIgnore #3545
  extended/src/main/java/io/kubernetes/client/extended/kubectl/KubectlDrain.java
Labels: cncf-cla: yes, size/XS, approved, lgtm

#3601 Migrate deprecated Bucket4J class usage to Bucket class to unblock upgrades
  extended/pom.xml
  extended/src/main/java/io/kubernetes/client/extended/event/legacy/EventSpamFilter.java
  extended/src/main/java/io/kubernetes/client/extended/workqueue/ratelimiter/BucketRateLimiter.java
  pom.xml
Labels: cncf-cla: yes, size/S, approved, lgtm
