Repository kubernetes-client/java, pull requests merged in 2025-01, with the labels that each got.

#3870 Manually bumping release-legacy-21 pom version to 21.0.2-legacy-SNAPSHOT
  client-java-contrib/admissionreview/pom.xml
  client-java-contrib/cert-manager/pom.xml
  client-java-contrib/prometheus-operator/pom.xml
  e2e/pom.xml
  examples/examples-release-16/pom.xml
  examples/examples-release-17/pom.xml
  examples/examples-release-18/pom.xml
  examples/examples-release-19/pom.xml
  examples/pom.xml
  extended/pom.xml
  fluent-gen/pom.xml
  fluent/pom.xml
  kubernetes/pom.xml
  pom.xml
  proto/pom.xml
  spring-aot/pom.xml
  spring/pom.xml
  util/pom.xml
Labels: cncf-cla: yes, size/M, approved, lgtm

#3869 Clarifying legacy release workflow instructions
  .github/workflows/release.yml
Labels: cncf-cla: yes, size/XS, approved, lgtm

#3875 Manual update release 21.0.2-legacy
  client-java-contrib/admissionreview/pom.xml
  client-java-contrib/cert-manager/pom.xml
  client-java-contrib/prometheus-operator/pom.xml
  e2e/pom.xml
  examples/examples-release-16/pom.xml
  examples/examples-release-17/pom.xml
  examples/examples-release-18/pom.xml
  examples/examples-release-19/pom.xml
  examples/pom.xml
  extended/pom.xml
  fluent-gen/pom.xml
  fluent/pom.xml
  kubernetes/pom.xml
  pom.xml
  proto/pom.xml
  spring-aot/pom.xml
  spring/pom.xml
  util/pom.xml
Labels: cncf-cla: yes, size/M, approved, lgtm

#3877 Release-22: Bump the latest pom version to 22.0.1-SNAPSHOT
  client-java-contrib/admissionreview/pom.xml
  client-java-contrib/cert-manager/pom.xml
  client-java-contrib/prometheus-operator/pom.xml
  e2e/pom.xml
  examples/examples-release-latest/pom.xml
  examples/pom.xml
  extended/pom.xml
  fluent-gen/pom.xml
  fluent/pom.xml
  kubernetes/pom.xml
  pom.xml
  proto/pom.xml
  spring-aot/pom.xml
  spring/pom.xml
  util/pom.xml
Labels: cncf-cla: yes, size/M, approved, lgtm

#3878 Automated Release: 22.0.0-legacy
  client-java-contrib/admissionreview/pom.xml
  client-java-contrib/cert-manager/pom.xml
  client-java-contrib/prometheus-operator/pom.xml
  e2e/pom.xml
  examples/examples-release-17/pom.xml
  examples/examples-release-18/pom.xml
  examples/examples-release-19/pom.xml
  examples/examples-release-20/pom.xml
  examples/examples-release-latest/pom.xml
  examples/pom.xml
  extended/pom.xml
  fluent/pom.xml
  kubernetes/pom.xml
  pom.xml
  proto/pom.xml
  spring-aot/pom.xml
  spring/pom.xml
  util/pom.xml
Labels: cncf-cla: yes, size/M, approved, lgtm

#3879 Bump master branch version to 23.0.0-SNAPSHOT
  client-java-contrib/admissionreview/pom.xml
  client-java-contrib/cert-manager/pom.xml
  client-java-contrib/prometheus-operator/pom.xml
  e2e/pom.xml
  examples/examples-release-17/pom.xml
  examples/examples-release-18/pom.xml
  examples/examples-release-19/pom.xml
  examples/examples-release-20/pom.xml
  examples/examples-release-latest/pom.xml
  examples/pom.xml
  extended/pom.xml
  fluent-gen/pom.xml
  fluent/pom.xml
  kubernetes/pom.xml
  pom.xml
  proto/pom.xml
  spring-aot/pom.xml
  spring/pom.xml
  util/pom.xml
Labels: cncf-cla: yes, size/M, approved, lgtm

#3856 Enable the reuse of cached informers on creation by `SharedInformerFactory`.
  util/src/main/java/io/kubernetes/client/informer/SharedInformerFactory.java
  util/src/test/java/io/kubernetes/client/informer/SharedInformerFactoryTest.java
Labels: size/L, cncf-cla: yes, approved, lgtm
