Repository kubernetes-client/java, pull requests merged in 2025-07, with the labels that each got.

#4113 Migrate EKS authentication from AWS 1.x -> AWS 2.x
  examples/examples-release-latest/pom.xml
  examples/examples-release-latest/src/main/java/io/kubernetes/client/examples/EKSAuthenticationExample.java
  pom.xml
  util/pom.xml
  util/src/main/java/io/kubernetes/client/util/credentials/EKSAuthentication.java
  util/src/test/java/io/kubernetes/client/util/credentials/EKSAuthenticationTest.java
Labels: size/L, cncf-cla: yes, approved, lgtm

#4140 fix: correct fieldManager parameter in makeClusterCreateCallBuilder
  util/src/main/java/io/kubernetes/client/util/generic/GenericKubernetesApi.java
Labels: cncf-cla: yes, size/XS, approved, lgtm

#4152 Add ApiClient in ClientBuilder
  util/src/main/java/io/kubernetes/client/util/ClientBuilder.java
Labels: cncf-cla: yes, size/S, approved, lgtm
