Repository kubernetes-client/java, pull requests merged in 2025-02, with the labels that each got.

#3896 Refreshes the patches files
  scripts/patches/json.diff
  scripts/patches/list-meta.diff
  scripts/patches/secret.diff
  scripts/patches/status.diff
Labels: cncf-cla: yes, size/M, approved, lgtm

#3897 Bump master java8 22.0.0-legacy
  client-java-contrib/admissionreview/pom.xml
  client-java-contrib/cert-manager/pom.xml
  client-java-contrib/prometheus-operator/pom.xml
  e2e/pom.xml
  examples/examples-release-16/pom.xml
  examples/examples-release-17/pom.xml
  examples/examples-release-18/pom.xml
  examples/examples-release-19/pom.xml
  examples/pom.xml
  extended/pom.xml
  fluent-gen/pom.xml
  fluent/pom.xml
  kubernetes/pom.xml
  kubernetes/src/main/java/io/kubernetes/client/openapi/ApiClient.java
  pom.xml
  proto/pom.xml
  spring-aot/pom.xml
  spring/pom.xml
  util/pom.xml
Labels: cncf-cla: yes, size/M, approved, lgtm

#3898 Chore: Sync up repo infra assets from master branch
  .github/workflows/generate.yml
  .github/workflows/release.yml
  scripts/patches/json.diff
  scripts/patches/list-meta.diff
  scripts/patches/secret.diff
  scripts/patches/status.diff
Labels: size/L, cncf-cla: yes, approved, lgtm

#3903 Branch(master-java8): Remove "JSON.java" from openapi gen ignore file
  kubernetes/.openapi-generator-ignore
Labels: cncf-cla: yes, size/XS, approved, lgtm

#3904 Branch(master-java8): Sync missing source files from master branch
  kubernetes/pom.xml
  kubernetes/src/main/java/io/kubernetes/client/custom/MapUtils.java
  kubernetes/src/main/java/io/kubernetes/client/gson/V1MetadataExclusionStrategy.java
  pom.xml
Labels: cncf-cla: yes, size/M, approved, lgtm

#3907 chore(deps): remove unused jakarta.ws.rs-api dependency
  kubernetes/pom.xml
  pom.xml
Labels: cncf-cla: yes, size/XS, approved, lgtm

#3908 Chore: Remove unneeded patch
  scripts/patches/list-meta.diff
  scripts/patches/status.diff
Labels: cncf-cla: yes, size/M, approved, lgtm

#3909 Remove unused dependencies from extended, spring, and root module
  extended/pom.xml
  pom.xml
  spring/pom.xml
Labels: cncf-cla: yes, size/S, approved, lgtm

#3914 Automated release 22.0.1 legacy
  client-java-contrib/admissionreview/pom.xml
  client-java-contrib/cert-manager/pom.xml
  client-java-contrib/prometheus-operator/pom.xml
  e2e/pom.xml
  examples/examples-release-16/pom.xml
  examples/examples-release-17/pom.xml
  examples/examples-release-18/pom.xml
  examples/examples-release-19/pom.xml
  examples/pom.xml
  extended/pom.xml
  fluent/pom.xml
  kubernetes/pom.xml
  pom.xml
  proto/pom.xml
  spring-aot/pom.xml
  spring/pom.xml
  util/pom.xml
Labels: cncf-cla: yes, size/M, approved, lgtm

#3915 Automated release 22.0.1
  client-java-contrib/admissionreview/pom.xml
  client-java-contrib/cert-manager/pom.xml
  client-java-contrib/prometheus-operator/pom.xml
  e2e/pom.xml
  examples/examples-release-17/pom.xml
  examples/examples-release-18/pom.xml
  examples/examples-release-19/pom.xml
  examples/examples-release-20/pom.xml
  examples/examples-release-latest/pom.xml
  examples/pom.xml
  extended/pom.xml
  fluent/pom.xml
  kubernetes/pom.xml
  pom.xml
  proto/pom.xml
  spring-aot/pom.xml
  spring/pom.xml
  util/pom.xml
Labels: cncf-cla: yes, size/M, approved, lgtm

#3930 fix: add missing continue token when build cluster list call
  util/src/main/java/io/kubernetes/client/util/generic/GenericKubernetesApi.java
  util/src/test/java/io/kubernetes/client/util/generic/GenericKubernetesListApiTest.java
Labels: size/L, cncf-cla: yes, approved, lgtm

#3931 Branch(release-23): Automated release 23.0.0
  client-java-contrib/admissionreview/pom.xml
  client-java-contrib/cert-manager/pom.xml
  client-java-contrib/prometheus-operator/pom.xml
  e2e/pom.xml
  examples/examples-release-17/pom.xml
  examples/examples-release-18/pom.xml
  examples/examples-release-19/pom.xml
  examples/examples-release-20/pom.xml
  examples/examples-release-latest/pom.xml
  examples/pom.xml
  extended/pom.xml
  fluent/pom.xml
  kubernetes/pom.xml
  pom.xml
  proto/pom.xml
  spring-aot/pom.xml
  spring/pom.xml
  util/pom.xml
  util/src/test/java/io/kubernetes/client/util/generic/GenericKubernetesListApiTest.java
Labels: cncf-cla: yes, size/M, approved, lgtm

#3932 Branch(release-legacy-23): Automated release 23.0.0 legacy
  client-java-contrib/admissionreview/pom.xml
  client-java-contrib/cert-manager/pom.xml
  client-java-contrib/prometheus-operator/pom.xml
  e2e/pom.xml
  examples/examples-release-16/pom.xml
  examples/examples-release-17/pom.xml
  examples/examples-release-18/pom.xml
  examples/examples-release-19/pom.xml
  examples/pom.xml
  extended/pom.xml
  fluent/pom.xml
  kubernetes/pom.xml
  pom.xml
  proto/pom.xml
  spring-aot/pom.xml
  spring/pom.xml
  util/pom.xml
Labels: cncf-cla: yes, size/M, approved, lgtm

#3939 Chore: Re-run spotless formatter
  util/src/test/java/io/kubernetes/client/util/generic/GenericKubernetesListApiTest.java
Labels: cncf-cla: yes, size/S, approved, lgtm

#3942 Deflake a test
  extended/src/test/java/io/kubernetes/client/extended/controller/DefaultControllerTest.java
Labels: cncf-cla: yes, size/XS, approved, lgtm

#3952 Switch to Countdown latch and actually use it for test.
  util/src/test/java/io/kubernetes/client/ExecTest.java
Labels: cncf-cla: yes, size/M, approved, lgtm
